### ISSUE TITLE
ProtectedMethodInFinalClassCheck.java:44-50: Make...

### ISSUE THREAD

**Issue by 0pdd** [teamed/qulice#1006]
The puzzle `917-27a2aa28` from #917 has to be resolved: 

https://github.com/teamed/qulice/blob/995e28a3c2033ddb09d32f1e9dc7214bf833b741/qulice-checkstyle/src/main/java/com/qulice/checkstyle/ProtectedMethodInFinalClassCheck.java#L44-L50

The puzzle was created by Paulo Lobo on 21-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1006](https://github.com/teamed/qulice/issues/1006) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1006](https://github.com/teamed/qulice/issues/1006) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/aff48104-5a69-49a6-8f29-1730d31fe0ca); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat Wait for #1025 review

**Comment by 0pdd** [comment]
The puzzle `917-27a2aa28` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
> @0crat Wait for #1025 review ([here](https://github.com/teamed/qulice/issues/1006#issuecomment-461421427))

@paulodamaso The impediment for [#1006](https://github.com/teamed/qulice/issues/1006) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1006](https://github.com/teamed/qulice/issues/1006) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/teamed/qulice/issues/1006#issuecomment-461519111))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
