### ISSUE TITLE
Update jcabi-parent to 0.49.4 (solves xcop issue)

### ISSUE THREAD

**Issue by fabriciofx** [teamed/qulice#1017]
Let's update to new jcabi version (0.49.4) because this new version solves `xcop` issue on Windows. Besides, let's:
1. Fix the formatting of the project XML files
2. Add `xcop` to travis and rultor (we can based it on `cactoos` project)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/1017#issuecomment-458225819))

@paulodamaso You can't do "Add job to WBS", unless you have one of these roles: `ARC`, `PO`; current roles of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) are: `DEV`, `REV`

**Comment by krzyk** [comment]
@fabriciofx this doesn't look like a big change, so maybe add also that we should fix all our xml files to match the xcop rules and add xcop to rultor and travis

**Comment by krzyk** [comment]
@fabriciofx ping

**Comment by fabriciofx** [comment]
@krzyk IMHO, I think an important change for two reasons:

1. Will force us to assure all XML files are formatted properly;
2. If I've `xcop` installed in my Windows machine and don't update to this change, the maven's install cycle doesn't perform correctly and don't install the artifact locally.

**Comment by krzyk** [comment]
@fabriciofx Please see my previous comment, I agree, but it would be good to include in the description to also fix the formatting of the project xml files and add xcop to travis and rultor.

**Comment by fabriciofx** [comment]
@krzyk Sorry. I'll do that.

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/1017#issuecomment-460320434))

@krzyk Job [#1017](https://github.com/teamed/qulice/issues/1017) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#1017](https://github.com/teamed/qulice/issues/1017) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/ea8a7ccb-a1c0-4ca4-a37c-7e903b1d5f04); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1017](https://github.com/teamed/qulice/issues/1017); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by zCRUSADERz** [comment]
@krzyk please assign me.

**Comment by krzyk** [comment]
@0crat assign @zCRUSADERz

**Comment by 0crat** [comment]
> @0crat assign @zCRUSADERz  ([here](https://github.com/teamed/qulice/issues/1017#issuecomment-494671541))

@krzyk The job [#1017](https://github.com/teamed/qulice/issues/1017) assigned to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz), here is [why](https://www.0crat.com/footprint/C3T49A35L/e01f4f87-b109-4fa5-b3f1-9178a70c205b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by zCRUSADERz** [comment]
@fabriciofx ping, fixed.

**Comment by fabriciofx** [comment]
@zCRUSADERz @krzyk Sounds good to me. I'll close this issue. Thanks!

**Comment by 0crat** [comment]
Job was finished in 6 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1017](https://github.com/teamed/qulice/issues/1017) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz)
