### ISSUE TITLE
pom.xml:138-140: Upgrade to Junit5. Continue to upgrade...

### ISSUE THREAD

**Issue by 0pdd** [teamed/qulice#1019]
The puzzle `939-39a57206` from #939 has to be resolved: 

https://github.com/teamed/qulice/blob/93cf62a79a6903b6d1bbb3d487982bf4a7f55971/pom.xml#L138-L140

The puzzle was created by @rultor on 30-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1019](https://github.com/teamed/qulice/issues/1019) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1019](https://github.com/teamed/qulice/issues/1019) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/045db3d7-d0b2-43d1-a1bd-5f97244c4f8b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat Wait for #1027 review and merge

**Comment by 0crat** [comment]
> @0crat Wait for #1027 review and merge ([here](https://github.com/teamed/qulice/issues/1019#issuecomment-461558366))

@paulodamaso The impediment for [#1019](https://github.com/teamed/qulice/issues/1019) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `939-39a57206` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1030](https://github.com/teamed/qulice/issues/1030) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1019](https://github.com/teamed/qulice/issues/1019) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/teamed/qulice/issues/1019#issuecomment-461711042))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
