### ISSUE TITLE
UseStringIsEmptyRule complains when checking String[].length

### ISSUE THREAD

**Issue by ilyakharlamov** [teamed/qulice#1031]
Steps to reproduce:
```java
/*
 */
package com.mycompany.app;
/**
 * Hello world!
 * @since 1.0
 */
@SuppressWarnings("PMD.UseUtilityClass")
public final class App {
    /**
     * Ctor.
     */
    private App() { }

    /**
     * Main.
     * @param args Arguments
     */
    public static void main(final String... args) {
        if (args.length > 0) {
            System.out.println("args are not empty");
        }
    }
}
```

run `mvn clean install -Pqulice`

What's wrong:
`PMD: src/main/java/com/mycompany/app/App.java[20-20]: Use String.isEmpty() when checking for empty string (UseStringIsEmptyRule)`

We check an array of Strings but not a String.
There is no string length check at all in this code. 
There is no such thing as  `String[].isEmpty()` either.
We check `String[].length` but not `String.length()` here.

Expected result:
The rule should complain on `String` but should not complain on `String[]`.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/1031#issuecomment-465465588))

@krzyk Job [#1031](https://github.com/teamed/qulice/issues/1031) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#1031](https://github.com/teamed/qulice/issues/1031); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by zCRUSADERz** [comment]
@krzyk assign me, please.

**Comment by krzyk** [comment]
@0crat assign @zCRUSADERz

**Comment by 0crat** [comment]
> @0crat assign @zCRUSADERz  ([here](https://github.com/teamed/qulice/issues/1031#issuecomment-488357501))

@krzyk The job [#1031](https://github.com/teamed/qulice/issues/1031) assigned to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz), here is [why](https://www.0crat.com/footprint/C3T49A35L/587e6fec-0828-43a2-8ce0-2edc17afc1c2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by zCRUSADERz** [comment]
@ilyakharlamov merged, please close

**Comment by zCRUSADERz** [comment]
@0crat wait for closure

**Comment by 0crat** [comment]
> @0crat wait for closure ([here](https://github.com/teamed/qulice/issues/1031#issuecomment-488907460))

@zCRUSADERz The impediment for [#1031](https://github.com/teamed/qulice/issues/1031) was registered successfully by @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz)

**Comment by 0crat** [comment]
> @0crat wait for closure ([here](https://github.com/teamed/qulice/issues/1031#issuecomment-488907460))

@zCRUSADERz Job [#1031](https://github.com/teamed/qulice/issues/1031) is not in the agenda of @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz), can't set impediment

**Comment by ilyakharlamov** [comment]
@zCRUSADERz Thanks, closed

**Comment by 0crat** [comment]
Job [#1031](https://github.com/teamed/qulice/issues/1031) is not in the agenda of @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1031](https://github.com/teamed/qulice/issues/1031) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz)
