### ISSUE TITLE
ChecksTest in qulice-checkstyle dont run automatically when building with maven.

### ISSUE THREAD

**Issue by zCRUSADERz** [teamed/qulice#1037]
Qulice 0.18.16. 
----
### Instruction
`git checkout 0.18.16`
`cd qulice-checkstyle`
`mvn -Dtest=ChecksTest test`

 #### Result
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project qulice-checkstyle: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.)`

If you run these tests in IDE then one test out of 36 will fail.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@0crat in

**Comment by krzyk** [comment]
@0crat assign @zCRUSADERz

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/1037#issuecomment-487962489))

@krzyk Job [#1037](https://github.com/teamed/qulice/issues/1037) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign @zCRUSADERz  ([here](https://github.com/teamed/qulice/issues/1037#issuecomment-487962519))

@krzyk The job [#1037](https://github.com/teamed/qulice/issues/1037) assigned to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz), here is [why](https://www.0crat.com/footprint/C3T49A35L/ca4d1b8e-2fc2-4cc1-90db-dd99e81893fc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by zCRUSADERz** [comment]
In #1041 issue has been fixed.

**Comment by zCRUSADERz** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/teamed/qulice/issues/1037#issuecomment-488667462))

@zCRUSADERz This is what I know about this job in [C3T49A35L](https://www.0crat.com/p/C3T49A35L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1037](https://github.com/teamed/qulice/issues/1037) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is assigned to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T49A35L?q=%7Bjob%3A%27gh%3Ateamed%2Fqulice%231037%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job [#1037](https://github.com/teamed/qulice/issues/1037) is not in the agenda of @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1037](https://github.com/teamed/qulice/issues/1037) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz)
