### ISSUE TITLE
PMD.ProhibitPublicStaticMethods happens for "public static void main(String[] args)"

### ISSUE THREAD

**Issue by aistomin** [teamed/qulice#1057]
# The Problem
In scope of #659 Methods like `public static void main(final String... args)` are excluded from validation, but the error still happens for methods like `public static void main(final String[] args)`

# Expected solution
The error should not happen for neither `public static void main(final String... args)` nor `public static void main(final String[] args)`. Or I need an explanation of what is the principal difference between these two forms.

# Examples
The code:
```
public final class SomeClass {
    public static void main(final String... args) {
    }
}
```
doesn't produce the error.
The code:
```
public final class SomeClass {
    public static void main(final String[] args) {
    }
}
```
produces the error.

# Environment
I use:
```
<plugin>
    <groupId>com.qulice</groupId>
    <artifactId>qulice-maven-plugin</artifactId>
    <version>0.18.19</version>
</plugin>
```

Thanks in advance!

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@aistomin[/z](https://www.0crat.com/u/aistomin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by aistomin** [comment]
Ah, sorry, my bad, I didn't notice that there is another issue with the same problem: #825

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1057` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
