### ISSUE TITLE
HeaderCheck and JavadocStyleCheck checks doesn't work together

### ISSUE THREAD

**Issue by Sammers21** [teamed/qulice#1065]
In a project i have a `package-info.java` file. 

I'm getting : `Line does not match expected header line of '/*'. (HeaderCheck)` if the first line is `/**`, and getting `Missing a Javadoc comment. (JavadocStyleCheck)` in case when the first line is `/*`, which, i think, is a strange and non-expected behaviour.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@sammers21[/z](https://www.0crat.com/u/sammers21) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#1065` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
