### ISSUE TITLE
RedundantThrowsCheck for inner classes

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#113]
We still have the same problem as explained in #41, but only for inner classes, for example: http://relics.rultor.com.s3.amazonaws.com/urn:facebook:1531296526/rultor-on-commit/stdout/2013-10-28T10:50:00Z/log.txt

**Comment by davvd** [comment]
@cyberone the task is your hands for the last 12 days.. keep in mind that if it's not closed in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -30 to your rating, your total score is [-130](http://www.netbout.com/b/35076?open=rating)

**Comment by cyberone** [comment]
@davvd reassign please

**Comment by yegor256** [comment]
@davvd assign someone else here pls

**Comment by davvd** [comment]
> @davvd assign someone else here pls

@yegor256 got it, someone else will be assigned soon

**Comment by davvd** [comment]
@cyberone you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle

added -60 to your rating, now it is equal to [-670](http://www.netbout.com/b/35076?open=rating)

**Comment by davvd** [comment]
@maurezen please proceed, it's yours

**Comment by maurezen** [comment]
@davvd @yegor256 could you please elaborate a bit on the topic of rating changes upon voluntary task rejection?

Also, the bug doesn't seem to be fixed in checkstyle, so what's really in the scope of this task? Inventing a workaround or just waiting indefinitely?

And finally, is there a minimal, complete, and verifiable example for reproducing this bug? Or at least, could you link me to a repo on which qulice:check fails with this exact problem?

**Comment by yegor256** [comment]
@maurezen if you reject a task by yourself, your rating is not affected. It's a good practice, if you don't want to work with the task or just don't know how. In this task I would suggest to reproduce the problem with a test and then "skip" it and merge. That will be enough. See http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by maurezen** [comment]
@yegor256 I actually can reproduce on your version of qulice, 0.3.1. As of master branch, rultor uses 0.10 (or 0.12, if it had already been incorporated), so it looks like the problem is no longer there. What do we do now?

**Comment by maurezen** [comment]
@yegor256 any comment?

**Comment by maurezen** [comment]
@yegor256 @davvd created a pull request here  #386

**Comment by maurezen** [comment]
@yegor256 pull request #386 merged to master. Please close the issue.

**Comment by yegor256** [comment]
thanks!

**Comment by maurezen** [comment]
@davvd this issue is closed.

**Comment by davvd** [comment]
@maurezen Thank you, I've added **30 mins** to your account in payment/transaction "`50593423`"... added +30 to your rating, now it is equal to [+750](http://www.netbout.com/b/35102?open=rating)
