### ISSUE TITLE
incorrect indentation of the first call

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#139]
This is what qulice is asking now:

```java
new String()
  .substring(
    0, 100
) // this is a bug
  .substring(
    0, 50
  );
```

While correct positioning would be:

```java
new String()
  .substring(
    0, 100
  )
  .substring(
    0, 50
  );
```

**Comment by carlosmiranda** [comment]
Fixed in Checkstyle 5.9 (which we are using now). Please see pull request https://github.com/teamed/qulice/pull/405, I added a test case to check that this is working.

**Comment by carlosmiranda** [comment]
@davvd We're waiting for #405.

**Comment by davvd** [comment]
> @davvd We're waiting for #405.

@carlosmiranda sure, let's wait for #405

**Comment by carlosmiranda** [comment]
@yegor256 This has been resolved (finally!) in #405. :) May we close this now?

**Comment by davvd** [comment]
Issue #405 is already closed (we were waiting for it) Maybe we can continue..

**Comment by carlosmiranda** [comment]
@yegor256 May we close this?

**Comment by carlosmiranda** [comment]
@yegor256 Can we close this now...?

**Comment by yegor256** [comment]
thanks!

**Comment by davvd** [comment]
@carlosmiranda done, I added **30 mins** in payment `52798023`; +30 to your rating, your total score is [+3331](http://www.netbout.com/b/35023?open=rating)
