### ISSUE TITLE
prohibit declaring a checked exception if it's not thrown

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#144]
Let's create a new check, which will prohibit the following:

```java
public void doSmth() throws IOException {
  // empty method
}
```

This method doesn't throw `IOException`, while declares it as being thrown. This is wrong and should be prohibited.

**Comment by davvd** [comment]
@jenya the ticket is with you for 12 days already. If it's not finished in the next 24 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -30 to your rating, your total score is [-45](http://www.netbout.com/b/35092?open=rating)

**Comment by yegor256** [comment]
@dmarkov please assign someone else

**Comment by davvd** [comment]
@jenya you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, current score is: [-615](http://www.netbout.com/b/35092?open=rating)

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I will try to assign someone else

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by krzyk** [comment]
@davvd please see PR #677

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd assign @krzyk

@krzyk OK @krzyk please go ahead, this task is yours

**Comment by davvd** [comment]
> @davvd please see PR #677 

@krzyk will take a look at it, thanks

**Comment by krzyk** [comment]
@yegor256 finally this has been resolved (at least for majority of our cases - all private methods, and all public ones that are final). Please close this issue if it is OK.

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by krzyk** [comment]
@yegor256 does #677 solve the problem?

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by davvd** [comment]
@krzyk Thank you, I have added **30 mins** to your account in payment/transaction "`77096891`", time consumed: 119 hours and 59 mins. +30 to your rating, your total score is [+5551](http://www.netbout.com/b/35035?open=rating)
