### ISSUE TITLE
UnusedPrivateField complains about constants in inner classes

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#173]
This is my code:

```java
interface Foo {
  final class Bar implements Foo {
    private static final Pattern TEST = Pattern.compile("hey");
    public String doSmth() {
      return Foo.Bar.TEST.toString();
    }
  }
}
```

PMD says:

```
Avoid unused private fields such as 'TEST'. (UnusedPrivateField)
```

I believe it's a bug.

**Comment by davvd** [comment]
@flexelem you've been working with this task for too long. I'm sorry, but I'll assign someone else. Please stop working with it. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: -305

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk someone else will help in this task, no problem at all

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd assign @mkordas please 

@krzyk OK @mkordas please start, the task is yours

**Comment by davvd** [comment]
> @davvd this is not postponed 

@krzyk right, I removed "postponed" tag

**Comment by mkordas** [comment]
@davvd please see PR #571

**Comment by davvd** [comment]
> @davvd please see PR #571

@mkordas thanks, will take a look

**Comment by mkordas** [comment]
@yegor256 test confirming issue is fixed was done in  #571, please close the issue

**Comment by mkordas** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@mkordas thanks!

**Comment by davvd** [comment]
@mkordas done, I added **30 mins** in payment `568ce9e525bd4b3dc600026c`, 98 hours and 23 mins spent to complete this; +30 added to your rating, at the moment it is: [+1300](http://www.netbout.com/b/36080?open=rating)
