### ISSUE TITLE
pom.xml:300-303: Rename volations.JS to violations.js after...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#301]
Puzzle `251-723b0584` in `qulice-maven-plugin/pom.xml:300-303` has to be resolved: Rename volations.JS to violations.js after a new version of parent is published (that uses qulice which has jslint configured to use src/main for the js file locations) and uncomment following line.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd please close this issue

**Comment by krzyk** [comment]
I was to fast with closing, PR actually has to be reviewed and merged first :)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by davvd** [comment]
Thanks all, closed

**Comment by davvd** [comment]
@krzyk Thanks for your contribution, **30 mins** was added to your account, payment ID is `50258553`. +30 to your rating, your total score is [+1459](http://www.netbout.com/b/35035?open=rating)
