### ISSUE TITLE
DuplicateFinderValidator.java:58-60: Fix a problem with maven...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#309]
Puzzle `250-bd6aad88` in `qulice-maven-plugin/src/main/java/com/qulice/maven/DuplicateFinderValidator.java:58-60` has to be resolved: Fix a problem with maven configuration of duplicate finder plugin in commented out code below, and enable duplicate-finder-ignore-deps IT in pom.xml.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd please assign someone else

**Comment by davvd** [comment]
> @davvd please assign someone else

@krzyk 30 points deducted from your rating

**Comment by davvd** [comment]
> @davvd please assign someone else

@krzyk I will ask somebody else to pick this up

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by davvd** [comment]
@krzyk Done, thanks all, closing..
