### ISSUE TITLE
Add option to exclude certain packages from cobertura check

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#322]
This would be useful when project starts using cobertura and needs a adjustment phase to do so.
There is an option in maven cobertura plugin http://mojo.codehaus.org/cobertura-maven-plugin/usage.html

**Comment by davvd** [comment]
@flexelem the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html); -60 added to your rating, current score is: -365

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I will find someone else, no problem

**Comment by krzyk** [comment]
@krzyk this is out of scope of qulice project
