### ISSUE TITLE
Add suport for ignoreMethodAnnotations in cobertura plugin

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#323]
Since maven cobertura plugin 2.6 there is a configuration parameter (``ignoreMethodAnnotations``) that allows ignoring methods by specified annotation from coverage report.
It is very useful for ignoring automatically generated methods that shouldn't be covered by this plugin (e.g. lombok ``toString`` or ``equals``), AFAIR lombok already annotates generated methods with ``@Generated``.

**Comment by davvd** [comment]
@alexdag this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@alexdag you're holding this ticket for 19 days already. If it's not finished (and closed) in the next 2 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck)... -30 to your rating, your total score is [-360](http://www.netbout.com/b/35099?open=rating)

**Comment by davvd** [comment]
@alexdag it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 to your rating, your total score is [-420](http://www.netbout.com/b/35099?open=rating)

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@krzyk this is out of scope of qulice project
