### ISSUE TITLE
Allow configuration of cobertura check coverage

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#324]
When project is migrating to cobertura it doesn't happen overnight to reach 80% coverage, it is best to increase the coverage by small steps (start e.g. with 10% and go up to 80%).
Add a configuration option to qulice to change line/branch coverage parameters per project.

**Comment by davvd** [comment]
@longtimeago this task is not yours any more (took too long), please stop. I'll give you something else

**Comment by davvd** [comment]
@alexdag please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@alexdag it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, current score is: [-480](http://www.netbout.com/b/35099?open=rating)

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by krzyk** [comment]
@krzyk this is out of scope of qulice project
