### ISSUE TITLE
Eclipse formatter

### ISSUE THREAD

**Issue by caarlos0** [teamed/qulice#325]
It would be nice to have an Eclipse formatter and cleanup that fits the rules. That will make it easier to make all the code fits (format an entire package, for example).

**Comment by wb14123** [comment]
Hi, @caarlos0 

Is this working for you?

**Comment by caarlos0** [comment]
@wb14123 I believe that the plugins will not get the custom configs from Qulice...

Did you managed to make it all works...

**Comment by wb14123** [comment]
@caarlos0  I find that these plugins could import configurations manually:

* [Using common Checkstyle rules for teams](http://www.vogella.com/tutorials/Checkstyle/article.html#checkstyle_remoteaccess)
* [Importing rules for PMD Eclipse](http://stackoverflow.com/questions/16778062/importing-rules-for-pmd-eclipse)
* FindBugs. I don't find custom configuration in Qulice.
* CodeNarc. I don't find any doc. If it is not working I will have a try on my laptop.

I don't have Eclipse installed for now. Is there any of those not working? I will have a try. Thanks.

**Comment by wb14123** [comment]
@caarlos0  BTW, the configuration files in Qulice could be found in the resources folder.

**Comment by caarlos0** [comment]
Neat!

Maybe we should document this, them?

The most annoying issue for me is, actually, the code formatter (hence I opened this issue), because qulice always complains and it took me some time to setup it quite right...

What do you think?

**Comment by wb14123** [comment]
You could give [this](http://stackoverflow.com/questions/984778/how-to-generate-an-eclipse-formatter-configuration-from-a-checkstyle-configurati) a try. It seems that CheckStyle plugin could generate a formatter for Eclipse.

**Comment by caarlos0** [comment]
@wb14123 I got an error importing the configs:

![screen shot 2015-01-08 at 11 56 30 am](https://cloud.githubusercontent.com/assets/245435/5663399/9561b7e2-972d-11e4-8907-e581e77f11fc.png)

Anyways, it doesn't solve the problem of formatting the code itself.

**Comment by wb14123** [comment]
There are two properties `{header}` and `{cache.file}` will be passed from program. You can click "edit properties" to edit them. However, after that need to [install custom checks](http://eclipse-cs.sourceforge.net/#!/custom-checks) from Qulice.

After CheckStyle is configured. [As the link I mentioned](http://stackoverflow.com/questions/984778/how-to-generate-an-eclipse-formatter-configuration-from-a-checkstyle-configurati), you can right click on your project and create a formatter based on the CheckStyle configuration.

![2015-01-09 09 28 26](https://cloud.githubusercontent.com/assets/1906051/5674225/f1369d9e-97e1-11e4-946f-ad0dde94bdfe.png)

The configuration may seems difficult. But I think it's easier to write a formatter by yourself. That is a lot of work to do.

**Comment by caarlos0** [comment]
Seems like it's working now, the only issue is the parenthesis thing, and I believe that this cannot be fixed right now...


Should be:
![screen shot 2015-01-09 at 8 46 25 am](https://cloud.githubusercontent.com/assets/245435/5678676/fd1423d0-97db-11e4-88e0-bff0f43ac4c2.png)


Eclipse format it like this:
![screen shot 2015-01-09 at 8 46 32 am](https://cloud.githubusercontent.com/assets/245435/5678677/fd1ded98-97db-11e4-85c1-c8465fdaf495.png)

Do you think it would be nice to put this in the wiki, or just leave the discussion here is good enough?

**Comment by wb14123** [comment]
If it doesn't format right, you may want to report a bug to CheckStyle plugin. I think it is OK to just leave the discussion here since it seems not working very properly.

**Comment by caarlos0** [comment]
Seems good to me. Actually, this kind of parenthesis formatting isn't allowed by eclipse. So I opened an issue:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=457163

By now, this is fine for me.

**Comment by davvd** [comment]
@wb14123 I added **30 mins** to your account, many thanks for working with the project!; +30 added to your rating, current score is: +75

**Comment by hs3180** [comment]
@wb14123 
I've walked through this ticket, but couldn't find out how to set the `{header}` and `{cache.file}`.
