### ISSUE TITLE
Weird bug with LicenseCheck

### ISSUE THREAD

**Issue by caarlos0** [teamed/qulice#331]
I have a parent pom, where I declare common thing I use in my projects. So, I added to it the qulice profile:

``` xml
<profile>
    <id>qulice</id>
    <build>
        <plugins>
            <plugin>
                <groupId>com.qulice</groupId>
                <artifactId>qulice-maven-plugin</artifactId>
                <version>0.11</version>
                <executions>
                    <execution>
                        <id>check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <license>file:${basedir}/LICENSE</license>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</profile>
```

And in other projects I just declare this project as parent, and _vualá_, `-Pqulice` is working.

But, it causes me a really weird bug. I use the MIT license in both my parent and children projects, but, qulice complains that I should have BSD license headers:

```
Line does not match expected header line of ' * BSD License'. (HeaderCheck)
```

The only place wherer I could find a BSD license is in Qulice. So, my guess is that it's trying to apply Qulice licensing to my project.

Oddly enough, if I add this exclusion:

``` xml
<excludes combine.children="append">
  <exclude>checkstyle:/*/package-info.java</exclude>
</excludes>
```

It works. (for all files, not only package-info's).

Code with the error: caarlos0/guice-junit-test-runner#7

**Comment by AlexDag** [comment]
@davvd  - Can I take this job yet? thanks

**Comment by yegor256** [comment]
@AlexDag sure it's yours, go ahead

**Comment by AlexDag** [comment]
@yegor256 - I'm completing this job,please, I need exact message for checkstyle. Is good this message- ""LICENSE file is not found"?

**Comment by yegor256** [comment]
@AlexDag yes, looks good

**Comment by davvd** [comment]
@alexdag the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... added -60 to your rating, now it is equal to [-330](http://www.netbout.com/b/35099?open=rating)

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by caarlos0** [comment]
🤷‍♂️
