### ISSUE TITLE
Current checkstyle version doesn't work with java 8 code

### ISSUE THREAD

**Issue by caarlos0** [teamed/qulice#335]
It breaks on Lambdas:

```
unexpected token: >
```

And them keeps breaking:

```
Got an exception - expecting EOF, found '}' (TreeWalker)
```

**Comment by palyuga** [comment]
@davvd please, see pull request #360

**Comment by palyuga** [comment]
@caarlos0 pull request has been merged, now Java 8 syntax should be supported, check and close, please

**Comment by davvd** [comment]
@palyuga it's not yours any more,because it took too long,please stop working with it... -60 added to your rating, at the moment it is: +90

**Comment by palyuga** [comment]
@davvd actually, the PR is merged already, so let's wait for a response from the reporter

**Comment by yegor256** [comment]
@davvd pls assign @palyuga back to this issue

**Comment by caarlos0** [comment]
Thanks @palyuga!

**Comment by davvd** [comment]
> @davvd pls assign @palyuga back to this issue

@yegor256 no problem, @palyuga is already assigned to this task, please go on

**Comment by vijaysdey88** [comment]
I am using mave-checkstyle-plugin v2.5. I still get the "EOF expected" error for lambda expression '->'. Could you please suggest a solution?
