### ISSUE TITLE
Checkstyle exceptions more visible

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#338]

**Comment by davvd** [comment]
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment]
we will find someone to do this task, soon

**Comment by davvd** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-92874657

**Comment by krzyk** [comment]
@yegor256 Could you add a description to this bug (if it is still valid)?

**Comment by yegor256** [comment]
@krzyk nah, I'm closing
