### ISSUE TITLE
some.xml:3-4: Make this a better text....

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#349]
Puzzle `123-3eeb54ce` in `qulice-maven-plugin/src/it/checkstyle-violations/src/main/resources/some.xml:3-4` has to be resolved: Make this a better text.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by darkled** [comment]
@davvd the first question is what does this puzzle mean? actual `some.xml` looks like
```xml
<doc>
    <!--
        @todo #123 Make this
         a better text.
    -->
</doc>
```
also this file seems to be never-used anywhere. Therefore I have no idea what is expected to be done within this issue. Could you provide some more details, please?

**Comment by yegor256** [comment]
@darkled I think this entire file should be deleted

**Comment by darkled** [comment]
@yegor256 best solution ever :)

**Comment by darkled** [comment]
@davvd PR was merged, please, check it.

**Comment by davvd** [comment]
Thanks, closed

**Comment by davvd** [comment]
@darkled Much appreciated! **30 mins** was added to your account, payment ID `50258578`; +30 to your rating, your total score is [+180](http://www.netbout.com/b/35091?open=rating)
