### ISSUE TITLE
FindBugsValidatorTest.java:91-94: Add support for multiline excludes....

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#350]
Puzzle `149-29796bc9` in `qulice-findbugs/src/test/java/com/qulice/findbugs/FindBugsValidatorTest.java:91-94` has to be resolved: Add support for multiline excludes. Use xembly Directives to generate xml on the fly. Beware, excludes may contain coma separated list of exclude patterns. When done, remove Ignore annotation on this test.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@wentwog this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by wentwog** [comment]
@davvd withdraw the task from me please, cos I don't currently have time enough to complete it.

**Comment by yegor256** [comment]
@davvd give this to someone else pls

**Comment by davvd** [comment]
> @davvd give this to someone else pls

@yegor256 no problem, I'll try to find somebody else

**Comment by davvd** [comment]
@palyuga could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by palyuga** [comment]
@davvd PR #381 is merged, please check and close this issue

**Comment by davvd** [comment]
@palyuga you're working with this issue for 15 days already... do not forget that the ticket will be closed once the `@todo` puzzle is removed from the code, in master branch... added -30 to your rating, now it is equal to +60

**Comment by palyuga** [comment]
@yegor256 PR #381 is merged and `@todo` is removed, I thought it means the issue should be closed. Should I do something else?

**Comment by yegor256** [comment]
@palyuga you've done it all right, but it all took rather long. the ticket will be closed soon

**Comment by davvd** [comment]
The task is done, thanks all, I'm closing it

**Comment by davvd** [comment]
@palyuga done, I added **30 mins** in payment `51288347`... +30 added to your rating, current score is: +90
