### ISSUE TITLE
MojoExecutor must invoke releaseMojo in a finally block

### ISSUE THREAD

**Issue by alevohin** [teamed/qulice#351]
com.qulice.maven.MojoExecutor must invoke this.manager.releaseMojo(mojo, execution) in a finally block

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@alevohin many thanks for the bug report, I added 15 mins to your acc, transaction `49703778`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I will find someone else, no problem

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by krzyk** [comment]
@davvd see PR #642

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk right, I removed "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @krzyk

@krzyk OK @krzyk please start, the task is yours

**Comment by davvd** [comment]
> @davvd see PR #642 

@krzyk I will take a look, thanks

**Comment by krzyk** [comment]
@alevohin Changes have been merged to master, please close this issue

**Comment by davvd** [comment]
@krzyk paid, thanks, added **45 mins** to your account, payment `75788475`, 27 hours and 56 mins was spent. the bonus for fast delivery (m=1676). +45 to your rating, your total score is [+4477](http://www.netbout.com/b/35035?open=rating)
