### ISSUE TITLE
FindBugsValidator.java:66-71: Create integration tests to check...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#352]
Puzzle `149-fa59b6ee` in `qulice-findbugs/src/main/java/com/qulice/findbugs/FindBugsValidator.java:66-71` has to be resolved: Create integration tests to check that FindBugsValidator can exclude classes from check. see http://findbugs.sourceforge.net/manual/filter.html for details of findbug filter patterns. Don't forget to update example-exclude.apt.vm with example for findbugs exclusion.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@alevohin this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@alevohin you're working with this issue for 13 days already. as a reminder, don't forget to remove the `@todo` puzzle from the source code. -30 to your rating, your total score is [+135](http://www.netbout.com/b/35105?open=rating)

**Comment by alevohin** [comment]
@davvd your comment looks strange because PR #352  for this issue created 12 days ago. And you were looking for reviewer for 12 days.

**Comment by yegor256** [comment]
@davvd we need more time here, obviously

**Comment by davvd** [comment]
> @davvd we need more time here, obviously

@yegor256 of course, thanks for letting me know, take your time

**Comment by alevohin** [comment]
@davvd PR #357 was merged. Please check and close issue.

**Comment by alevohin** [comment]
@davvd PR #357 was merged. Please check and close issue.

**Comment by davvd** [comment]
once `352-f6cf61e2` puzzle is resolved, this ticket will be complete

**Comment by alevohin** [comment]
@davvd could you explain what does it mean?
> once 352-f6cf61e2 puzzle is resolved, this ticket will be complete

**Comment by yegor256** [comment]
@alevohin this means that the problem will be fully (!) fixed when this puzzle is resolved. Your job is done here already. This information is for us to track the big scope of the project.

**Comment by davvd** [comment]
Closing this issue now...

**Comment by davvd** [comment]
@alevohin Thanks a lot, I just topped your account for **30 mins**, transaction ID `50519039`; +30 to your rating, your total score is [+195](http://www.netbout.com/b/35105?open=rating)

**Comment by davvd** [comment]
@krzyk the last puzzle `352-f6cf61e2`/#421 originated from here solved
