### ISSUE TITLE
XmlValidatorTest.java:91-95: XmlValidator should be able to...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#354]
Puzzle `246-77de21a5` in `qulice-xml/src/test/java/com/qulice/xml/XmlValidatorTest.java:91-95` has to be resolved: XmlValidator should be able to log IO problems (for example, inability to connect to a server) and ignore them (see ticket #243).\ However, {@link com.jcabi.xml.StrictXML} class outright throws an IllegalArgumentException in such cases. Let's find a way to detect whether a failure was caused by such IO errorsand fix this test.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@alexdag This task is yours, please go ahead keeping in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If any questions, don't hesitate to ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@alexdag you're holding this ticket for 18 days already. If it's not finished (and closed) in the next 40 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle ([this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck); do not forget to remove the TODO puzzle from the source code; added -30 to your rating, now it is equal to [-270](http://www.netbout.com/b/35099?open=rating)

**Comment by davvd** [comment]
@alexdag this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 added to your rating, at the moment it is: [-540](http://www.netbout.com/b/35099?open=rating)

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by davvd** [comment]
@krzyk Closing, thanks all
