### ISSUE TITLE
MethodBodyCommentsCheck.java:52-53: Add handling of anonymous classes...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#355]
Puzzle `260-1576b183` in `qulice-checkstyle/src/main/java/com/qulice/checkstyle/MethodBodyCommentsCheck.java:52-53` has to be resolved: Add handling of anonymous classes outside of variable definitions, e.g. in for, try/catch, expression, etc.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@maxim-kornienko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by maxim-kornienko** [comment]
@davvd Could you please provide a couple of code sniplets, that should fail?
Should `/* comment */` be treated the same way as `// commnent`?

**Comment by yegor256** [comment]
@maxim-kornienko yes, all of them should fail. any comment inside method body should raise a violation

**Comment by maxim-kornienko** [comment]
@yegor256 thanks, but what about example of code that should fail, but doesn't now?

**Comment by yegor256** [comment]
@maxim-kornienko to be honest, I can't reproduce the problem. All options I'm trying are checked correctly. Maybe this puzzle is just old and should be removed.

**Comment by maxim-kornienko** [comment]
@yegor256 me too :) Let's abort it then.

**Comment by yegor256** [comment]
@maxim-kornienko just create a pull request where this puzzle is removed and the task will be done/closed/paid.

**Comment by maxim-kornienko** [comment]
@yegor256 done. Pull request teamed/qulice/pull/372

**Comment by davvd** [comment]
We're done here, thanks all

**Comment by davvd** [comment]
@maxim-kornienko Thanks a lot, I just topped your account for **30 mins**, transaction ID `50519049`; +30 added to your rating, at the moment it is: +105
