### ISSUE TITLE
MethodBodyCommentsCheck.java:50-51: Add handling of multiple anonymous...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#356]
Puzzle `260-dc51e6f4` in `qulice-checkstyle/src/main/java/com/qulice/checkstyle/MethodBodyCommentsCheck.java:50-51` has to be resolved: Add handling of multiple anonymous classes inside methods by looking at the recursive tree.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@flexelem this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@flexelem check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 17 days. If you can't close it within the next 48 hours I'll have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. do not forget that you should remove the `@todo` puzzle from the source code. -30 added to your rating, at the moment it is: -395

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by davvd** [comment]
@krzyk Done, the task is closed
