### ISSUE TITLE
Travis CI build failed for openjdk6

### ISSUE THREAD

**Issue by alevohin** [teamed/qulice#358]
Travis CI build failed for openjdk6. Reason - "The current version of FindBugs is 3.0.0. FindBugs requires JRE (or JDK) 1.7.0 or later to run." (http://findbugs.sourceforge.net/). Module "qulice-findbugs" depends on com.google.code.findbugs:findbugs:3.0.0.
Need to remove Travis CI build for openjdk6.

**Comment by davvd** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@alevohin thanks a lot for reporting, **15 mins** added to your acc, pmt ID `49953441`

**Comment by alevohin** [comment]
@davvd It's duplicated of https://github.com/teamed/qulice/issues/359, that is closed. I'll check my PRs and close it if everithing ok.
