### ISSUE TITLE
Travis shouldn't use jdk 1.6

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#359]
According to https://github.com/teamed/qulice/issues/209#issuecomment-50982178 qulice is compatible with JDK >= 1.7, but Travis builds are still done using 1.6.

**Comment by yegor256** [comment]
@davvd  I'll fix this, assign me

**Comment by davvd** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by yegor256** [comment]
@krzyk should be fine now, please check

**Comment by krzyk** [comment]
Yes, it works correctly now

**Comment by davvd** [comment]
@yegor256 Thanks a lot, I just topped your account for **30 mins**, transaction ID `000-d3b21ae7`

+30 to your rating, your total score is [+4776](http://www.netbout.com/b/35008?open=rating)
