### ISSUE TITLE
FindBugsValidator must create "...findbug_excludes_...xml" in temp directory

### ISSUE THREAD

**Issue by alevohin** [teamed/qulice#362]
FindBugsValidator must create temporary files like "...findbug_excludes_...xml" in temp directory. Now it creates this files in base project directory.

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@alevohin thanks for reporting! I topped your account for 15 mins, transaction 49975795

**Comment by krzyk** [comment]
@davvd this is duplicate

**Comment by davvd** [comment]
> @davvd this is duplicate

@krzyk OK, I put "invalid", "duplicate" labels here

**Comment by davvd** [comment]
@alevohin the ticket is "invalid", closing it

**Comment by alevohin** [comment]
@krzyk please provide link to duplicated issue

**Comment by krzyk** [comment]
@alevohin Here it is  #441, I know that you reported it earlier, but I didn't notice that earlier and added #441 as issue to be fixed in 0.14 release.

**Comment by krzyk** [comment]
@yegor256 could we remove `duplicate` and `invalid` tags and reopen this issue? I would replace #441 in 0.14 with this one, and mark #441 as duplicate.

**Comment by yegor256** [comment]
@krzyk it will mess things up.. let's not do this
