### ISSUE TITLE
pom.xml:134-136: Remove this declaration when parent...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#366]
Puzzle `308-45ddd042` in `pom.xml:134-136` has to be resolved: Remove this declaration when parent pom would depends on qulice-maven-plugin:0.12 -->

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by alevohin** [comment]
@davvd please check and close issue. PR #377 were merged.

**Comment by alevohin** [comment]
@davvd @yegor256 we need to check and close this issue. PR was merged.

**Comment by alevohin** [comment]
@davvd @yegor256 PR was merged and deployed. Let's close task, it's completed.

**Comment by davvd** [comment]
Thanks all, I'm closing

**Comment by davvd** [comment]
@alevohin done, I added **30 mins** in payment `50519072`

added +30 to your rating, now it is equal to [+225](http://www.netbout.com/b/35105?open=rating)
