### ISSUE TITLE
pom.xml:207-208: When new jcabi is released...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#370]
Puzzle `333-37771839` in `qulice-findbugs/pom.xml:207-208` has to be resolved: When new jcabi is released based on qulice > 0.11, remove the line below.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by davvd** [comment]
@pandreev please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment]
@pandreev check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I'll have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; do not forget to remove the TODO puzzle from the source code; -30 added to your rating, current score is: -270

**Comment by davvd** [comment]
@pandreev this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 to your rating, your total score is -390

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk pls

**Comment by krzyk** [comment]
@davvd please see PR #580

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk right, I removed "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @krzyk pls

@krzyk OK @krzyk please go ahead, this task is yours

**Comment by davvd** [comment]
> @davvd please see PR #580 

@krzyk thank you, I will check it

**Comment by davvd** [comment]
@krzyk the code made here contains a puzzle `370-69914ea1`/#590, which will be resolved soon

**Comment by davvd** [comment]
@krzyk I'm closing the issue...

**Comment by davvd** [comment]
@krzyk Much obliged! I have added **45 mins** to your account in payment "73942342", 25 hours and 50 mins spent... the bonus for fast delivery (m=1550)... added +45 to your rating, now it is equal to [+3010](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@krzyk the last puzzle `370-69914ea1`/#590 solved
