### ISSUE TITLE
MethodBodyCommentsCheck should detect multiline comments

### ISSUE THREAD

**Issue by maxim-kornienko** [teamed/qulice#371]
MethodBodyCommentsCheck detects simgle line comments like `// comment`, but ignores multiline syntax like `/* ignored comment*/`.

Try checking this code: 
```java
public void method(String format, String text) {
    int c = 0;
    /* comment */
    this.a = b;
}
```
Expected result: check produces violation
Actual result: no violation occurs

**Comment by davvd** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@maxim-kornienko thanks for tis bug, I topped your account for 15 mins, transaction `50045404`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by mkordas** [comment]
@krzyk please assign me

**Comment by mkordas** [comment]
@davvd please see PR #616

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd please see PR #616

@mkordas thank you, I will check it

**Comment by davvd** [comment]
> @davvd assign @mkordas please 

@krzyk OK @mkordas please start, the task is yours

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk thanks, I removed the "postponed" tag

**Comment by mkordas** [comment]
@maxim-kornienko it is done #616, can you close the issue?
