### ISSUE TITLE
IndentationCheck

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#373]
Let's create `IndentationCheck`, which goes line by line and check that every next line either: 1) has the same number of leading spaces as the previous line, or 2) has 4 spaces more, or 3) has 4 spaces less.

**Comment by davvd** [comment]
I'll ask someone to take care of this task soon

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-436a95bf`

**Comment by davvd** [comment]
@nathansgreen the task is yours plz proceed

**Comment by nathansgreen** [comment]
@davvd  please assign to someone else

**Comment by davvd** [comment]
> @davvd  please assign to someone else

@nathansgreen I will try to find someone else

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by krzyk** [comment]
@yegor256 I think this was done as part of #556

**Comment by yegor256** [comment]
@krzyk right, thanks
