### ISSUE TITLE
MandatoryThisCheck

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#374]
Let's create a new checkstyle `MandatoryThisCheck` that will ensure that all object properties and methods start with `this.`

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-ffb61d6a`

**Comment by davvd** [comment]
@nhekfqn this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by nhekfqn** [comment]
@yegor256 please provide more details - where and how this new checkstyle should be created.

**Comment by yegor256** [comment]
@nhekfqn similar to other checkstyle checks, like, for example this one: https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/main/java/com/qulice/checkstyle/CurlyBracketsStructureCheck.java

**Comment by nhekfqn** [comment]
@davvd Please find someone else to do the task.

**Comment by davvd** [comment]
> @davvd Please find someone else to do the task.

@nhekfqn I will try to find someone else

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I will try to assign someone else

**Comment by mkordas** [comment]
@yegor256 isn't [RequireThis](http://checkstyle.sourceforge.net/config_coding.html#RequireThis) enough here? I can add tests to confirm that RequireThis works as expected in Qulice.

**Comment by yegor256** [comment]
@mkordas yeah, `RequireThis` should be enough. I wonder why it doesn't work as expected...

**Comment by krzyk** [comment]
@yegor256 do you have examples where it fails?

**Comment by yegor256** [comment]
@krzyk I can't reproduce it. I think this issue is just expired. I'm closing.
