### ISSUE TITLE
In-method variable name check

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#376]
Let's check that all variables names inside methods match this regex: `[a-z]{3,12}`

**Comment by davvd** [comment]
we'll find someone to do this task, soon

**Comment by davvd** [comment]
@yegor256 many thanks for the report, I topped your account for 15 mins, transaction 000-7f764e8b

**Comment by davvd** [comment]
@nathansgreen please go ahead with this task,it's yours

**Comment by nathansgreen** [comment]
@davvd please assign to someone else

**Comment by davvd** [comment]
> @davvd please assign to someone else

@nathansgreen OK, I will try to assign someone else

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk someone else will help in this task, no problem at all

**Comment by mkordas** [comment]
@krzyk can you assign me to it?

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@mkordas I'm wondering if this is still valid

**Comment by krzyk** [comment]
@yegor256 Do you have examples where it is not working? I see that we have such rules currently:
```
        <module name="LocalFinalVariableName">
            <property name="format" value="^ex|[a-z]{3,}$"/>
        </module>
        <module name="LocalVariableName">
            <property name="format" value="^ex|[a-z]{3,}$"/>
        </module>
```
Is this issue about changing the max number of characters to 12 and removing `ex`?

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by yegor256** [comment]
@krzyk maybe I'm wrong in this issue... let's just change patterns to `^ex|[a-z]{3,12}$` and call it a day

**Comment by mkordas** [comment]
@krzyk please assign me here. Actually we have more work to be done around local variables naming. As from [Checkstyle 6.14](http://checkstyle.sourceforge.net/releasenotes.html#Release_6.14) there's new check `CatchParameterName` (I'm the author), and `LocalVariableName` do not check catch parameters anymore, so we have gap right now that needs to be fixed.

@yegor256 do you want the same pattern (`^ex|[a-z]{3,12}$`) to apply also for catch parameters?

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk done. @mkordas you are assigned to this task. please proceed...

**Comment by mkordas** [comment]
@davvd please see PR #376

**Comment by davvd** [comment]
> @davvd please see PR #376

@mkordas thanks, I'll take a look

**Comment by mkordas** [comment]
@yegor256 please close the issue, it was done in #591

**Comment by yegor256** [comment]
@mkordas thanks!

**Comment by davvd** [comment]
@mkordas paid, thanks, added **45 mins** to your account, payment `568f65d1f0da043bf00001e4`, 27 hours and 15 mins was spent... there is a bonus for fast delivery (m=1635)... +45 added to your rating, current score is: [+1534](http://www.netbout.com/b/36080?open=rating)
