### ISSUE TITLE
verify.groovy:36-39: This validation doesn't work at...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#388]
Puzzle `60-2649436b` in `qulice-maven-plugin/src/it/findbugs-violations/verify.groovy:36-39` has to be resolved: This validation doesn't work at the moment because of incorrect classpath generation in DefaultMavenEnvironment. There is some problem which leads to incomplete classpath being passed to com.qulice.findbugs.Wrap class.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by davvd** [comment]
@jenya this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by davvd** [comment]
@apocarteres please go ahead with this task, it's yours

**Comment by apocarteres** [comment]
@davvd please assign it to someone else

**Comment by davvd** [comment]
> @davvd please assign it to someone else

@apocarteres someone else will help in this task, no problem at all

**Comment by davvd** [comment]
@maurezen the task is yours plz proceed

**Comment by maurezen** [comment]
@davvd please assign this issue to someone else.

**Comment by davvd** [comment]
> @davvd please assign this issue to someone else.

@maurezen all right, we'll find someone else for this task

**Comment by davvd** [comment]
@adko-pl the task is yours please proceed

**Comment by adko-pl** [comment]
@davvd please find another developer

**Comment by yegor256** [comment]
@davvd pls assign someone else here

**Comment by davvd** [comment]
> @davvd pls assign someone else here

@yegor256 deducted 30 from your rating :(

**Comment by davvd** [comment]
> @davvd pls assign someone else here

@yegor256 OK, I will try to assign someone else

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by krzyk** [comment]
@davvd this is not posponed

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by krzyk** [comment]
@davvd please see PR #641

**Comment by davvd** [comment]
> @davvd assign @krzyk

@krzyk done. @krzyk you are assigned to this task. please proceed...

**Comment by davvd** [comment]
> @davvd please see PR #641 

@krzyk will check it soon, thanks

**Comment by davvd** [comment]
@krzyk I'm closing the issue...

**Comment by davvd** [comment]
@krzyk paid, thanks, added **1 hour** to your account, payment `75677091`, 3 hours and 13 mins was spent... there is a bonus for fast delivery (m=193)... +60 added to your rating, at the moment it is: [+4299](http://www.netbout.com/b/35035?open=rating)
