### ISSUE TITLE
StrictIndentationCheck

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#389]
FYI, we removed our own CascadeIndentationCheck in #265

Let's create a new class `StrictIndentationCheck` which will check that every next line is indented by either 1) the same number of spaces as the previous one, or 2) +4 spaces, or 3) -4X spaces, where X is any number.

**Comment by davvd** [comment]
I'll find a developer for the task soon...

**Comment by davvd** [comment]
@yegor256 thanks for this report, I added 15 mins to your account, in transaction `000-90980e0e`

**Comment by yegor256** [comment]
@davvd seems to be a duplicate of #373

**Comment by davvd** [comment]
> @davvd seems to be a duplicate of #373

@yegor256 OK
