### ISSUE TITLE
HiddenFieldCheck rule make the code look worse

### ISSUE THREAD

**Issue by ggajos** [teamed/qulice#390]
When I read arguments of methods like this I fell like internet connection is breaking up and some of data is lost.
```Java
Target(final String hst, final int prt) {
        this.host = hst;
        this.port = prt;
}
```
It is workaround for (HiddenFieldCheck) rule;
```Java
Target(final String host, final int port) {
        this.host = host;
        this.port = port;
}
```
Is there a way to make it beautiful again? We have to prepend this. prefix every time so it's very natural just to type `this.host = host`.

We can't prefix method arguments, for example with "inHost" because of: `Name 'inHost' must match pattern '^[a-z]{3,}$'. (ParameterNameCheck)`

Any other ideas?

**Comment by yegor256** [comment]
@ggajos this is coming from PMD, and it makes sense. `this.host = host` is rather confusing since it reads like "set host to host". These `hst` and `prt

**Comment by ggajos** [comment]
ok, thanks for explanation
