### ISSUE TITLE
Windows: lines in file should end with Unix-like end of line

### ISSUE THREAD

**Issue by maurezen** [teamed/qulice#391]
I'm checking out a fresh clone of some repository, say jcabi-dynamo, and running `mvn clean install -Pqulice`. 
Except [failing header checks](https://github.com/jcabi/jcabi/issues/297) there is one more issue - hundreds of 

>[ERROR] \src\test\java\com\jcabi\dynamo\AttributesTest.java[30]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)

The files in repo should be fine, so who is the culprit? Does git somehow change ends of lines? Or does the check itself use system-dependant EOL while it shouldn't in this case?

**Comment by yegor256** [comment]
It's an issue with `.gitattributes`, which doesn't specify that all files must have Unix end-of-lines. See https://help.github.com/articles/dealing-with-line-endings/

**Comment by maurezen** [comment]
Will take a look, thanks!
