### ISSUE TITLE
Checkstyle support in SuppressWarnings annotation

### ISSUE THREAD

**Issue by nhekfqn** [teamed/qulice#392]
Currently to suppress checkstyle checks ```@checkstyle``` comment is used. See for example https://github.com/jcabi/jcabi-dynamo/issues/8 It is totally not obvious as another checks, say PMD, are suppressed with ```@SuppressWarnings``` annotation.

Qulice need support to suppress checkstyle checks with ```@SuppressWarnings``` annotation as well.

**Comment by yegor256** [comment]
@nhekfqn good idea, but we won't do this. Mostly because Checkstyle checks are "text-based", while PMD is more "structs-based". They are different and mixing them together won't look good.
