### ISSUE TITLE
Qulice does not read schema document through the proxy

### ISSUE THREAD

**Issue by darkled** [teamed/qulice#393]
Checking a project locally under windows 7 behind the proxy with `mvn clean install -Pqulice` leads to the following errors:
```
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)
[WARNING] 17 XML validation error(s):
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: cvc-elt.1: Cannot find the declaration of element 'project'.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/DECORATION/1.3.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         name="justAnotherProject"
         xsi:schemaLocation="http://maven.apache.org/DECORATION/1.3.0 http://maven.apache.org/xsd/decoration-1.3.0.xsd">
    <skin>
        <groupId>com.jcabi</groupId>
        <artifactId>jcabi-maven-skin</artifactId>
        <version>1.5.1</version>
    </skin>
    <bannerLeft>
        <name>justAnotherProject.com</name>
        <src>http://www.justAnotherProject.com/logo.png</src>
        <href>http://www.justAnotherProject.com/</href>
        <width>115</width>
        <height>65</height>
    </bannerLeft>
    <body>
        <menu name="Overview">
            <item href="index.html" name="Introduction"/>
            <item href="https://github.com/teamed/justAnotherProject/releases" name="Release History"/>
        </menu>
        <menu ref="reports"/>
    </body>
</project>
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.727 s
[INFO] Finished at: 2015-01-24T21:22:47+04:00
[INFO] Final Memory: 54M/751M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.10:check (jcabi-check) on project justAnotherProject: Failure: java.lang.IllegalArgumentException: 17 error(s), see log above -> [Help 1]
```
It seems that `qulice` is not able for the moment to handle proxy settings in order to load schema documents.

**Comment by davvd** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@darkled thanks for the report, I topped your acc for 15 mins, payment ID `50666271`

**Comment by davvd** [comment]
@apocarteres the task is yours, please go ahead

**Comment by apocarteres** [comment]
@darkled i ran the same build under OS X with system-wide proxy installed (checking proxy logs during build) and build looks correct for me. Are you sure that proxy you use works properly?

**Comment by darkled** [comment]
@apocarteres yes, sure, under my windows 7 all maven artifacts were downloaded correctly.

**Comment by apocarteres** [comment]
@darkled ok please add mark that it's related to Windows exactly then

**Comment by apocarteres** [comment]
@darkled btw, how did u setup proxy on Windows to get mvn pickup settings?

**Comment by darkled** [comment]
@apocarteres they are set both in the control panel and in `~\.m2\settings.xml`

**Comment by apocarteres** [comment]
@darkled ok i see. thx

**Comment by apocarteres** [comment]
well, i setup two virtual machines win7 and ubuntu
ubuntu starts up with <code>tinyproxy</code>
on win7 put ~\.m2\setting.xml proper proxy config
on win7 kick off <code>mvn -e clean install -Pqulice</code>
on ubuntu <code>tail -f /var/log/tinyproxy.log</code>
logs running well and contain corresponding requests to repos

build is successful for me in this config. 
Could you tell more about proxy u use?
What proxy logs do contain exactly?
Is there requests for schema documents there?

**Comment by darkled** [comment]
@apocarteres my proxy in maven is configured as follows:
```xml
<settings>
	<proxies>
		<proxy>
			<id>aProxy</id>
			<active>true</active>
			<protocol>http</protocol>
			<host>proxy.xxx.xx</host>
			<port>xxxx</port>
			<username></username>
			<password></password>
			<nonProxyHosts>localhost,127.0.0.1</nonProxyHosts>
		</proxy>
	</proxies>
</settings>
```
Unfortunately, I have access neither to its' detailed information nor to logs.

**Comment by apocarteres** [comment]
@darkled can u fire up local proxy instance and double check it again? If you use external proxy there is no guarantee that proxy works properly / doesn't modify requests or content.

**Comment by darkled** [comment]
@apocarteres unfortunately it makes no sense, since I cannot access internet without this external proxy. Do you have any other ideas?

**Comment by apocarteres** [comment]
@darkled could you compare two files then?

1. download via your proxy <code>http://maven.apache.org/xsd/decoration-1.3.0.xsd</code>
2. download <code>http://decipher.ru/pub/decoration-1.3.0.xsd.tar.gz</code>
3. extract <code>decoration-1.3.0.xsd</code> from <code>decoration-1.3.0.xsd.tar.gz</code>

compare md5 sum of original and unpacked documents

**Comment by darkled** [comment]
@apocarteres here is the result, documents are the same.
```
MD5sums 1.2 freeware for Win9x/ME/NT/2000/XP+
Copyright (C) 2001-2005 Jem Berkes - http://www.pc-tools.net/
Type md5sums.exe -h for help

[Path] / filename                              MD5 sum
-------------------------------------------------------------------------------
[.......]
decoration-1.3.0.xsd                           dfb438fdfc2c1113366f7079c591f948
decoration-1.3.0.xsd.xml                       dfb438fdfc2c1113366f7079c591f948
```

**Comment by apocarteres** [comment]
@darkled i made the same experiment as before with <code>tinyproxy</code> but i used <code>squid</code> this time and build successful again. All proxy logs are fine. Have no idea what is wrong with your proxy then, but it seems there is no problem in <code>qulice</code> with using proxy under Win7 / Ubuntu and OS X. Btw i used https / socks to test with no auth. 

- Did u try to use socks one? 
- Do you have any chance to use other proxy?

The last thing that comes into my mind is to run tcpdump or any other sniffer to capture http requests and analyze traffic.

**Comment by apocarteres** [comment]
@darkled and another thing... you use <code><protocol>http</protocol></code> but in my case several resources were failed to fetch. try to use <code><protocol>https</protocol></code>

**Comment by apocarteres** [comment]
@darkled ok i got it :) you are right. it doesn't use proxy as it should. My previous tests were successful cause my virtual boxes have  proxy connection but direct connect as well. My build keep failed either, since i firewall my virtual boxes and prevented direct connections. So the problem is that <code>CheckMogo</code> object contains <code>environment</code> field which has incomplete configuration. I will be fixed it soon. Thanks for your time.

**Comment by apocarteres** [comment]
@darkled add proxy config to your MAVEN_OPTS variable such as:
<code>-Dhttp.proxyHost=<HOST> -Dhttp.proxyPort=<PORT></code>
should fix your problem

**Comment by darkled** [comment]
@apocarteres that's working, thanks. Just another question, `CheckMogo` is a class of `qulice`, isn't it? If yes, is it possible to fix it in order to read maven settings as well?

**Comment by apocarteres** [comment]
@darkled right, it's part of <code>qulice</code> but things go deeper there. The problem is that <code>CheckMogo</code> autowires <code>session</code> such that
<pre>
    @Component
    private transient MavenSession session;
</pre>
that is Maven injects configured session there under hood. We can hack the <code>session</code> in runtime and forcibly pass it to underlying validators, but it will be quite ugly solution. 

On the other hand configured session proceeds to particular <code>XmlValidator</code> and then to the <code>StrictXML</code>. Within <code>StrictXML</code> validation happens through <code>javax.xml.validation.Schema</code> which is not part of <code>qulice</code> and it doesn't take the session into account. But as i mentioned above it perfectly works with standard Java Proxy JVM flags. 

Actually i'm not sure that such big fix would be better than using standard Java mechanism

**Comment by darkled** [comment]
@apocarteres agreed, thanks! Closing the issue.

**Comment by davvd** [comment]
@apocarteres Thank you, I've added **30 mins** to your account in payment/transaction "`51288374`"... +30 to your rating, your total score is [+195](http://www.netbout.com/b/35111?open=rating)
