### ISSUE TITLE
JSR-303 validator error

### ISSUE THREAD

**Issue by maurezen** [teamed/qulice#395]
While running `mvn clean install -Pqulice` on qulice/qulice-maven-plugin I get the following error in the log
>`[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration
, because no Bean Validation provider could be found. Add a provider like Hibern
ate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html
)`

The build is still successful. What does this error affect? What should be done to get rid of it?

**Comment by yegor256** [comment]
it's just a warning, ignore it. more details here #330
