### ISSUE TITLE
Incomplete documentation: using of proxies

### ISSUE THREAD

**Issue by darkled** [teamed/qulice#396]
According to #393 qulice is not able to validate xml schemas using proxies which are set up in maven's `settings.xml`. Therefore I would suggest to put this information somewhere in either `README.md` or FAQ or both.

Proxy configuration should be in `MAVEN_OPTS` variable such as:
```
-Dhttp.proxyHost=HOST -Dhttp.proxyPort=PORT
```

**Comment by davvd** [comment]
I'll find a developer for the task soon...

**Comment by davvd** [comment]
@yegor256 this task is yours, go ahead

**Comment by davvd** [comment]
@darkled many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `50957379`

**Comment by yegor256** [comment]
@davvd give this to somebody else

**Comment by davvd** [comment]
> @davvd give this to somebody else

@yegor256 OK, I will try to assign someone else

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd not postponed

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk yep, done. @mkordas it is your task now

**Comment by mkordas** [comment]
@davvd please see PR #613

**Comment by davvd** [comment]
> @davvd please see PR #613

@mkordas I will take a look, thanks

**Comment by mkordas** [comment]
@darkled it's finally done in #613, can you close the issue?

**Comment by darkled** [comment]
@mkordas sure, thanks!

**Comment by davvd** [comment]
@mkordas Much obliged! I have added **1 hour** to your account in payment "569ca96ca01b690114000078", 23 hours and 35 mins spent... the bonus for fast delivery (m=1415)... +60 to your rating, your total score is [+2694](http://www.netbout.com/b/36080?open=rating)
