### ISSUE TITLE
DependenciesValidator should support excludes

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#398]
DependenciesValidator should support excludes. For now it can just be totally disabled with
```
<exclude>dependencies:</exclude>
```
It would be really useful to have a possibility to exclude particular artifacts, kind of this way
```
<exclude>dependencies:org.slf4j:slf4j-log4j12, org.aspectj:aspectjrt</exclude>
```

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
@longtimeago many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `51288445`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by longtimeago** [comment]
@krzyk could we unpostpone the issue?

**Comment by krzyk** [comment]
@longtimeago yes, as soon as I find a volunteer :), or find time to do it myself

**Comment by longtimeago** [comment]
@krzyk wow, I didn't know that it's a problem to find a developer

**Comment by krzyk** [comment]
@Happy-Neko want to try this one?

**Comment by Happy-Neko** [comment]
@krzyk yes.

**Comment by krzyk** [comment]
@Happy-Neko sorry I already started to work on this one

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by krzyk** [comment]
@longtimeago please see PR #652

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd assign @krzyk

@krzyk done. @krzyk the task is yours, please go ahead

**Comment by krzyk** [comment]
@longtimeago changes have been merged to master, and it will be released in 0.15.5 (https://github.com/teamed/qulice/issues/604#issuecomment-176195222) in about an hour. Please close this issue.

**Comment by krzyk** [comment]
@longtimeago there is a slight change from what you requested, right now the syntax is:
```
<exclude>dependencies:org.slf4j:slf4j-log4j12</exclude>
<exclude>dependencies:org.aspectj:aspectjrt</exclude>
```

and to exclude everything you do:
```
<exclude>dependencies:.*</exclude>
```

**Comment by longtimeago** [comment]
@krzyk no problem, thanks!

**Comment by longtimeago** [comment]
@krzyk it would be nice to update this doc as well http://www.qulice.com/qulice-maven-plugin/example-exclude.html

**Comment by krzyk** [comment]
@longtimeago it is updated :)
> Dependencies exclude uses syntax of groupId:artifactId, so to exclude e.g. guava library you should add dependencies:com.google.guava:guava as an exclude. Multiple exclude tags can be provided to exclude multiple dependencies. To exclude all dependency checks dependencies:.* should be used.

**Comment by krzyk** [comment]
@longtimeago if that's OK, please close this issue

**Comment by longtimeago** [comment]
@krzyk Perfect, thanks!

**Comment by davvd** [comment]
@krzyk Thanks for your contribution, **45 mins** was added to your account, payment ID is `75988226`, 24 hours and 54 mins spent total

there is a bonus for fast delivery (m=1494)

+45 added to your rating, current score is: [+4886](http://www.netbout.com/b/35035?open=rating)
