### ISSUE TITLE
HeaderCheck for long LICENSE.txt (e.g. GPL)

### ISSUE THREAD

**Issue by Tilo2048** [teamed/qulice#399]
Dear all,

I just startet using Qulice and ... well I'm learning. ;)

I choosed the GPL license for a personal project via http://choosealicense.com/licenses/gpl-3.0/ and put the whole GPL clauses into my LICENSE.txt file.

Now I don't want to include the whole LICENSE.txt into my java files but only the short version like described at the end of the license:

    {one line to give the program's name and a brief idea of what it does.}
    Copyright (C) {year}  {name of author}
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

Now the Qulice HeaderCheck is complaining that the header appears to be missing as the files have not anough lines.

Any suggestions?

Thank you and kind regards

**Comment by yegor256** [comment]
@Tilo2048 you should have a full license, in every file. There is no workaround :)

**Comment by Tilo2048** [comment]
"there is no workaround":
* in the sense that every file should contain the full license even if it is 100s of lines long or there is a common short version

 OR

* Qulice just doesn't support this?

**Comment by yegor256** [comment]
@Tilo2048 yes, every file should contain the full license, no matter how long it is. imagine a situation when your file is taken away from your project by someone and sent to someone else without mentioning where it came from. The guy uses it, violating the license, because he doesn't know that the license every exists. Make sense?

**Comment by Tilo2048** [comment]
Makes sense but sounds unpractical. Thanks for your feedback.

Then I will proceed learning through pain.

**Comment by yegor256** [comment]
check this article, it should help you to handle the pain: http://www.yegor256.com/2014/08/13/strict-code-quality-control.html

**Comment by Tilo2048** [comment]
... this is where I came from.
