### ISSUE TITLE
How can I disable the check for package Javadoc?

### ISSUE THREAD

**Issue by dpisarenko** [teamed/qulice#401]
Is it possible to disable the Checkstyle rule, which checks that there is package Javadoc (as far as I remember, it's called `JavadocPackage`) ?

If yes - how?

**Comment by yegor256** [comment]
I don't think it's possible. All Checkstyle suppression comments are to be added to `.java` files. But if there is no `package-info.java`, there is no place to add them.

**Comment by vorburger** [comment]
I believe you could possibly [do something like this here](https://android.googlesource.com/platform/external/checkstyle/+/HEAD/config/suppressions.xml#29).
