### ISSUE TITLE
Checkstyle bug: version upgrade

### ISSUE THREAD

**Issue by pinaf** [teamed/qulice#408]
Checkstyle has a bug where WalkTree check fails with NullPointerException.
It is triggered if you have a field such as this in your class (note the lack of `new float[]`)
```
private final float[] FOREGROUND_FRACTIONS =
-    {
-        0.0f,
-        0.03f,
-        0.94f,
-        1.0f
-    };
```

this link suggests it was fixed https://github.com/checkstyle/checkstyle/issues/353
if so, let's upgrade checkstyle.

**Comment by davvd** [comment]
I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@pinaf thanks for this report, I added 15 mins to your account, in transaction `AP-1YP950605X661021J`

**Comment by longtimeago** [comment]
@davvd please, give it to me

**Comment by longtimeago** [comment]
@yegor256 may I?

**Comment by longtimeago** [comment]
@yegor256 It's our bug, not a checkstyle one.
I've reproduced and localized it. ``` ConstantUsageCheck ``` is guilty.

**Comment by longtimeago** [comment]
@yegor256 anyway, here is the fix https://github.com/teamed/qulice/pull/440

**Comment by davvd** [comment]
@longtimeago it's yours, please help, budget is 30 mins

**Comment by longtimeago** [comment]
@pinaf please check #440 and close the issue if it's ok :)

**Comment by davvd** [comment]
@longtimeago Thanks for your contribution, **1 hour** was added to your account, payment ID is `60369651`, 23 hours and 51 mins spent total

there is a bonus for fast delivery (m=1431)

+60 added to your rating, current score is: [+3371](http://www.netbout.com/b/35024?open=rating)
