### ISSUE TITLE
lineLength configuration in pom.xml doesn't seem to be applied

### ISSUE THREAD

**Issue by drissamri** [teamed/qulice#409]
Currently giving Qulice a go, but seem to stumble upon on a configuration issue. 
I've set the lineLength property in my pom.xml and ran mvn qulice:check but it is not taking this property into account.
``` 
<plugin>
   <groupId>com.qulice</groupId>
   <artifactId>qulice-maven-plugin</artifactId>
   <version>0.12.1</version>
   <configuration>
      <license>file:${basedir}/LICENSE.txt</license>
      <lineLength>100</lineLength>
    </configuration>
    <executions>
       <execution>
           <goals>
             <goal>check</goal>
           </goals>
       </execution>
    </executions>
 </plugin>
```
```
Line is longer than 80 characters (found 91). (LineLengthCheck)
```

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by GilraenBurland** [comment]
+1 for this.

**Comment by yegor256** [comment]
@drissamri it's not designed this way. It's not supposed to be configurable. If you want that level of configuration, use Checkstyle directly. Qulice is shipped together with our understanding of what "quality" is :)
