### ISSUE TITLE
JavadocTagsCheck false positive for valid email

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#412]
Here is the javadoc
```
/**
 * Tests for {@link com.sigzig.ui.ToggleLogButton}.
 *
 * @author Gerrit (han.solo@xmpp.mobilezoo.org)
 * @version $Id$
 */
```
It produces following error:
```
Tag text 'Gerrit (han.solo@xmpp.mobilezoo.org)' does not match the pattern 
'^([A-Z](\.|[a-z]+) ){2,}\([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\)$' (JavadocTagsCheck)
```
Which is definitely wrong.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@longtimeago many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `61136399`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk here

**Comment by krzyk** [comment]
@longtimeago the above fails because we expect at a person to have at least first and last name. It will work if you give Gerrit a second name.
E.g. the following passes check: 
```
/**
 * Tests for {@link com.sigzig.ui.ToggleLogButton}.
 *
 * @author John Gerrit (han.solo@xmpp.mobilezoo.org)
 * @version $Id$
 */
```

Should we expect to have people with only single name (first or last)?

**Comment by longtimeago** [comment]
@krzyk I think it's too stict to expect both

**Comment by longtimeago** [comment]
@krzyk one may want to put a nick instead of real name

**Comment by krzyk** [comment]
@davvd please see PR #496

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd assign @krzyk here

@krzyk OK @krzyk please go ahead, this task is yours

**Comment by davvd** [comment]
> @davvd please see PR #496 

@krzyk thank you, I will check it

**Comment by krzyk** [comment]
@longtimeago code has been updated in master, please close this issue

**Comment by longtimeago** [comment]
@krzyk thank you!

**Comment by davvd** [comment]
@krzyk Much obliged! I have added **30 mins** to your account in payment "70771021", 237 hours and 37 mins spent

+30 added to your rating, at the moment it is: [+2853](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@longtimeago once `412-bd044e76`/#505 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1125](https://github.com/yegor256/qulice/issues/1125) is still not solved.
