### ISSUE TITLE
Message "Wrong order for 'com.google.common.base.Joiner' import. (ImportOrderCheck)" not informative

### ISSUE THREAD

**Issue by d-molotchko** [teamed/qulice#413]
While applying coding style to test unit I get message "Wrong order for 'com.google.common.base.Joiner' import. (ImportOrderCheck)". 
I can move import to other place (at first line, for example) but it is not right. 
I need to know suggested place to move to.
There are no documentation about 'ImportOrderCheck' on site.

**Comment by Suseika** [comment]
This may be helpful:

http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/ImportOrderCheck.html

Basically:

> java. comes first, javax. comes second, then everything else

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by Suseika** [comment]
First should go `java` imports, then `javax`, then everything else. That's the strategy quilce is using. But really that should be made explicit in the documentation or error messages.

**Comment by yegor256** [comment]
@d-molotchko we can't fix it, this message is coming from Checkstyle
