### ISSUE TITLE
NPE Idea 14.1 bundled Maven 3.0.5

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#417]
build [Takes](https://github.com/yegor256/takes) by Idea 14.1 bundled Maven 3.0.5 causes NPE 

>[INFO] --- qulice-maven-plugin:0.12:check (jcabi-check) @ takes ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.981s
[INFO] Finished at: Sun Mar 29 13:03:58 YEKT 2015
[INFO] Final Memory: 28M/352M
[INFO] ------------------------------------------------------------------------
[ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at

**Comment by yegor256** [comment]
@dmzaytsev please explain again how I can reproduce this bug?

**Comment by dmzaytsev** [comment]
@yegor256 sure

Steps to reproduce this bug:
1. Install [IntelliJ IDEA 14.1](https://www.jetbrains.com/idea/download/) Community Edition(I got NPE  on  Windows 7 64 bit and Windows 8.1 64bit, but I think this is true for all platforms)
2. Open Settings windows (File/Setting)
3. Open tab "Build, Execution, Deployment/Build Tools/Maven"
4. Set  Maven home directory to "Bundled(Maven 3)"
5. Choose VCS/Checkout from version control/GitHub
6. Set Git Repo URL to "https://github.com/yegor256/takes.git", clone it
7. Open Maven Projects panel (View/Tool Windows/Maven Projects)
8. Check Profiles/qulice
9. Click takes/Lifecycle/install
10 Build project will start
11. In Run window you will see NPE stack trace

**Comment by yegor256** [comment]
@dmzaytsev upgrade your Maven to 3.2 and the problem will go away

**Comment by dmzaytsev** [comment]
@yegor256 thanks!
