### ISSUE TITLE
quality.html has broken link 

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#419]
the page http://www.qulice.com/quality.html has broken link [CascadeIndentation]
(http://www.qulice.com/qulice-checkstyle/apidocs-0.12.1/com/qulice/checkstyle/CascadeIndentationCheck.html)

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@dmzaytsev fixed, thanks
