### ISSUE TITLE
pom.xml:51-53: Need to add multiline check...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#421]
Puzzle `352-f6cf61e2` in `qulice-maven-plugin/src/it/findbugs-exclude/pom.xml:51-53` has to be resolved: Need to add multiline check after issue #350 resolved. Now only one class can be excluded Don't forget update example-exclude.apt.vm... The puzzle was created by alevohin on 16-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by mkordas** [comment]
@krzyk please assign me to this task

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk done. @mkordas the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by mkordas** [comment]
@davvd please see PR #586

**Comment by davvd** [comment]
> @davvd please see PR #586

@mkordas will check it soon, thanks

**Comment by mkordas** [comment]
@davvd puzzle is done in #586, please close the issue

**Comment by davvd** [comment]
> @davvd puzzle is done in #586, please close the issue

@mkordas thanks

**Comment by davvd** [comment]
@krzyk Done, the task is closed

**Comment by davvd** [comment]
@mkordas Thank you, I have added **45 mins** to your account in payment/transaction "`568cea1da9f715301900002b`", time consumed: 25 hours and 49 mins... the bonus for fast delivery (m=1549)... +45 added to your rating, current score is: [+1345](http://www.netbout.com/b/36080?open=rating)
