### ISSUE TITLE
QulicePlugin.java:47-47: Design validator classes for Gradle.......

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#422]
Puzzle `339-6f043704` in `qulice-gradle-plugin/src/main/java/com/qulice/gradle/QulicePlugin.java:47-47` has to be resolved: Design validator classes for Gradle.... The puzzle was created by Dmitri Pisarenko on 17-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by davvd** [comment]
@krzyk The issue is closed
