### ISSUE TITLE
pom.xml:66-72: This version of jcabi-xml retries...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#423]
Puzzle `280-4ce4d8c5` in `qulice-xml/pom.xml:66-72` has to be resolved: This version of jcabi-xml retries if the connection to the host of the schema document is reset. However I don't know how to trigger the "connection reset" condition for testing. We should find a way to test whether it does retry if this happens. See issues https://github.com/jcabi/jcabi-xml/issues/32 and https://github.com/teamed/qulice/issues/280 for background details.... The puzzle was created by Carlos Miranda on 12-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@davvd assign @aschworer please

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd assign @aschworer please

@krzyk yep, done. @aschworer it is your task now

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by aschworer** [comment]
@davvd is it ok to take it if the other 2 tasks I have are still not closed? What's up with the concurrent tasks rules?

**Comment by krzyk** [comment]
@aschworer concurrent tasks limit is applicable for automatic assignment only, but you can get more tasks if architect of a project assigns them to you. Architects don't know how many tasks you have currently assigned.

More over you can look at current issues in any project and ask architect of given project to assign it to you. (look at `TEAM.md` file in the project to know who is who in the project).

If you don't think you can do this task in 7 days I can reassign this.

**Comment by aschworer** [comment]
@krzyk Thank you for the explanation. It is clear. To be honest I don't know if I can. Until unless I close at least one task in teamed, I don't know what to expect and what it takes. So I would prefer not to commit for one more right now. I could take it a bit later if it's still available. Thank you.

**Comment by krzyk** [comment]
@aschworer OK, let me know when you'll be available

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@krzyk Thanks all, closed
