### ISSUE TITLE
<exclude> parameter in pom.xml for jslint doesn't work for specified files

### ISSUE THREAD

**Issue by wholegroup** [teamed/qulice#424]
It doesn't work. All js files are being checked.
``` xml
<plugin>
    <groupId>com.qulice</groupId>
    <artifactId>qulice-maven-plugin</artifactId>
    <configuration>
        <excludes>
            <exclude>jslint:.*js</exclude>
        </excludes>
    </configuration>
</plugin>
```

**Comment by davvd** [comment]
@wholegroup this task will get someone's attention soon

**Comment by davvd** [comment]
@wholegroup many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `55164606`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk here

**Comment by krzyk** [comment]
@davvd please see PR #500

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @krzyk here

@krzyk yep, done. @krzyk it is your task now

**Comment by davvd** [comment]
> @davvd please see PR #500 

@krzyk will take a look, thanks

**Comment by krzyk** [comment]
@wholegroup I've updated the code on master, you can checkout documentation here: https://github.com/teamed/qulice/blob/cdffba0d9373918a8e737aaa10604fd3bcc10a2d/qulice-maven-plugin/src/site/apt/example-exclude.apt.vm#L75-L78

If it is OK for you, please close this issue, thanks.

**Comment by krzyk** [comment]
@wholegroup your example above would become:
```
<plugin>
    <groupId>com.qulice</groupId>
    <artifactId>qulice-maven-plugin</artifactId>
    <configuration>
        <excludes>
            <exclude>jslint:**/*.js</exclude>
        </excludes>
    </configuration>
</plugin>
```

**Comment by krzyk** [comment]
@wholegroup ping

**Comment by wholegroup** [comment]
@krzyk sorry, I can test it only in 3 days.

@wholegroup <https://github.com/wholegroup> ping

—
Reply to this email directly or view it on GitHub
<https://github.com/teamed/qulice/issues/424#issuecomment-159533444>.

**Comment by krzyk** [comment]
@wholegroup have you had a chance to look at it?

**Comment by davvd** [comment]
@krzyk Thanks for your contribution, **30 mins** was added to your account, payment ID is `71223753`, 214 hours and 5 mins spent total

+30 added to your rating, current score is: [+2895](http://www.netbout.com/b/35035?open=rating)
