### ISSUE TITLE
AntEnvironmentTest.java:40-40: Implement unit tests at AntEnvironmentTest......

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#426]
Puzzle `337-3d7cb361` in `qulice-ant/src/test/java/com/qulice/ant/AntEnvironmentTest.java:40-40` has to be resolved: Implement unit tests at AntEnvironmentTest... The puzzle was created by alevohin on 19-Jan-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk "postponed" label already at this ticket

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I will try to assign someone else

**Comment by davvd** [comment]
@krzyk The issue should be closed..
