### ISSUE TITLE
overriden ParameterNameCheck

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#430]
It seems Qulice silently overrides ParameterNameCheck something like this `^[a-z]{3,}$`
Maybe I missed it in the [doc](http://www.qulice.com/quality.html) ?

Is it possible to use default value  `^[a-z][a-zA-Z0-9]*$` for [ParameterNameCheck] (http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/naming/ParameterNameCheck.html) ?
If yes so what needs to be changed  in the the pom.xml ?

**Comment by cvrebert** [comment]
I think it does that to enforce the same (IMHO bad) naming convention that it uses for local variables.

**Comment by cvrebert** [comment]
X-Ref: #376

**Comment by dmzaytsev** [comment]
@cvrebert Yes, I understand why it was done.
I just wanted to say if Qulice designed not only for internal use then plugin configuration should be allow to change custom restrictions.

@yegor256 What do you think about it ?

I would use Qulice in another project, which has other requirements the naming convention. Qulice good product I like it. I think more flexibility will  make it even better.

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@dmzaytsev it's a good product because it doesn't have the flexibility :) If you need a flexibility, use Checkstyle directly. Qulice is supposed to be strict and non-configurable. Basically, you either follow the rules or don't use it. That's the business idea here.
