### ISSUE TITLE
qulice fails with the exception "A required class was missing"

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#431]
Travis's build fails on the qulice check. This happens with any [Takes](https://github.com/yegor256/takes) build.
See log [here](https://travis-ci.org/yegor256/takes/jobs/60197872) line 3672
It's occurs on java 8 build only. 

>[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.12:check (jcabi-check) on project takes: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.12:check failed: A required class was missing while executing com.qulice:qulice-maven-plugin:0.12:check: org/codehaus/plexus/util/DirectoryScanner

**Comment by dmzaytsev** [comment]
@yegor256 @davvd 
is this ticket classified as a bug? if so dispatch it please

**Comment by davvd** [comment]
@dmzaytsev I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@dmzaytsev thanks for reporting! I topped your account for 15 mins, transaction 57277112

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign me

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk thanks, I removed the "postponed" tag

**Comment by davvd** [comment]
> @davvd assign me

@krzyk done, the task is yours, go ahead

**Comment by krzyk** [comment]
@dmzaytsev I tested qulice 0.16 on jdk 1.8 and I don't see this problem

**Comment by dmzaytsev** [comment]
@krzyk thanks! 
it was obsolete version 0.12

**Comment by davvd** [comment]
@krzyk I added **30 mins** to your account, many thanks for working with the project (79773288)! The completion time here was 72 hours and 21 mins.... +30 to your rating, your total score is [+6186](http://www.netbout.com/b/35035?open=rating)
