### ISSUE TITLE
RedundantModifierCheck don't play well with Java 8 default methods

### ISSUE THREAD

**Issue by caarlos0** [teamed/qulice#432]
If I define an interface like this:

```java
public interface Data {
    List<Blah> data();

    default void forEach(final Consumer<Blah> action) {
        for (final Blah blah : this.data()) {
            action.accept(blah);
        }
    }
}
```

Qulice will complain, saying that I have the redundant modifier `final` in `final Blah blah : this.data()`. If I remove the modifier, qulice complains that I need to put the `final` modifier.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by caarlos0** [comment]
@davvd @yegor256 ping

**Comment by davvd** [comment]
@krzyk this task is yours, go ahead

**Comment by davvd** [comment]
@caarlos0 thanks for the ticket, your account was topped for 15 mins, payment AP-4C929071VV336604D

**Comment by krzyk** [comment]
@davvd please see PR #459

**Comment by davvd** [comment]
> @davvd please see PR #459 

@krzyk thank you, I will check it

**Comment by krzyk** [comment]
@davvd we are waiting for #460

**Comment by krzyk** [comment]
@caarlos0 I have added test that confirms default methods work correctly with current qulice version.  Please close this issue.

**Comment by caarlos0** [comment]
@krzyk thanks!

**Comment by davvd** [comment]
> @davvd we are waiting for #460 

@krzyk issue #460 is closed already

**Comment by davvd** [comment]
@krzyk **30 mins** added to your account (payment number `65253670`), many thanks for your contribution! 119 hours and 25 mins spent here.; +30 added to your rating, at the moment it is: [+3852](http://www.netbout.com/b/35035?open=rating)
