### ISSUE TITLE
NPE when using qulice during a build with Maven < 3.2

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#439]
This has already been reported, but was not considered a bug that is worth fixing: #417 

I insist that this is a bug because it doesn't clearly explain in the log what is the source of the problem.

Qulice should print out something like: "You're using old version of maven, upgrade to 3.2+". 3.0 is a current default in IntelliJ IDEA and it can cause problems to qulice users.

**Comment by Suseika** [comment]
I would be glad to pick this issue up as soon as there is an opening on my Netbout agenda.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by davvd** [comment]
@suseika thanks for the report, I topped your acc for 15 mins, payment ID `AP-1BY70459EN853623H`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by mkordas** [comment]
@krzyk shouldn't we mark this as invalid?

**Comment by krzyk** [comment]
@Suseika please close this issue, it was solved by a PR in issue #514
