### ISSUE TITLE
FindBugsValidator pollute baseDir with findbug_excludes files

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#441]
FindBugsValidator generates findbug_excludes files on the fly but put them into wrong folder - maven module baseDir.
It's really easy to fix. In ``` FindBugsValidator.excludes() ``` change 
``` env.basedir().getPath() ``` 
to
``` env.tempdir().getPath() ```

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@longtimeago thank you for reporting this, I added 15 mins to your acc, transaction `60369677`

**Comment by krzyk** [comment]
@davvd it is urgent

**Comment by davvd** [comment]
> @davvd it is urgent

@krzyk OK, I put "urgent" label here

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I removed "urgent" tags

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk someone else will help in this task, no problem at all

**Comment by krzyk** [comment]
@davvd not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk to this task pls

**Comment by krzyk** [comment]
@davvd please see PR #492

**Comment by davvd** [comment]
> @davvd not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @krzyk to this task pls

@krzyk OK @krzyk please proceed, this task is yours

**Comment by davvd** [comment]
> @davvd please see PR #492 

@krzyk thanks, will take a look

**Comment by krzyk** [comment]
@longtimeago fix has been merged to master, please close this issue

**Comment by longtimeago** [comment]
@krzyk thank you very much!

**Comment by davvd** [comment]
@krzyk paid, thanks, added **1 hour** to your account, payment `70047800`, 3 hours and 8 mins was spent; there is a bonus for fast delivery (m=188); +60 to your rating, your total score is [+2618](http://www.netbout.com/b/35035?open=rating)
