### ISSUE TITLE
Upgrade to latest check style version to support Java 8 syntax features

### ISSUE THREAD

**Issue by GilraenBurland** [teamed/qulice#442]
The current checkstyl version 5.9 is not recognizing method references like this:

`this::doSomething`

Please use the latest version to fix this problem.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by davvd** [comment]
@krzyk it's yours, budget is 30 mins, please go ahead

**Comment by krzyk** [comment]
@GilraenBurland which version of qulice have you tried using? I just tested master and it correctly parses method references (and lambdas). Checkstyle supports java 8 constructs since 5.9.

**Comment by GilraenBurland** [comment]
@krzyk I used the latest version from maven-central: 0.12.1.

I got an error like this: `Expected . after 'this'` on the above mentioned method reference `this::doSomething`

**Comment by krzyk** [comment]
@GilraenBurland you can't use method reference with this in Java 8, it won't compile (`invalid reference static bound method reference`), so checkstyle is correct, the only `this` that can be used is the one that has either a `.` after it or a `(` (if inside constructor)

Maybe you have a longer example (a full class) that compiles fine, but causes problems with qulice?

**Comment by GilraenBurland** [comment]
@krzyk 

Example class which can be compiled but is not working with qulice:

```
/**
 * No license defined
 */

package example;

import java.util.stream.Stream;

/**
 * Example.
 *
 * @author Selena Lowell (selena.lowell@unknown.com)
 * @version $Id$
 */
public final class Example {

    /**
     * Values.
     */
    private static final String[] VALUES = {
        "Value 1", "Value 2", "Value 3",
    };

    /**
     * Ctor.
     */
    private Example() {
    }

    /**
     * Main.
     *
     * @param args Arguments
     */
    public static void main(final String[] args) {
        new Example().start();
    }

    /**
     * Start. Check fails in this method.
     */
    private void start() {
        Stream.of(Example.VALUES).forEach(this::doSomething);
    }

    /**
     * Method to be referenced.
     *
     * @param value Value to print
     */
    private void doSomething(final String value) {
        System.out.println(value);
    }
}
```

Error message I am getting now: `[ERROR] /src/main/java/example/Example.java[44]: Got an exception - expecting EOF, found '}' (TreeWalker)

If I remove the `.forEach(this::doSomething)` statement then everything is working fine.
`

**Comment by krzyk** [comment]
@davvd please see PR #445

**Comment by krzyk** [comment]
@GilraenBurland thanks, I forgout about instance references :), I've recreated the problem and fixed by updating checkstyle

**Comment by davvd** [comment]
> @davvd please see PR #445 

@krzyk thanks, will take a look

**Comment by krzyk** [comment]
@GilraenBurland changes have been merged to master, please close this issue

**Comment by GilraenBurland** [comment]
@krzyk Thank you very much!

**Comment by davvd** [comment]
@krzyk I added **30 mins** to your account, many thanks for working with the project! The completion time here was 60881448.; +30 added to your rating, at the moment it is: [+4431](http://www.netbout.com/b/35035?open=rating)
