### ISSUE TITLE
AntEnvironment.java:168-168: Implement exclude and excludes for...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#443]
Puzzle `337-8e901889` in `qulice-ant/src/main/java/com/qulice/ant/AntEnvironment.java:168-168` has to be resolved: Implement exclude and excludes for ant QuliceTask... The puzzle was created by Yegor Bugayenko on 30-Jun-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk "postponed" label already in this issue

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by davvd** [comment]
@krzyk Thanks all, closed
