### ISSUE TITLE
ConstantUsageCheck false positive if constant is only used in annotation

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#447]
There is a constant:
``` private static final int MAX = 25; ```

and it's used in:
``` java
    @Timeable(limit = MAX, unit = TimeUnit.SECONDS)
    public void close() {
    ....
    }
```
Qulice reports Checkstyle violation that ``` Private constant "MAX" is not used (ConstantUsageCheck) ```

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by davvd** [comment]
@longtimeago thank you for the ticket reported, I topped your account for 15 mins, transaction `64984797`

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk right, I added "urgent" label

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I removed "urgent" tags

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by krzyk** [comment]
@davvd not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk to this task pls

**Comment by krzyk** [comment]
@davvd please see PR #493

**Comment by davvd** [comment]
> @davvd not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @krzyk to this task pls

@krzyk done. @krzyk you are assigned to this task. please proceed...

**Comment by davvd** [comment]
> @davvd please see PR #493 

@krzyk thank you, I will check it

**Comment by krzyk** [comment]
@longtimeago code changes have been merged to master, please close this issue

**Comment by longtimeago** [comment]
@krzyk cool, thanks!

**Comment by davvd** [comment]
@longtimeago the code made here contains a puzzle `447-94597ea9`/#497, which will be resolved soon

**Comment by davvd** [comment]
@krzyk done, I added **45 mins** in payment `70054404`, 26 hours and 20 mins spent to complete this; the bonus for fast delivery (m=1580); +45 to your rating, your total score is [+2708](http://www.netbout.com/b/35035?open=rating)

**Comment by 0pdd** [comment]
@longtimeago the puzzle [#1126](https://github.com/yegor256/qulice/issues/1126) is still not solved.
