### ISSUE TITLE
@version $Id$ not replaced

### ISSUE THREAD

**Issue by piotrkot** [teamed/qulice#450]
There is qulice rule to put `$Id$` as version-text for version tag. That version text is not replaced during deployment. This can be verified by looking into sources.jar or javadoc.jar of, say, [jcabi-email] (http://search.maven.org/#search|ga|1|a%3A%22jcabi-email%22).
Please, explain what is the point of putting `@version $Id$`?

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@piotrkot it has to be replaced, see for example this project: https://github.com/teamed/rultor (clone it locally and check any `.java` file)

Just add `*.java ident` to your `.gitattributes`, as explained here: http://git-scm.com/docs/gitattributes
