### ISSUE TITLE
PMD doesn't recognize method references

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#454]
If I have a method that is used only as a method reference, then PMD will complain that it is not used anywhere.

Adding `net.sourceforge.pmd:pmd:5.1.2` to `qulice-maven-plugin` dependencies fixes it for me. I think it would be good to have the verson of PMD upgraded from 5.1.1 to 5.1.2 in `qulice-pmd`.

By the way, using newer PMD also fixes the errors described in #418

**Comment by Suseika** [comment]
Might as well upgrade all the way up to 5.1.3, there are lots of useful bugfixes: http://pmd.sourceforge.net/pmd-5.1.3/changelog.html

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by davvd** [comment]
@krzyk this task is yours, go ahead

**Comment by davvd** [comment]
@suseika many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `AP-06750415WT4113214`

**Comment by krzyk** [comment]
@davvd please see PR #456

**Comment by davvd** [comment]
> @davvd please see PR #456 

@krzyk I will take a look, thanks

**Comment by krzyk** [comment]
@Suseika code has been updated on master, please close this issue

**Comment by Suseika** [comment]
@krzyk Thanks

**Comment by davvd** [comment]
@krzyk **30 mins** sent to your balance (ID `64303251`), many thanks! It took 97 hours and 49 mins.. +30 to your rating, your total score is [+4066](http://www.netbout.com/b/35035?open=rating)
