### ISSUE TITLE
Prohibit a semicolon in the end of try-with-resourses head

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#461]
This code will compile, and qulice won't complain about it, but it won't pass our code review because of the extra semicolon:

```java
try (
    final Closeable door = new Door();
) {

}
```
or
```java
try (
    final Closeable door = new Door();
    final Closeable window = new Window();
) {

}
```

If qulice required this code to look like this:

```java
try (
    final Closeable door = new Door();
    final Closeable window = new Window() // ← No semicolon
) {

}
```

that would save us some time in code review.

**Comment by davvd** [comment]
@yegor256 please pay attention to this issue

**Comment by yegor256** [comment]
@Suseika good idea, thanks

**Comment by davvd** [comment]
@suseika thanks for the report, I topped your acc for 15 mins, payment ID `AP-70C21551A0862081A`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@Suseika could you update the the description how should the second case look like? (the one with two assignements inside the `try ()`), I assume it is:
```
try (
    final Closeable door = new Door();
    final Closeable window = new Window()
) {

}
```

**Comment by Suseika** [comment]
@krzyk That's correct, I updated the issue.

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@jrdalpra can you work on this?

**Comment by jrdalpra** [comment]
@krzyk I have the limit of 2 concurrent tasks. I'm trying to close to get more. For now I can't get it. Sorry.

**Comment by jrdalpra** [comment]
@krzyk @Suseika Is this too bad to have a extra semicolon at the source code?

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk OK @hdouss please proceed, this task is yours

**Comment by HDouss** [comment]
Using master branch, this code : 
```java
try (
    final Closeable door = new Door();
    final Closeable window = new Window();
) {

}
```
makes qulice complain with "Only one statement per line allowed."
I think that this good behaviour became available since we upgraded Checkstyle version to 6.12.1.
Anyway, I will add a unit test for it.

**Comment by HDouss** [comment]
@Suseika This is the commit that made Checkstyle complain : b405880b6e79f143c3ba3651fe6c8b68324fca51
It has 6.9 as a milestone. We were on 6.8.1 before upgrading. So, this is why it didn't complain until upgrade.

**Comment by krzyk** [comment]
@HDouss I see it was fixed in checkstyle https://github.com/checkstyle/checkstyle/issues/2211, but I don't think it was released yet

**Comment by HDouss** [comment]
@krzyk The issue you mentioned will cancel our desired behaviour. The author wants that : 
```
  try (
            OutputStream fos = new FileOutputStream("foo");
            OutputStream fos2 = new FileOutputStream("bah");) {
        }
```
to be accepted. Because since 6.9 it is not accepted (as desired by our issue).

**Comment by krzyk** [comment]
@HDouss No, it won't cancel that, it will be back to the original that allows multiple statements inside try-with-resources. It won't forbid `;` at the end of the last statement inside try.

**Comment by krzyk** [comment]
@HDouss author wants following to work:
```
  try (
            OutputStream fos = new FileOutputStream("foo");
            OutputStream fos2 = new FileOutputStream("bah")
        ) {
    }
```
and following to fail:
```
  try (
            OutputStream fos = new FileOutputStream("foo");
            OutputStream fos2 = new FileOutputStream("bah");
        ) {
    }
```

**Comment by krzyk** [comment]
@HDouss you can implement it with handling only a simple case of single statement insite `try ()`:
This should work:
```
try (
    final Closeable door = new Door()
) {

}
```
This should fail:
```
try (
    final Closeable door = new Door();
) {

}
```
And add a todo to handle multiple statements inside the `try()` (and mention the checkstyle bug there).

**Comment by HDouss** [comment]
@krzyk Don't you think that we have just to let it like it is if it is working for all cases right now ?
If someday we'll upgrade Checkstyle to an unedsired behaviour, the added unit test will alert us.

**Comment by HDouss** [comment]
@krzyk I don't agree with you on your previous comments. Please track the discussion in : checkstyle/checkstyle#64 and checkstyle/checkstyle#2211 and you will find out that on checkstyle/checkstyle#2211 they want to tolerate the optional finl semicolon

**Comment by HDouss** [comment]
@krzyk I found a strange behaviour of Checkstyle. Let me investigate further...

**Comment by krzyk** [comment]
@HDouss yes I know, I was thinking about implementing our own check for the semicolon.

**Comment by HDouss** [comment]
@krzyk Almost finishing implementing our own check

**Comment by HDouss** [comment]
@krzyk PR #549 created. I tested the implementation with every scenario I could think of.

**Comment by HDouss** [comment]
@Suseika PR #549 reviewed and merged. Please close the issue.

**Comment by Suseika** [comment]
@HDouss Thanks.

**Comment by davvd** [comment]
@hdouss I just added **30 mins** to your account, many thanks for your contribution (73452953).. 96 hours and 30 mins spent here... +30 added to your rating, at the moment it is: [+391](http://www.netbout.com/b/36032?open=rating)
