### ISSUE TITLE
Consider upgrade to latest PMD version

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#462]
Current PMD version (5.1.1) contains several annoying bugs,
for example http://sourceforge.net/p/pmd/bugs/1128/
This bug is reproduced with all primitive types.
It's fixed in PMD 5.2.2

Let's upgrade qulice to the latest version of PMD (or at least 5.2.2)

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by davvd** [comment]
@krzyk it's yours,please help,budget is 30 mins

**Comment by davvd** [comment]
@longtimeago thanks for tis bug, I topped your account for 15 mins, transaction `65812758`

**Comment by krzyk** [comment]
@longtimeago we are currently on 5.3.3, do you want to upgrade to 5.3.4?

**Comment by krzyk** [comment]
@longtimeago it was done in https://github.com/teamed/qulice/pull/456, but there was no release since then.
@yegor256 could you make a new release of qulice?

**Comment by longtimeago** [comment]
@krzyk humm ... looks like I've missed something.
Let's upgrade to 5.3.4 and then release a new version

**Comment by krzyk** [comment]
@davvd please see PR #466

**Comment by davvd** [comment]
> @davvd please see PR #466 

@krzyk thank you, I will check it

**Comment by krzyk** [comment]
@yegor256 could you make a new release with this changes?

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by krzyk** [comment]
@longtimeago please see qulice 0.13

**Comment by longtimeago** [comment]
@krzyk perfect! Thank you!

**Comment by davvd** [comment]
@krzyk **30 mins** was added to your account, many thanks for your contribution (payment 66242503)! The task took 119 hours and 28 mins.. +30 to your rating, your total score is [+3507](http://www.netbout.com/b/35035?open=rating)
