### ISSUE TITLE
Disallow initializing non-static fields in the field declaration

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#470]
When we initialize non-static fields where they are declared, it creates an inconsistency: some fields are initialized in the constructor, and some and initialized at declarations.

Compare this:

```java
class Service {
  private final transient int threads;
  private final transient Stopwatch started = new Stopwatch();
  public Service(int threads) {
    this.threads = threads;
  }
}
```

and this:

```java
class Service {
  private final transient Stopwatch started;
  public Service(int threads) {
    this.threads = threads;
    this.stopwatch = new Stopwatch();
  }
}
```

I know about the "constructors must be code-free" rule, but putting initialization at declaration for the sake of not having code in the constructor would be just a dirty hack.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@Suseika very good idea, thanks!

**Comment by davvd** [comment]
@krzyk it's yours, please help, budget is 30 mins

**Comment by krzyk** [comment]
@Suseika @yegor256 I think this rule is too restrictive. This would force creation of constructors when it is not really needed (e.g. in a class that doesn't have any parameters for constructors).
I really don't see any inconsistency in initializing final fields as soon as we know their value.

**Comment by yegor256** [comment]
@krzyk I think it would be logical to prohibit the use of constructors and at the same time pre-defined initialization. Just in the example above. If there are no constructors - you can initialize everything "statically". What do you think?

**Comment by davvd** [comment]
@suseika thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-8YX54112Y3057844P`

**Comment by krzyk** [comment]
@yegor256 makes sense

**Comment by krzyk** [comment]
@davvd please see PR #479

**Comment by krzyk** [comment]
@davvd please give me more time

**Comment by davvd** [comment]
> @davvd please see PR #479 

@krzyk will take a look, thanks

**Comment by davvd** [comment]
> @davvd please give me more time

@krzyk of course, thanks for letting me know, take your time

**Comment by krzyk** [comment]
@Suseika please close this issue, changes have been merged to master

**Comment by davvd** [comment]
@krzyk **30 mins** sent to your balance (ID `67436932`), many thanks! It took 213 hours and 44 mins.

+30 added to your rating, at the moment it is: [+3268](http://www.netbout.com/b/35035?open=rating)
