### ISSUE TITLE
We should be able to have constructor parameters with the same names as the fields

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#471]
We have a rule that parameters' names must be different from fields' names. Generally it is really useful and helps prevent some overlooked problems. 

But there is one exception. This rule is absolutely *destructive* to code quality when applied to constructors.

Generally we have just assignments in constructors:
```java
public Rectangle(final int w, final int h) {
    this.width = w;
    this.height = h;
}
```

Parameters in constructors must be the same things as the fields, because they are just assigned to fields and not operated upon in any way. And if thing A and thing B are the same thing used for the same reason, then A and B should have the same name. But they can't because of our rules.

Current rule leads to us inventing synonyms, like `w` instead of `width` and `h` instead of `heght`. Sometimes those synonyms are easy to figure out, sometimes they are really hard. I don't think we should be doing this. Synonyms in code are a disaster.

Another thing is that a constructor parameter's name and field name are important for different reasons. Constructor parameter names show up in completion dialogues in IDE, and field names show up in the code of class. Both constructor parameters and fields should have expressive names, but our quality standards don't allow them both to be maximally expressive.

### What we should do

I think that we should be *enforcing* constructor parameters to have the same names as field names. Current approach harms code quality, and the suggested approach actually improves it. A properly designed class would never actually need a constructor parameter to have different name from the field it is stored in.

If it is too difficult to enforce the naming for constructor parameters (or if you think that it is not a good idea), then at least excluding constructor parameters from the `HiddenFieldCheck` would be a huge improvement.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@Suseika good idea indeed, thanks!

**Comment by davvd** [comment]
@krzyk it's yours, please help, budget is 30 mins

**Comment by davvd** [comment]
@suseika thank you for reporting this, I added 15 mins to your acc, transaction `AP-15H82593UM4350141`

**Comment by krzyk** [comment]
@davvd please see PR #476

**Comment by krzyk** [comment]
@davvd please give me more time

**Comment by davvd** [comment]
> @davvd please see PR #476

@krzyk will take a look, thanks

**Comment by davvd** [comment]
> @davvd please give me more time

@krzyk no problem, thanks for letting me know

**Comment by krzyk** [comment]
@Suseika please close this issue, code changes have been merged to master

**Comment by Suseika** [comment]
@krzyk Great, thanks

**Comment by davvd** [comment]
@krzyk Thanks for your contribution, **30 mins** was added to your account, payment ID is `67436926`, 213 hours and 44 mins spent total... +30 added to your rating, current score is: [+3238](http://www.netbout.com/b/35035?open=rating)
