### ISSUE TITLE
Generic parameters should be documented

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#472]
This code will pass qulice test
```java
/**
 * Box with content.
 * @author Sam (sam@i.am)
 * @version $Id$
 * @since 0.5
 */
public interface Box<T> {

}
```

The problem here that parameter `T` is not documented. Qulice should disallow that. Instead, the correct code would be:

```java
/**
 * Box with content.
 * @author Sam (sam@i.am)
 * @version $Id$
 * @since 0.5
 * @param <T> Type of content
 */
public interface Box<T> {

}
```

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by davvd** [comment]
@krzyk this is yours, pls go ahead

**Comment by davvd** [comment]
@suseika thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-8FG78582YD3150241`

**Comment by krzyk** [comment]
@davvd please see PR #475

**Comment by krzyk** [comment]
@davvd are you alive?

**Comment by krzyk** [comment]
@davvd please give me more time

**Comment by davvd** [comment]
> @davvd please see PR #475 

@krzyk thank you, I will check it

**Comment by davvd** [comment]
> @davvd please give me more time

@krzyk yes, take your time, thanks for letting me know

**Comment by krzyk** [comment]
@Suseika please close this issue, changes have been merged to master

**Comment by Suseika** [comment]
@krzyk Thanks

**Comment by davvd** [comment]
@krzyk thank you, added **30 mins** to your acc, payment num is `67436902`, 213 hours and 44 mins spent in total to complete... +30 added to your rating, at the moment it is: [+3208](http://www.netbout.com/b/35035?open=rating)
