### ISSUE TITLE
Logging of checks is inconsistent

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#474]
Here is a typical qulice log. You can see that all the checks except for Checkstyle and PMD are reported before the actual check has started.
```
[INFO] --- qulice-maven-plugin:0.12.2:check (jcabi-check) @ inflectible ---
[INFO] LICENSE found: file:/home/suseika/Projects/inflectible/LICENSE.txt
log4j:WARN No appenders could be found for logger (com.puppycrawl.tools.checkstyle.ConfigurationLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] No Checkstyle violations found in 173 files
[INFO] No PMD violations found in 161 files
[INFO] CodeNarc not required since no groovy files in /home/suseika/Projects/inflectible/src
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://aspects.jcabi.com/jsr-303.html)
[INFO] jcabi-aspects 0.22/7e07127 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[INFO] Calling org.apache.maven.plugins:maven-enforcer-plugin:1.0-beta-1:enforce...
[INFO] Calling com.ning.maven.plugins:maven-duplicate-finder-plugin:1.0.7:check...
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Calling org.codehaus.mojo:cobertura-maven-plugin:2.5.1:check...
[INFO] Cobertura 1.9.4.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Cobertura: Loaded information on 105 classes.

[INFO] All checks passed.
[INFO] This is not an SVN project
[INFO] No dependency problems found
[INFO] Calling org.codehaus.mojo:jslint-maven-plugin:1.0.1:jslint...
[INFO] Qulice quality check completed in 1min
```

This is inconsistent, I suggest adding log lines that tell when Checkstyle starts and when PMD starts. Before Checkstyle has completed, you can't tell from the log what is taking up 100% of your CPU (unless you worked with Qulice for some time and know when it starts what).

**Comment by davvd** [comment]
@yegor256 please dispatch this issue

**Comment by davvd** [comment]
@suseika thanks for the ticket, your account was topped for 15 mins, payment AP-0CH92146DS483281S

**Comment by krzyk** [comment]
@davvd assign @krzyk here

**Comment by krzyk** [comment]
@davvd please see PR #499

**Comment by davvd** [comment]
> @davvd assign @krzyk here

@krzyk done. @krzyk the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd please see PR #499 

@krzyk will take a look, thanks

**Comment by krzyk** [comment]
@Suseika I've added in logs the start and end of each validator, please close this issue if it is OK.

**Comment by davvd** [comment]
@krzyk Thank you, I have added **45 mins** to your account in payment/transaction "`70622560`", time consumed: 24 hours and 26 mins; m=1466, that's why a bonus here for fast delivery; added +45 to your rating, now it is equal to [+2914](http://www.netbout.com/b/35035?open=rating)
