### ISSUE TITLE
There should be only one main constructor

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#477]
A main constructor is the one that does the real work by setting all the necessary fields in the class, all other constructors should just delegate work to it.

Qulice should complain in such case:
```
public class Car {
    private final Engine engine;
    private final Steering steering;

    public Car(final Engine eng, final Steering steer) {
        this.engine = eng;
        this.steering = steer;
    }

    public Car(final Engine eng) {
        this.engine = eng;
        this.steering = new DefaultSteering();
    }
...
```

Correct case is:
```
public class Car {
    private final Engine engine;
    private final Steering steering;

    public Car(final Engine eng, final Steering steer) {
        this.engine = eng;
        this.steering = steer;
    }

    public Car(final Engine eng) {
        this(eng, new DefaultSteering());
    }
...
```

The above is currently enforced only if there is a superclass (e.g. when `Car extends Vehicle`), but should be enforced always.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please

**Comment by davvd** [comment]
@krzyk thank you for reporting this, I added 15 mins to your acc, transaction `67401090`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by krzyk** [comment]
@carlosmiranda want to give it a try? (I think it should be possible using PMD XPath, similar to  `ConstructorShouldDoInitialization` in https://github.com/teamed/qulice/blob/master/qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml#L99-L119)

**Comment by krzyk** [comment]
@longtimeago or maybe you want to try this?

**Comment by longtimeago** [comment]
@krzyk can try, why not

**Comment by krzyk** [comment]
@davvd assign @longtimeago

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@longtimeago thanks

**Comment by davvd** [comment]
> @davvd assign @longtimeago 

@krzyk OK @longtimeago please go ahead, this task is yours

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by longtimeago** [comment]
@davvd here is the PR https://github.com/teamed/qulice/pull/504

**Comment by longtimeago** [comment]
@davvd need more time

**Comment by davvd** [comment]
> @davvd need more time

@longtimeago of course, take your time

**Comment by krzyk** [comment]
@longtimeago thanks

**Comment by davvd** [comment]
@longtimeago Much obliged! I have added **30 mins** to your account in payment "71364685", 169 hours and 13 mins spent. +30 to your rating, your total score is [+1509](http://www.netbout.com/b/35024?open=rating)
