### ISSUE TITLE
Constructors should be code free

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#478]
There is no rule that would forbid putting anything other than field assignments into constructors.
The only exception should be calling other constructors or calling super class constructor.
Please add such rule.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by davvd** [comment]
@krzyk thank you for reporting this, I added 15 mins to your acc, transaction `67397534`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@HDouss can you take this? I think it can be done using PMD XPath (see bottom of our [ruleset.xml](https://github.com/teamed/qulice/blob/master/qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml#L100-L142) and some other rules in PMD sources).

**Comment by HDouss** [comment]
@krzyk Ok

**Comment by HDouss** [comment]
@krzyk I will wait for assignment to start working on this issue

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk OK @hdouss please proceed, this task is yours

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by HDouss** [comment]
@krzyk PR #545 accepted and merged. Please close the issue.

**Comment by krzyk** [comment]
@HDouss thanks

**Comment by HDouss** [comment]
@davvd Issue closed

**Comment by davvd** [comment]
@hdouss Thanks for your contribution, **30 mins** was added to your account, payment ID is `73360867`, 115 hours and 16 mins spent total; +30 added to your rating, current score is: [+361](http://www.netbout.com/b/36032?open=rating)
