### ISSUE TITLE
AvoidInstantiatingObjectsInLoops prohibits instantiating the Iterable we're iterating over

### ISSUE THREAD

**Issue by Suseika** [teamed/qulice#480]
This code would not pass qulice check, but it should:

```java
for (final Integer number : new ArrayList<Integer>(Tv.TEN)) {
    number.intValue();
}
```

PMD treats `new ArrayList<Integer>(Tv.TEN)` as an object instantiated inside a loop. 

One might argue if it is actually *inside* the loop, but anyway I think that this violation should not happen in this case.

Of course, that is not a particularly good piece of code, it is just a minimal reproducible example.

Disallowing instantiating the `Iterable` in the loop head makes us use a one-time variable, which would be another quality issue.

A similar issue in PMD bug tracker: http://sourceforge.net/p/pmd/bugs/1215/

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by davvd** [comment]
@krzyk the task is yours (budget is 30 mins)

**Comment by davvd** [comment]
@suseika thanks for reporting! I topped your account for 15 mins, transaction AP-6U016237AP3937530

**Comment by krzyk** [comment]
@Suseika have you tried latest qulice? In version 0.13 PMD was upgraded to 5.3.4 (or 5.3.3) and this error is not reported.

**Comment by Suseika** [comment]
@krzyk Right, it can only be reproduced in older versions, closing.

**Comment by davvd** [comment]
@krzyk paid, thanks, added **38 mins** to your account, payment `68031944`, 48 hours and 27 mins was spent... the bonus for fast delivery (m=2907)... +38 added to your rating, at the moment it is: [+3051](http://www.netbout.com/b/35035?open=rating)
