### ISSUE TITLE
XmlValidator.java:173-179: Remove the method below and...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#483]
Puzzle `469-1b2c894b` in `qulice-xml/src/main/java/com/qulice/xml/XmlValidator.java:173-179` has to be resolved: Remove the method below and find a way to format tags correctly in XML. Attributes should be indented by 4 spaces, just like XML tags, but in IT xml-violations there is a tag that our Prettifier want to be indented by 3 spaces which is wrong. Another problem is that in the parent tag, attributes are indented to match the first attribute, this is also wrong - all attributes on new line should be indented by 4 spaces.... The puzzle was created by krzyk on 17-Oct-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by davvd** [comment]
@krzyk The task is closed, thanks everybody
