### ISSUE TITLE
HeaderCheck needs explanation

### ISSUE THREAD

**Issue by aistomin** [teamed/qulice#486]
I'm just not sure that I understand everything correctly. ```HeaderCheck``` needs this lines to be the first statement in the header javadoc:
``` 
 * Copyright (c) 2011-2014, Qulice.com
```
So, basically, my question is: Why should I put this copyright to _my_ code? I already included the license, that means that I respect Qulice and I do not pretend that it's my library. But, the code where it forces me to put this copyright, is the code that was created by me. I used Qulice in process of this code creation, that's true, license proofs that. But does it mean that this code was created by Qulice, JetBrains, Apple, company that produces the coffee I drink? I'm using all of them when I'm programming, should I put copyright of them all to the header? Who's gonna be the first in line? Of course, Qulice, because it just won't work without it. To me sounds a little bit strange. Could someone explain this to me, please? :)

**Comment by krzyk** [comment]
@aistomin the `LICENSE.txt` file you add to your code is yours code license, and `HeaderCheck` assures that every one of your code files will contain this license text at the top. Replace this file with the license you want.

**Comment by aistomin** [comment]
Ah, now I got the idea :) It checks that I didn't forget to include _my own_ licence. Wonderful idea. Thanks a lot for explanation. I'm going to close the issue.
