### ISSUE TITLE
Update Checkstyle to 6.12.1

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#487]
Current version used by Qulice is 6.8.1. Since that version multiple bugs were fixed and CommentsIndentation check was added: http://checkstyle.sourceforge.net/releasenotes.html

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by mkordas** [comment]
Checkstyle 6.12.1 is out, renamed issue accordingly

**Comment by krzyk** [comment]
@mkordas please close  this issue, changes have been merged to master

**Comment by mkordas** [comment]
@davvd can I receive payment for this issue?

**Comment by davvd** [comment]
> @davvd can I receive payment for this issue?

@mkordas @yegor256 please help us here

**Comment by yegor256** [comment]
@davvd pls add extra 15 mins to @mkordas

**Comment by davvd** [comment]
> @davvd pls add extra 15 mins to @mkordas 

@yegor256 I've paid 15 mins to @mkordas in transaction `567a9b2e9609dd4fea00016d`
