### ISSUE TITLE
PMD.ConstructorShouldDoInitialization should ignore static fields

### ISSUE THREAD

**Issue by pinaf** [teamed/qulice#491]
Regarding the `PMD.ConstructorShouldDoInitialization` check, 

this should be a problem:
```java
public final class FieldInitNoConstructor {
    private final transient int number = 1;

    public int num() {
        return number;
    }
}
```
But this shouldn't:
```java
public final class FieldInitConstructor {
    private static final transient String text = "STATIC";
    private final transient int number;

    public FieldInitConstructor() {
        this.number = 2;
    }

    public int num() {
        return number;
    }

    public String tex() {
        return text;
    }
}
```
Qulice compains with a PMD violation
>
Avoid doing field initialization outside constructor. (ConstructorShouldDoInitialization)

It should, instead, not complain but ignore the static field initialization outside the constructor.

**Comment by krzyk** [comment]
@pinaf Please update the description with the error message you are getting

**Comment by pinaf** [comment]
@krzyk updated title and description

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by pinaf** [comment]
@krzyk is he alive? :)

**Comment by krzyk** [comment]
@davvd ping

**Comment by krzyk** [comment]
@yegor256 could you check on @davvd ?

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
@pinaf thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-1FG15817LT144504P`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by pinaf** [comment]
@krzyk btw, this is needed in another project.

**Comment by krzyk** [comment]
@pinaf I will do it now

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by krzyk** [comment]
@davvd please see PR #501

**Comment by pinaf** [comment]
@krzyk thanks!

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd assign @krzyk

@krzyk done. @krzyk the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd please see PR #501 

@krzyk will take a look at it, thanks

**Comment by pinaf** [comment]
@krzyk thanks! can we release a new version?

**Comment by krzyk** [comment]
@rultor release tag is `0.13.3`

**Comment by krzyk** [comment]
@pinaf sure

**Comment by pinaf** [comment]
@krzyk does it take time for it to show up in maven central?

**Comment by krzyk** [comment]
@pinaf As I see it takes few minutes, I see that 0.13.3 is now available

**Comment by pinaf** [comment]
@krzyk yep - thanks!

**Comment by davvd** [comment]
@krzyk **1 hour** added to your account (payment number `70615709`), many thanks for your contribution! 22 hours and 2 mins spent here.. there is a bonus for fast delivery (m=1322). added +60 to your rating, now it is equal to [+2899](http://www.netbout.com/b/35035?open=rating)
