### ISSUE TITLE
JavadocTagsCheck doesn't validate all author tags

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#495]
Following example:
```
**
 * Simple.
 * @author John Smith (john.smith@example.com)
 * @author None
 * @version $Id$
 */
public interface AuthorTag {
}
```
Should fail, because second author has incorrect format (it doesn't have an email address), but it doesn't.
When you change order of author tags, `JavadocTagsCheck` will fail.
Fix `JavadocTagsCheck` to check all `@author` tags.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@krzyk many thanks for the report, I topped your account for 30 mins, transaction 70054478

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by mkordas** [comment]
@krzyk can you assign me here?

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd assign @mkordas please 

@krzyk done. @mkordas the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd this is not postponed 

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by mkordas** [comment]
@davvd please see PR #573

**Comment by davvd** [comment]
> @davvd please see PR #573

@mkordas will take a look, thanks

**Comment by mkordas** [comment]
@krzyk this was merged in #573, can you close the issue?

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
@mkordas done, I added **30 mins** in payment `568cea2e2310ad21f7000311`, 98 hours and 23 mins spent to complete this

added +30 to your rating, now it is equal to [+1375](http://www.netbout.com/b/36080?open=rating)
