### ISSUE TITLE
CheckstyleValidatorTest.java:214-216: Right now ConstantUsageCheck takes into...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#497]
Puzzle `447-94597ea9` in `qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java:214-216` has to be resolved: Right now ConstantUsageCheck takes into account usage of constants inside method annotations, add handling of constants used in field and class annotations.... The puzzle was created by krzyk on 14-Nov-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by davvd** [comment]
@krzyk Thanks all, I am closing
