### ISSUE TITLE
String concatenation check sometimes doesn't work

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#502]
In case of following code:
```
            throw new IllegalStateException("Failed to create checker"
                + " test" + ex.getMessage(), ex
            );
```
`StringLiteralsConcatenationCheck` will not report an error, but it should.

But it will report error in such case:
```
            throw new IllegalStateException("Failed to create checker"
                + " test" + " other", ex
            );
```
~~Waiting for fix in  checkstyle/checkstyle#2766~~ (Actually it doesn't like like related to checkstyle/checkstyle#2766)
Please make this check work for both cases.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
@krzyk many thanks, **30 mins** added to your acc for reporting this bug, pmt ID `70521321`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by krzyk** [comment]
@Happy-Neko I'm wondering if this is a similar issue as #503, would like to pick it up?

**Comment by Happy-Neko** [comment]
@krzyk Ok, I'll check it.

**Comment by Happy-Neko** [comment]
@krzyk Same problem as #503.

**Comment by krzyk** [comment]
@Happy-Neko Thanks, I'll wait for the checkstyle fix before assigning this to you.

**Comment by krzyk** [comment]
@Happy-Neko I've look at this and it doesn't look like the same problem as in #503, can I assign you on this?

**Comment by Happy-Neko** [comment]
@krzyk ok.

**Comment by krzyk** [comment]
@davvd assign @Happy-Neko

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd assign @Happy-Neko 

@krzyk yep, done. @happy-neko it is your task now

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by krzyk** [comment]
@Happy-Neko thanks

**Comment by davvd** [comment]
@happy-neko Many thanks! **30 mins** were added to your account in Transaction ID `AP-9NP06237JN410054F` (task took 100 hours and 45 mins)... +30 added to your rating, current score is: [+188](http://www.netbout.com/b/36136?open=rating)

**Comment by krzyk** [comment]
@yegor256 I didn't get *30mins* for reporting this issue

**Comment by yegor256** [comment]
@krzyk OK
