### ISSUE TITLE
CheckstyleValidatorTest.java:51-53: Split this class into smaller...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#505]
Puzzle `412-bd044e76` in `qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java:51-53` has to be resolved: Split this class into smaller ones and remove PMD exclude `TooManyMethods`. Good candidates for moving out of this class are all that use `validateCheckstyle` method.... The puzzle was created by krzyk on 18-Nov-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by davvd** [comment]
@krzyk Done, thanks all, closing..
