### ISSUE TITLE
Disallow methods with multiple return statements

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#515]
Following code:
```
    public Integer otherNumber(final String number) {
        try {
            return Integer.parseInt(number);
        } catch (final NumberFormatException ex) {
            return -1;
        }
    }
```
should make qulice complain about two return statements (right now we allow 2 return statements).
(see http://www.yegor256.com/2015/08/18/multiple-return-statements-in-oop.html)

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment]
@krzyk thanks a lot for reporting, **30 mins** added to your acc, pmt ID `71947289`

**Comment by mkordas** [comment]
@davvd please assign me to this issue

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk yep, done. @mkordas it is your task now

**Comment by mkordas** [comment]
@krzyk this was done in #530, please proceed

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by mkordas** [comment]
@davvd this was closed 3 days ago, please summarize

**Comment by mkordas** [comment]
@davvd ping

**Comment by davvd** [comment]
@mkordas paid, thanks, added **38 mins** to your account, payment `567914232bc9e96f3400014b`, 71 hours and 49 mins was spent. m=4309, that's why a bonus here for fast delivery. +38 added to your rating, current score is: [+719](http://www.netbout.com/b/36080?open=rating)

**Comment by davvd** [comment]
> @davvd this was closed 3 days ago, please summarize

@mkordas usually it takes a few days to finalize a task, thanks for your patience
