### ISSUE TITLE
[question] Why the release number is not flowing semver?

### ISSUE THREAD

**Issue by kkamkou** [teamed/qulice#517]
Hi all! I have a simple question - why the release number is not flowing [semver](http://semver.org/)? Thank you.

**Comment by krzyk** [comment]
@kkamkou Why do you think it doesn't?

**Comment by kkamkou** [comment]
afaik 0.14.0 is the semver format, and 0.14 is the formatted output M.m

**Comment by krzyk** [comment]
@yegor256 Why do we skip zeros at the end major release version (`0.14` instead of `0.14.0`)?

**Comment by yegor256** [comment]
@krzyk @kkamkou well, that's how it's done in Maven world. see how Maven plugins are versioned. they all skip minor version if it equals to zero. we're doing the same. and, I think, it's correct.

**Comment by kkamkou** [comment]
Thank you
