### ISSUE TITLE
[question] Why com.qulice:qulice-gradle-plugin:0.14 produces qulice-plugin (gradle)?

### ISSUE THREAD

**Issue by kkamkou** [teamed/qulice#518]
Hi all! I have a simple question: why `com.qulice:qulice-gradle-plugin:0.14` produces `qulice-plugin` instead of `qulice` or `com.qulice.gradle` etc.? Thank you. refs #404

**Comment by krzyk** [comment]
@kkamkou Initial design of gradle plugin introduced it, it will be changed as part of #422

**Comment by kkamkou** [comment]
Thank you.
