### ISSUE TITLE
Qulice does not enforce Checkstyle rule NoLineWrap

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#520]
[NoLineWrap](http://checkstyle.sourceforge.net/config_whitespace.html#NoLineWrap) check is not enforced by qulice-checkstyle, I think someone just forgot to enable it. Wrapping package and import statements should be prohibited:
* https://google.github.io/styleguide/javaguide.html#s3.2-package-statement
* https://google.github.io/styleguide/javaguide.html#s3.3.2-import-line-wrapping

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by HDouss** [comment]
@krzyk Please assign this to me

**Comment by krzyk** [comment]
@davvd assign @HDouss pls

**Comment by davvd** [comment]
> @davvd assign @HDouss pls

@krzyk yep, done. @hdouss it is your task now

**Comment by davvd** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `5673b60a2bc9e972d60000a0`

**Comment by HDouss** [comment]
@mkordas PR #531 reviewed and merged. Please close the issue.

**Comment by HDouss** [comment]
@mkordas PR #531 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss I'm closing it, thanks

**Comment by HDouss** [comment]
@davvd Issue closed.

**Comment by davvd** [comment]
> @davvd Issue closed.

@hdouss thanks

**Comment by davvd** [comment]
@hdouss Thanks a lot, I just topped your account for **38 mins**, transaction ID `72856726`, total time was 71 hours and 49 mins... the bonus for fast delivery (m=4309)... +38 added to your rating, current score is: [+256](http://www.netbout.com/b/36032?open=rating)
