### ISSUE TITLE
Leftovers after removal of RedundantThrows check from Checkstyle

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#524]
RedundantThrows was removed from Checkstyle at version 6.2 (https://github.com/checkstyle/checkstyle/issues/473), because it was too buggy.

Due to problems with it, Qulice had many workarounds for it - mainly suppressions. When this check was removed from Qulice there was no proper cleanup.

All occurrences of `RedundantThrows` should be removed from code. Currently we have 22 of them, e.g.:
* https://github.com/teamed/qulice/search?utf8=%E2%9C%93&q=RedundantThrows&type=Code
* https://github.com/teamed/qulice/search?utf8=%E2%9C%93&q=RedundantThrowsCheck&type=Code

`RedundantThrowsCheckTest` should be removed too, as it become obsolete.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `5673fe065cf2414e1600002a`

**Comment by krzyk** [comment]
@davvd it is not postponed

**Comment by krzyk** [comment]
@davvd assign @jrdalpra please

**Comment by davvd** [comment]
> @davvd assign @jrdalpra please

@krzyk done. @jrdalpra the task is yours, please go ahead

**Comment by jrdalpra** [comment]
@davvd ok
@mkordas just to be clear: just remove the unnecessary code and tests to clean the project, right?

**Comment by mkordas** [comment]
@jrdalpra yes, just do project cleanup

**Comment by jrdalpra** [comment]
@mkordas done
@davvd can u assign someone to review the code?

**Comment by jrdalpra** [comment]
@mkordas can you close the issue, please?

**Comment by krzyk** [comment]
@jrdalpra please always provide the PR number in the issue, so the creator can look at it

**Comment by jrdalpra** [comment]
@mkordas the PR is here https://github.com/teamed/qulice/pull/560

**Comment by mkordas** [comment]
@jrdalpra thanks!

**Comment by jrdalpra** [comment]
@dmarkov @krzyk closed here. Now can close at netbout. Thanks.

**Comment by davvd** [comment]
@jrdalpra Thanks so much! Your account was topped up for **38 mins** (transaction ID is `AP-44Y88423VW859082H`, the task took 71 hours and 59 mins)... there is a bonus for fast delivery (m=4319)... +38 added to your rating, at the moment it is: [+98](http://www.netbout.com/b/36044?open=rating)
