### ISSUE TITLE
Cascade indentation check is required

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#527]
We removed `CascadeIndentationCheck` in https://github.com/teamed/qulice/issues/265 and it was a bad idea. We must check that each line indentation is either:

 1. the same as previous one or less
 2. bigger than previous by exactly 4

All other cases must cause a failure.

**Comment by krzyk** [comment]
@yegor256 maybe we could use `IndentationCheck` with `forceStrictCondition = true` for that.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by yegor256** [comment]
@krzyk yes, why not. what matters for me is that qulice must complain about this:

```
String a = String.format(
      "test"
);
```

It doesn't complain now.

**Comment by mkordas** [comment]
@krzyk please assign me (I will proceed with adding `forceStrictCondition = true` + some test for Yegor's case)

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk done. @mkordas the task is yours, please go ahead

**Comment by davvd** [comment]
@yegor256 thanks for the ticket, your account was topped for 15 mins, payment 000-814caaa3

**Comment by mkordas** [comment]
@davvd please see PR #538

**Comment by davvd** [comment]
> @davvd please see PR #538 

@mkordas will check it soon, thanks

**Comment by mkordas** [comment]
@yegor256 please verify and close the issue, it was done in #538

**Comment by yegor256** [comment]
@mkordas thanks!

**Comment by mkordas** [comment]
@yegor256 you're welcome

@davvd issue is closed, please summarize

**Comment by davvd** [comment]
@mkordas thank you, added **38 mins** to your acc, payment num is `567bad209a19d83aae0000cd`, 49 hours and 5 mins spent in total to complete

m=2945, that's why a bonus here for fast delivery

+38 to your rating, your total score is [+802](http://www.netbout.com/b/36080?open=rating)
