### ISSUE TITLE
Qulice does not enforce any of PMD rules from 'unnecessary' set

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#528]
There are lots of valuable and pretty non-controversial rules in [PMD 'unnecessary' ruleset](https://pmd.github.io/pmd-5.4.1/pmd-java/rules/java/unnecessary.html), but they are not mentioned in [Qulice's PMD configuration](https://github.com/teamed/qulice/blob/0.14/qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml).

I would excpect all of them being enforced by Qulice.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by HDouss** [comment]
@krzyk Please assign this to me.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment]
> @davvd assign @HDouss please 

@krzyk OK @hdouss please go ahead, this task is yours

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `5677d1dc36029277f70001af`

**Comment by HDouss** [comment]
@mkordas PR #534 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss I'm closing it

**Comment by HDouss** [comment]
@davvd Issue closed. Please proceed.

**Comment by davvd** [comment]
> @davvd Issue closed. Please proceed.

@hdouss sure, will do soon

**Comment by HDouss** [comment]
@davvd Thanks!

**Comment by davvd** [comment]
> @davvd Thanks! 

@hdouss sure, no problem

**Comment by davvd** [comment]
@hdouss **45 mins** sent to your balance (ID `72986607`), many thanks! It took 47 hours and 19 mins.. m=2839, that's why a bonus here for fast delivery. +45 added to your rating, current score is: [+316](http://www.netbout.com/b/36032?open=rating)
