### ISSUE TITLE
Upgrade to PMD 5.4.1

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#540]
Qulice currently uses PMD 5.3.4. Let's upgrade to the newest version and we'll get those things:
* https://pmd.github.io/pmd-5.3.5/overview/changelog.html
* https://pmd.github.io/pmd-5.4.0/overview/changelog.html
* https://pmd.github.io/pmd-5.4.1/overview/changelog.html

I'd suggest to make sure that the following new checks are enabled after update:
* Basic: SimplifiedTernary (rulesets/java/basic.xml/SimplifiedTernary)
Ternary operator with a boolean literal can be simplified with a boolean expression.
* Clone: CloneMethodMustBePublic (rulesets/java/clone.xml/CloneMethodMustBePublic)
The java manual says “By convention, classes that implement the Cloneable interface should override Object.clone (which is protected) with a public method.”
* Clone: CloneMethodReturnTypeMustMatchClassName (rulesets/java/clone.xml/CloneMethodReturnTypeMustMatchClassName)
If a class implements Cloneable the return type of the method clone() must be the class name.
* Design: SingletonClassReturningNewInstance (rulesets/java/design.xml/SingletonClassReturningNewInstance)
Verifies that the method called getInstance returns a cached instance and not always a fresh, new instance.
* Design: SingleMethodRule (rulesets/java/design.xml/SingleMethodSingletonRule)
Verifies that there is only one method called getInstance. If there are more methods that return the singleton, then it can easily happen, that these are not the same instances - and thus no singleton.

We should make sure that the following rule is disabled, as we have different convention for `this` usage:
* Unnecessary: UselessQualifiedThis (rulesets/java/unnecessary.xml/UselessQualifiedThis)
Flags unnecessary qualified usages of this, when this alone would be unique. E.g. use just this instead of Foo.this.

Pay attention to rename that happened:
* UseSingleton -> UseUtilityClass

**Comment by krzyk** [comment]
@mkordas can you suggest what new rules from those version might be useful?

**Comment by mkordas** [comment]
@krzyk done in description

**Comment by krzyk** [comment]
@mkordas `UselessQualifiedThis` seams to touch only reference to classes (`Foo.this` -> `this`), so I think it can be enabled (and tested that it doesn't cause problems with our code).

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag "bug" added

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `56813eb4b5bdf431080001a0`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by krzyk** [comment]
@Happy-Neko do you want to work on this?

**Comment by Happy-Neko** [comment]
@krzyk ok.

**Comment by krzyk** [comment]
@davvd assign @Happy-Neko please

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by davvd** [comment]
> @davvd assign @Happy-Neko please 

@krzyk OK @happy-neko please start, the task is yours

**Comment by davvd** [comment]
> @davvd this is not postponed 

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by Happy-Neko** [comment]
@davvd Please proceed with code review (PR #619).

**Comment by davvd** [comment]
> @davvd Please proceed with code review (PR #619).

@happy-neko will take a look, thanks

**Comment by Happy-Neko** [comment]
@mkordas PR merged. Please review and close ticket if everything is ok.

**Comment by mkordas** [comment]
@Happy-Neko good job!

**Comment by davvd** [comment]
@happy-neko thanks, I just added **30 mins** to your account, payment `AP-3MP13451EX5361914`, 145 hours and 42 mins spent... +30 to your rating, your total score is [+98](http://www.netbout.com/b/36136?open=rating)
