### ISSUE TITLE
BracketsStructureCheck doesn't report problem when parameters are expressions because of the Checkstyle lib bug

### ISSUE THREAD

**Issue by Happy-Neko** [teamed/qulice#541]
I have reported Checkstyle bug [here](https://github.com/checkstyle/checkstyle/issues/2766).

We should wait for confirmation and test `BracketsStructureCheck` with fixed checkstyle version.

**Comment by krzyk** [comment]
@Happy-Neko Let's wait for fix in checkstyle project and will get back to #503. Please close this issue.

**Comment by Happy-Neko** [comment]
@krzyk We need more time for #503 then. 30 min budget was spent to determine the problem is on external library and confirming it with unit test.

**Comment by krzyk** [comment]
@Happy-Neko Unfortunately I don't have a way to control that :(. The only option is to do the ticket fast, and you will get bonus points (+30, +15 or +8 mins if you can get this issue closed in 24,48,72 hours).
I'll assign #503 to you as soon as I'll see that checkstyle bug was fixed, so you will not waste 30mins you already spent on it, if you will work fast on implementing the fix (e.g. by upgrading checkstyle) you can get 60 mins.
Also take into account that 30mins is usually an average, sometimes you will spend 10mins on an issue, sometimes 50mins.
30mins is also a way to limit the size of the changes, you can add todo puzzles for missing corner cases, and do just the happy path (a design). But each ticket should give something usable for the user, adding a test for project outside of ours doesn't do that.

**Comment by krzyk** [comment]
@Happy-Neko please close this issue

**Comment by Happy-Neko** [comment]
@krzyk issue closed.
