### ISSUE TITLE
NonStaticMethodCheck is commented out in checks.xml

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#542]
In `checks.xml` there is comment:
```xml
        <!--
        see https://github.com/teamed/qulice/issues/239
        <module name="com.qulice.checkstyle.NonStaticMethodCheck">
            <property name="excludeFileNamePattern" value=".*Test\.java"/>
        </module>
        -->
```
However, issue #239 is already fixed and check should be re-enabled.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 567d4a72a59f9f1ec70003ae

**Comment by HDouss** [comment]
@krzyk assign this to me please.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please 

@krzyk OK @hdouss please start, the task is yours

**Comment by HDouss** [comment]
@mkordas PR #564 reviewed and merged. Please close the issue

**Comment by mkordas** [comment]
@HDouss thanks!

**Comment by HDouss** [comment]
@davvd Isuue closed

**Comment by davvd** [comment]
> @davvd Issue closed

@hdouss thanks

**Comment by davvd** [comment]
@hdouss done, I added **30 mins** in payment `73861283`, 95 hours and 56 mins spent to complete this. +30 to your rating, your total score is [+624](http://www.netbout.com/b/36032?open=rating)
