### ISSUE TITLE
Require '@since' tag in class Javadocs

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#550]
Our coding standard require each top-level class to have `@since` tag.

Qulice should complain when this tag is missing. It could be implemented as e.g. custom Checkstyle check.

Sample code that should cause violation:
```
+/** 
+ * Some class.
+ *
+ * @author John Doe (sample@mail.com)
+ * @version $Id$ 
+ */
```
Correct Javadoc:
```
/**
 * Some class.
 *
 * @author John Doe (sample@mail.com)
 * @version $Id$
 * @since 1.0
+ */
```

**Comment by krzyk** [comment]
@mkordas please remove the extraneous comments (the ones with `//`)

**Comment by mkordas** [comment]
@krzyk comments removed

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by HDouss** [comment]
@krzyk Please assign this to me.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
@mkordas thanks for the ticket, your account was topped for 15 mins, payment 56867598d752f13bfc00010e

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk OK @hdouss please go ahead, this task is yours

**Comment by HDouss** [comment]
@mkordas What's the pattern of the since tag value have to be in general ? I think about `^\\d+(\\.\\d+)+[a-z]?$` which means NUMBER.NUMBER(optionally .NUMBER n another times)(optionnally LETTER). What do you think ?

**Comment by mkordas** [comment]
@HDouss I'd suggest going through release names of all Teamed app releases (easy to get from Git) and making sure that regexp works on them

**Comment by HDouss** [comment]
@mkordas Could you please explain to me how to fetch release names from Git ?

**Comment by HDouss** [comment]
@mkordas Or do you mean Tags ?

**Comment by mkordas** [comment]
@HDouss every release is tagged and we don't use tags for anything else, so `git tag` should do the work... but it doesn't apparently. We used to have tags like e.g. `qulice-0.1`, while on Maven Central it is just `0.1`. So `maven-metadata.xml` might be bit better source of knowledge about all releases that happened in Teamed:
* http://repo1.maven.org/maven2/com/qulice/qulice/maven-metadata.xml
* http://repo1.maven.org/maven2/org/takes/takes/maven-metadata.xml
* http://repo1.maven.org/maven2/com/jcabi/jcabi/maven-metadata.xml
* http://repo1.maven.org/maven2/co/stateful/java-sdk/maven-metadata.xml

Just do simple XPath on those to get the lists. I don't see anything else besides `\d+(\.\d+){1,2}`

**Comment by HDouss** [comment]
@mkordas Ok. I will let it like it is. Qulice is not exclusively intended for teamed projects. The pattern implemented is more general and can accept : 1.0.8, 12.1a or 4.2.1b

**Comment by krzyk** [comment]
@HDouss I would prefer `\d+(\.\d+){1,2}`, or semver (but will allowance of major.minor, with optional patch and labels). This is the most common format in the maven world, I haven't seen much of single letter additions at the end.

**Comment by HDouss** [comment]
@krzyk I have seen the single letter addition for some software releases. Anyway, I suggest to retain semver. So it would be `\d+(\.\d+){1,2}(\.[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?`. What do you think ?

**Comment by krzyk** [comment]
@HDouss OK, let's go with this one

**Comment by HDouss** [comment]
@davvd PR #587 ready and waiting for reviewer assignment since 4 days. This ticket could take more time than expected.

**Comment by krzyk** [comment]
@HDouss you can ask davvd to give you more time (e.g. "need more time"), since the CR was marked with postponed tag, I'm not sure why

**Comment by HDouss** [comment]
@davvd I need more time since you marked the CR with postponed tag.

**Comment by davvd** [comment]
> @davvd PR #587 ready and waiting for reviewer assignment since 4 days. This ticket could take more time than expected.

@hdouss OK, no problem, take your time

**Comment by davvd** [comment]
> @davvd I need more time since you marked the CR with postponed tag.

@hdouss take your time, I am aware that we're waiting here

**Comment by krzyk** [comment]
@dmarkov assign @HDouss please

**Comment by HDouss** [comment]
@krzyk 
>@dmarkov assign @HDouss please

I am already assigned here.

**Comment by krzyk** [comment]
@HDouss but I don't see you in the *Assignee*

**Comment by HDouss** [comment]
@krzyk Pretty weird. I sure I saw myself in the 'Assignee' field before posting my comment. Sorry. Is @dmarkov the one who should assign ?

**Comment by krzyk** [comment]
@HDouss no, here it is @davvd

**Comment by HDouss** [comment]
@krzyk So, you made a mistake.
>@dmarkov assign @HDouss please

**Comment by krzyk** [comment]
@HDouss yep, you are right :)

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk yes, @hdouss is already assigned to this task, please go ahead!

**Comment by HDouss** [comment]
@mkordas PR #587 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss well done!

**Comment by HDouss** [comment]
@davvd Issue closed since 4 days.

**Comment by davvd** [comment]
@hdouss thanks, I just added **30 mins** to your account, payment `75045399`, 97 hours and 19 mins spent. +30 added to your rating, current score is: [+1142](http://www.netbout.com/b/36032?open=rating)

**Comment by davvd** [comment]
> @davvd Issue closed since 4 days.

@hdouss thanks for patience
