### ISSUE TITLE
Dependencies to google-collections and guava-io should be removed

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#552]
In qulice-checkstyle `pom.xml` I can find the following dependencies:
```
        <dependency>
            <!-- Checkstyle is using some classes from this lib -->
            <groupId>com.google.collections</groupId>
            <artifactId>google-collections</artifactId>
            <version>1.0-rc5</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-io</artifactId>
            <version>r03</version>
            <scope>test</scope>
        </dependency>
```
I don't think Checkstyle uses any of these dependencies, they are very old libraries.

Moreover, Guava could be upgraded to 19.0 if possible, currently it is 18.0:
```
       <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by krzyk** [comment]
@mkordas please add also guava-io to the list (we should get rid of it)

**Comment by mkordas** [comment]
@krzyk title and description updated, good catch

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 568399150b9607185a00010c

**Comment by HDouss** [comment]
@krzyk assign this to me please.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please 

@krzyk done. @hdouss the task is yours, please go ahead

**Comment by HDouss** [comment]
@mkordas PR #565 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss looks good, thanks!

**Comment by HDouss** [comment]
@davvd Issue closed.

**Comment by davvd** [comment]
@hdouss I just added **1 hour** to your account, many thanks for your contribution (73592377).. 23 hours and 23 mins spent here. m=1403, that's why a bonus here for fast delivery. +60 added to your rating, at the moment it is: [+594](http://www.netbout.com/b/36032?open=rating)
