### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#553]
There are new versions of following dependencies that we should use:
* jcabi-parent 0.40
* checkstyle 6.14
* xembly 0.21.4

And also remove hardcoded maven-invoker-version in poms (it will be taken from jcabi-parent).

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by HDouss** [comment]
@krzyk seems like hardcoded maven-invoker-version is intended : 
```
<!--
Latest version of the plugin (1.8) is based on Groovy 2.0.1,
which is based on ASM 4.0, while CodeNarc and FindBugs are still using ASM 3.x.
This version mismatch leads to an exception in runtime,
explained in http://stackoverflow.com/questions/11738732/
That's why we downgrade the version here to 1.6, which is
based on Groovy 1.8.6, which is using ASM 3.2.
-->
```

**Comment by HDouss** [comment]
@krzyk I will work on the issue as soon as assigned.

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk done. @hdouss the task is yours, please go ahead

**Comment by HDouss** [comment]
@krzyk I will let  hardcoded maven-invoker version.
>@krzyk seems like hardcoded maven-invoker-version is intended :
```
<!--
Latest version of the plugin (1.8) is based on Groovy 2.0.1,
which is based on ASM 4.0, while CodeNarc and FindBugs are still using ASM 3.x.
This version mismatch leads to an exception in runtime,
explained in http://stackoverflow.com/questions/11738732/
That's why we downgrade the version here to 1.6, which is
based on Groovy 1.8.6, which is using ASM 3.2.
-->
```

**Comment by davvd** [comment]
@krzyk many thanks for the report, I topped your account for 30 mins, transaction 73366181

**Comment by krzyk** [comment]
@HDouss thanks

**Comment by HDouss** [comment]
@davvd Issue closed.

**Comment by davvd** [comment]
@hdouss **45 mins** was added to your account, many thanks for your contribution (payment 73518088)! The task took 45 hours and 36 mins.; the bonus for fast delivery (m=2736); added +45 to your rating, now it is equal to [+496](http://www.netbout.com/b/36032?open=rating)

**Comment by davvd** [comment]
> @davvd Issue closed.

@hdouss thanks
