### ISSUE TITLE
Puzzles in Javadoc for methods with '@Override'

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#555]
If puzzle needs to be added to method with `@Override` natural solution is to create Javadoc like that:

    /**
     * @todo #XXX:30min Here goes puzzle contents.
     */
    @Override
    public void method() {
        // logic
    }

Qulice complains on the above with `First sentence in a comment should start with a capital letter (RegexpMultilineCheck)`.

I don't see anything incorrect in the above as Javadoc parser inherits Javadoc from parent anyway, so no violation should be raised.

**Comment by krzyk** [comment]
@mkordas AFAIR such javadoc would require `{@inheritDoc}` at the beginning to actually inherit the documentation from parent

**Comment by mkordas** [comment]
@krzyk 
From http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html:
> ### Automatic Copying of Method Comments
The Javadoc tool has the ability to copy or "inherit" method comments in classes and interfaces under the following two circumstances. Constructors, fields and nested classes do not inherit doc comments.

> * Automatically inherit comment to fill in missing text - When a main description, or `@return`, `@param` or `@throws` tag is missing from a method comment, the Javadoc tool copies the corresponding main description or tag comment from the method it overrides or implements (if any), according to the algorithm below.
More specifically, when a `@param` tag for a particular parameter is missing, then the comment for that parameter is copied from the method further up the inheritance hierarchy. When a `@throws` tag for a particular exception is missing, the `@throws` tag is copied only if that exception is declared.

> * Explicitly inherit comment with `{@inheritDoc}` tag - Insert the inline tag `{@inheritDoc}` in a method main description or `@return`, `@param` or `@throws` tag comment -- the corresponding inherited main description or tag comment is copied into that spot.

It basically means, that Javadoc is inherited automatically for each section separately.

**Comment by krzyk** [comment]
@mkordas Yes, I saw that docs, and I was under the impression that unknown tag will be treated as a description. But I checked it on a real code and indeed the description is copied even if there is only single `@todo`.

**Comment by krzyk** [comment]
@yegor256 are you OK with adding todos in javadoc of overridden methods (instead of adding them using `//`) as it is in the description?

**Comment by yegor256** [comment]
@krzyk no, I don't like it. overriden methods must **not** have any javadoc blocks. we should use `//`

**Comment by mkordas** [comment]
@yegor256 so maybe we should have check like `NoJavadocForOverriddingMethod`?

**Comment by yegor256** [comment]
@mkordas yes, not a bad idea

**Comment by krzyk** [comment]
@mkordas so maybe close this issue and create a new issue?

**Comment by mkordas** [comment]
@krzyk created new issue #594, thanks
