### ISSUE TITLE
Strict indentation check is wrong

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#556]
We tried to enforce more strict indentation rules in #527 but used `forceStrictCondition` in checkstyles `IndentationCheck` causes problems in following code:
```
   public void view() {
        Arrays.asList(
            new Integer(
                1
            )
        )
    }
```
The above code has correct indentation, but qulice complains, that `Integer` parameter should have same indentation as the `new` keyword, and same for `)` that follows.
Basically it enforces such code:
```
   public void view() {
        Arrays.asList(
            new Integer(
            1
        )
        )
    }
```

Disable `forceStrictCondition`, and write our own `CascadeIndentationCheck` that will do as described in #527:
Make sure each line indentation is either:

1. the same as previous one or less
2. bigger than previous by exactly 4

All other cases must cause a failure.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@mkordas want to continue with this one?

**Comment by mkordas** [comment]
@krzyk I'm busy with 10 other tasks. BTW, can I have more on me especially if I'm not in Qulice team anymore?

**Comment by krzyk** [comment]
@mkordas with manual assignment you can have as much as you can handle :), but you won't get automatically assigned task until you get below your current limit.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by HDouss** [comment]
@krzyk Isn't it a duplicate of #527 ? It seems to me that the two issues are about this behaviour : 
>
1. the same as previous one or less
2. bigger than previous by exactly 4
All other cases must cause a failure.

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk done. @hdouss the task is yours, please go ahead

**Comment by davvd** [comment]
@krzyk many thanks for the report, I topped your account for 30 mins, transaction 73363389

**Comment by krzyk** [comment]
@HDouss yes but #527 was implemented a different closed.  After that it occurred that checkstyle indentation check with forced strict condition is bugged, so we have to do our own (simple one, as in the description) implementation.

**Comment by HDouss** [comment]
@krzyk I understood. What I meant is that the "specs" are the same. I will go for our own implementation.

**Comment by krzyk** [comment]
@HDouss yes, specs are the same

**Comment by HDouss** [comment]
Added PR #559. Exception to the rule : lines inside a comment block.

**Comment by HDouss** [comment]
@krzyk  PR #559 reviewed and merged. Please close the issue.

**Comment by krzyk** [comment]
@HDouss thanks

**Comment by HDouss** [comment]
@davvd Issue closed.

**Comment by davvd** [comment]
@hdouss Many thanks! **38 mins** were added to your account in Transaction ID `73592365` (task took 50 hours and 33 mins); the bonus for fast delivery (m=3033); added +38 to your rating, now it is equal to [+534](http://www.netbout.com/b/36032?open=rating)
