### ISSUE TITLE
setMinimumPriority in SourceValidator is misleading and unnecessary

### ISSUE THREAD

**Issue by prahladyeri** [teamed/qulice#562]
All pmd tests are handled by the `SourceValidator` class and ultimately end up in `validateOne` method which has the following misleading statement:

    factory.setMinimumPriority(RulePriority.valueOf(5));

I don't know what the reasons were for setting a minimum priority of `level 5` for all tests, but this is both misleading and confusing. For one, it isn't working at all. For example, there are tons of rules in the pmd [basic.xml](https://github.com/pmd/pmd/blob/master/pmd-java/src/main/resources/rulesets/java/basic.xml) and some custom rules in our own [ruleset.xml](https://github.com/teamed/qulice/blob/ebf85bd3162241d029b6796da98e91d2d08228cc/qulice-pmd/src/main/resources/com/qulice/pmd/ruleset.xml) that have a priority level of 3 which is below 5, but still they are working.

Secondly, if a validation isn't working, a developer may think that it is because of this set `priority level` which is very misleading.

I hence recommend to remove this priority check if it isn't defeating any other design goals that `qulice-pmd` may have.

**Comment by krzyk** [comment]
@prahladyeri priority in PMD is reversed, rules with priority 1, are the most important, rules with priority 5 are least important (5 is also the lowest level).

**Comment by prahladyeri** [comment]
@krzyk thanks, I wasn't aware of that.
