### ISSUE TITLE
Qulice code contains too much line length suppressions

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#568]
Majority of `// @checkstyle LineLength (x lines)` should be removed from Qulice codebase. They distract code reader forcing to scroll horizontally and give bad example.

Right now there are 21 of them: https://github.com/teamed/qulice/search?utf8=%E2%9C%93&q=%22%40checkstyle+linelength+%28%22
* some are completely obsolete (line is shorter or contains import - long imports should be allowed)
* in most of the remaining cases suppressions were made to not have violations when concatenation strings - but the correct approach is described at http://www.yegor256.com/2014/06/19/avoid-string-concatenation.html

**Comment by krzyk** [comment]
@mkordas let's join it with #572 (but we should move `src/mock/com/qulice/findbugs/BytecodeMocker.java` to `src/java/com/qulice/findbugs/mock/BytecodeMocker.java`)

**Comment by mkordas** [comment]
@krzyk with solution to remove `src/mock` indeed it becomes much simpler. Merged with #572 and closing this one.
