### ISSUE TITLE
UseConcurrentHashMap, AvoidUsingVolatile and DoNotUseThreads PMD rules should be disabled

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#569]
1. UseConcurrentHashMap PMD rule is triggering for every `HashMap` instantiation. `ConcurrentHashMap` has unnecessary memory overhead and it shouldn't be general replacement for `HashMap`. Please see https://ria101.wordpress.com/2011/12/12/concurrenthashmap-avoid-a-common-misuse/

 Especially when `HashMap` is created within a method and isn't returned from it, there's absolutely no point in making it concurrent.

 I'd expect this rule being disabled and all unnecessary usages of `ConcurrentHashMap` like e.g. in https://github.com/teamed/qulice/blob/f1842e14d8a5cb92efd48befd62dc3dc4ac9d00a/qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java#L70 should be replaced with `HashMap` or equivalent.

1. Disable AvoidUsingVolatile rule, as it makes sense only for Java 1.4 projects, where `volatile` was generally broken and semantics changed in Java 5.

1. Disable DoNotUseThreads rule, as it makes sense only in J2EE environment (according to PMD docs: The J2EE specification explicitly forbids the use of threads.)

<hr id='w'>

**Comment by krzyk** [comment]
@yegor256 Could you take a look at this one? I don't know why `ConcurrentHashMap` was enforced in the first place.

**Comment by yegor256** [comment]
@krzyk well, it's coming from PMD and they, I believe, have their reasons for that. Let's investigate. If you really think that PMD is wrong, let's remove this rule.

**Comment by mkordas** [comment]
@yegor256 even in PMD they [exclude this check](https://github.com/pmd/pmd/blob/9d350e6f780569ef660aca43e3935237abb81bd9/pmd-core/src/main/resources/rulesets/internal/dogfood.xml#L56) for their code. Description of the rule:
> If you run in Java5 or newer and have concurrent access, you should use the ConcurrentHashMap implementation

It was created in commit https://github.com/adangel/pmd/commit/1d7d5e64743d7e3a5640ea632e0163a6518c2c6a just to help migrating from Java 1.4 and older ones to promote `ConcurrentHashMap`, but straight away in `controversial` ruleset. There is issue open to remove it: https://sourceforge.net/p/pmd/bugs/1336/

**Comment by yegor256** [comment]
@krzyk I'm not against removing of this rule

**Comment by krzyk** [comment]
@yegor256 thanks

**Comment by krzyk** [comment]
@yegor256 what do you think about removing also `DoNotUseThreads` in this issue?
This rule makes sense only in J2EE environment. (according to PMD docs: *The J2EE specification explicitly forbids the use of threads.*)

**Comment by yegor256** [comment]
@krzyk yes, let's remove it, I agree

**Comment by krzyk** [comment]
@mkordas please update the description with removal of DoNotUseThreads

**Comment by mkordas** [comment]
@krzyk DoNotUseThreads added to description

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
@mkordas thanks for tis bug, I topped your account for 15 mins, transaction `568fb5039cdd9a33a20002ff`

**Comment by mkordas** [comment]
@krzyk as agreed in other ticket, I've added also disabling `AvoidUsingVolatile` here

**Comment by krzyk** [comment]
@davvd assign @krzyk please

**Comment by krzyk** [comment]
@davvd please see PR #602

**Comment by davvd** [comment]
> @davvd assign @krzyk please

@krzyk done. @krzyk the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd please see PR #602 

@krzyk thanks, will take a look

**Comment by krzyk** [comment]
@mkordas changes have been merged to master, please close this issue

**Comment by davvd** [comment]
@mkordas the code made here contains a puzzle `569-cd6c2a10`/#609, which will be resolved soon

**Comment by mkordas** [comment]
@krzyk thanks

**Comment by davvd** [comment]
@krzyk Thank you, I have added **45 mins** to your account in payment/transaction "`74523426`", time consumed: 27 hours and 56 mins. the bonus for fast delivery (m=1676). +45 to your rating, your total score is [+3502](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@mkordas last puzzled solved `569-cd6c2a10`/#609
