### ISSUE TITLE
Only ArrayList is checked to have initial capacity

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#574]
We have the following custom check:
```xml
    <module name="com.qulice.checkstyle.ConditionalRegexpMultilineCheck">
        <property name="condition" value="^import java\.util\.ArrayList;$"/>
        <property name="format" value="new ArrayList(?:&lt;.*?&gt;)?\(\)"/>
        <property name="message"
                  value="ArrayList should be initialized with a size parameter"/>
        <property name="fileExtensions" value="java"/>
    </module>
```
It checks only `ArrayList` to have proper initial capacity. Checks for at least these classes are missing:
* `java.util.HashMap`
* `java.util.TreeMap`
* `java.util.HashSet`
* `java.util.LinkedHashSet`

**Comment by krzyk** [comment]
@mkordas I'm not convinced that this would be a good idea. In case of `ArrayLists` you have a good alternative that can grow without performance impact (`LinkedList`) - we don't always know how much data we will store inside collection, and adding excludes is not nice.
What structure we could use for such case for `Map` or a `Set` if we don't want to add an exclude?

**Comment by mkordas** [comment]
@krzyk we could use e.g. `Maps.newHashMap()`. At least it is the current workaround in Qulice: https://github.com/teamed/qulice/search?q=newarraylist

**Comment by krzyk** [comment]
@mkordas but it still creates `HashMap`, so we don't gain anything by it, only force ourselves to use guava where it is not needed. We would need Map implementation that doesn't have performance impact while growing, which I don't see in JDK.

**Comment by mkordas** [comment]
@krzyk right, I see your point, fully agreed. Should we do anything about `Lists.newArrayList()` or it's fine to leave it as workaround?

**Comment by krzyk** [comment]
@mkordas Let's leave it, it is only in 4 places, it could be removed if you had a general clean up issue with more work in it.

**Comment by mkordas** [comment]
@krzyk what I meant is extending current check to apply also to Guava declaration. I think this is enough work for the dedicated issue, especially if these 4 occurrences will be fixed there too.

**Comment by krzyk** [comment]
@mkordas yes, that makes sense

**Comment by mkordas** [comment]
@krzyk closing this one, let's continue in #584
