### ISSUE TITLE
Check to prohibit just '{@inheritDoc}'

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#575]
Javadoc comments containing only the `{@inheritDoc}` tag are obsolete. Javadoc tool automatically copies the super class comment if no comment is present, so comment containing only an `{@inheritDoc}`adds nothing and should be prohibited.

We even have 4 such cases in Qulice itself: https://github.com/teamed/qulice/search?utf8=%E2%9C%93&q=inheritDoc&type=Code
```java
    /**
     * {@inheritDoc}
     */
    @Override
    void method() {
        doSomething();
    }
```

I'd expect violation for the above code.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `568f671a7e55c12b1b00009f`

**Comment by krzyk** [comment]
@mkordas this is now covered by `NoJavadocForOverriddenMethodsCheck`, so I think it can be closed

**Comment by mkordas** [comment]
@krzyk you are right, thanks
