### ISSUE TITLE
No check to ensure empty lines are present where needed

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#576]
Right now the following code passes Qulice check:

``` java
@Override
public void start() {
}
@Override
public void stop() {
}
```

I'd expect violation about missing newline between methods, but `EmptyLineSeparator` Checkstyle check that was created for that purpose is missing from the config.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by davvd** [comment]
@mkordas thanks for this report, I added 15 mins to your account, in transaction `568d16ae293a7942d800037d`

**Comment by krzyk** [comment]
@davvd this is not posptoned

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk right, I added "urgent" label

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk sure, thanks, I removed "postponed" tags to it

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I removed "urgent" tags to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/576#issuecomment-408585021))

@krzyk Thanks for your contribution, @mkordas[/z](https://www.0crat.com/u/mkordas)! If you would be a member of [the project](https://www.0crat.com/p/C3T49A35L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/576#issuecomment-408585021))

@krzyk The job [#576](https://github.com/teamed/qulice/issues/576) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/2090563715); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@mkordas changes have been merged to master in #922 please close this issue

**Comment by krzyk** [comment]
@mkordas ping

**Comment by mkordas** [comment]
@krzyk looks good, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#576](https://github.com/teamed/qulice/issues/576) is now out of scope
