### ISSUE TITLE
Let's eat our own dogfood

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#577]
Before merging each code we should run newly built qulice against qulice codebase.
This will allow us to catch errors in our checks earlier.

We should have another travis build (only travis) that will do the validations using newly built plugin - it is because sometimes we introduce incompatible changes that could fail on our current codebase, but we can't updated it because it will fail on the previous qulice plugin.
So we should have a build that will be just an information for us, what new violations are being detected. This should allow us to fix invalid ones.

Options how to do it:
1.
- `mvn clean install`
- `mvn com.qulice:qulice-maven-plugin:1.0-SNAPSHOT:check -Pqulice` (here we will probably need to add excludes e.g. `-Dqulice.excludes="xml:.*,checkstyle:.*,pmd:.*/src/test/resources/.*"`)

2.
- add option to define qulice version from command line (by using `<properties>` tag)
- `mvn clean install`
- `mvn versions:set "-DnewVersion=1.1"`
- `mvn clean install -Pqulice -Dqulice.version=1.0-SNAPSHOT`

3. Any other ideas

For the 1 and 2, we should also make sure that we run the build for all the modules, so some shell magic will be needed to enter each directory and build given plugin.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by mkordas** [comment]
@krzyk how would you configure exclusions for such run?

**Comment by krzyk** [comment]
@mkordas if they are required (shouldn't, if we add new check we should fix problems that it causes in qulice using e.g. puzzles) it reads excludes from the pom.xml files (and from the code).

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
@krzyk thanks for the ticket, your account was topped for 30 mins, payment 73942602

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by krzyk** [comment]
@mkordas I've updated the description, would you like to work on this?

**Comment by mkordas** [comment]
@krzyk first we need to update Qulice to 0.15.4 for our code, there are many violations. Should I raise issue for that?

**Comment by krzyk** [comment]
@mkordas I don't think we need to upgrade for this issue specifically, this will be just a build informing us of the violations.
But yes, there are quite a lot of changes needed for the new qulice, so an issue will be needed.

**Comment by mkordas** [comment]
@krzyk OK, I'll submit an issue with some proposals how to fix missing since tag. So you propose to allow failing Travis build for some time and red mark on each commit?

**Comment by krzyk** [comment]
@mkordas we won't be able to always have a green build, e.g. when we add a code that reverses the previous check
A red flag is OK, if I can go and see that the only failing one is the "dogfooded" qulice.

In the future if the newly added rule is not conflicting with previous qulice, we will fix the code during the implementation of the check (or add a todo if it is more work).

**Comment by krzyk** [comment]
@mkordas are you interested?

**Comment by krzyk** [comment]
@mkordas ping

**Comment by mkordas** [comment]
@krzyk because of @davvd being so slow I'll ask for an assignment only when my PR will be ready

**Comment by krzyk** [comment]
@mkordas yes, he is a pain, I'm just asking if I should look for someone else :)

**Comment by mkordas** [comment]
@krzyk I'll give a try :)

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd assign @mkordas please 

@krzyk OK @mkordas please proceed, this task is yours

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by mkordas** [comment]
@davvd please see PR #650

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by davvd** [comment]
> @davvd please see PR #650

@mkordas will check it soon, thanks

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by krzyk** [comment]
@mkordas does the task appear in your agenda? I don't see you assigned in github, but David confirmed it.

**Comment by mkordas** [comment]
@krzyk yes, I see it. Can you close the issue?

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
> @davvd assign @mkordas please 

@krzyk yes, @mkordas is already assigned to this task, please go ahead!

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
@mkordas **1 hour** sent to your balance (ID `56ab34d415431a575200001a`), many thanks! It took zero.. there is a bonus for fast delivery (m=0). +60 added to your rating, current score is: [+4108](http://www.netbout.com/b/36080?open=rating)
