### ISSUE TITLE
Page 'qulice.com' is currently broken

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#578]
Go to http://www.qulice.com/index.html and see how page looks like:
![screenshot from 2016-01-01 16 46 37](https://cloud.githubusercontent.com/assets/5467276/12071340/459f0dba-b0a7-11e5-8aa3-985c57c2ad9d.png)

We need to fix this and root cause should be identified.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag "bug" added

**Comment by davvd** [comment]
@mkordas thanks a lot for reporting, **15 mins** added to your acc, pmt ID `568cca1a133ed7461c00015c`

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk OK @hdouss please proceed, this task is yours

**Comment by HDouss** [comment]
@mkordas Are the site sources related to the project ?

**Comment by mkordas** [comment]
@HDouss sure, look at `vm` files and `gh-pages` branch

**Comment by HDouss** [comment]
@mkordas Thanks !

**Comment by HDouss** [comment]
@yegor256 Seems your last commit cadf2a75bfc0e9bda2909dfe6685596b7fe831ce has many problems. I will revoke the changes in the PR.

**Comment by HDouss** [comment]
@yegor256 Please correct me if I am wrong.

**Comment by HDouss** [comment]
@davvd Need more time here. The bug is probably not in qulice project itself.

**Comment by davvd** [comment]
> @davvd Need more time here. The bug is probably not in qulice project itself.

@hdouss OK, no problem, take your time

**Comment by HDouss** [comment]
@mkordas PR #605 merged. Please close the issue.

**Comment by krzyk** [comment]
@HDouss we will need to wait for release, which is still in progress (see http://www.rultor.com/t/6325-172756347)

**Comment by mkordas** [comment]
@HDouss @krzyk release is done and page looks good, thanks!

**Comment by krzyk** [comment]
@mkordas well, actually the page should say `0.15.3`, but it shows `0.15.2`

**Comment by mkordas** [comment]
@krzyk reopening
@HDouss please take a look at http://www.qulice.com/

**Comment by krzyk** [comment]
@HDouss new version was created in `/qulice` directory, but the links in `/qulice/index.html` lead wrong directory for qulice-maven-plugin

**Comment by HDouss** [comment]
@mkordas PR #629 should resolve this issue.

**Comment by krzyk** [comment]
@HDouss @mkordas we'll see result here http://www.rultor.com/t/6325-173171992 (it usually takes about 1hr)

**Comment by HDouss** [comment]
@krzyk @mkordas All seems [OK](http://www.qulice.com/)

**Comment by HDouss** [comment]
@mkordas PR #629 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss page looks ideal right now :)

**Comment by davvd** [comment]
@hdouss thanks, paid, **30 mins** to your account, payment ID is `75231576`, task took 313 hours and 47 mins to complete. +30 to your rating, your total score is [+1382](http://www.netbout.com/b/36032?open=rating)
