### ISSUE TITLE
Checkstyle and PMD report errors with incorrect path

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#579]
Both Checkstyle and PMD are reporting errors with leading slash, which is not correct.
More over if run on multimodule project they don't include the module directory in the path.

Example:
```
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] /src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java[117]: Indentation (16) must be same or less than previous line (8), or bigger by exactly 4 (CascadeIndentationCheck)
[ERROR] /src/main/java/com/qulice/checkstyle/CheckstyleValidator.java[119]: Indentation (16) must be same or less than previous line (8), or bigger by exactly 4 (CascadeIndentationCheck)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
```

In the above example there shouldn't be a leading slash and the above classpath should show the path relative to the current directory (so module names should be included in the path).

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
@krzyk thanks for the report, I topped your acc for 30 mins, payment ID `73865577`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by krzyk** [comment]
@krzyk this will be handled by #61 and following todos
