### ISSUE TITLE
Configure pdd and est in travis and rultor

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#581]
1. Current travis build don't check if puzzles created are correct (using `pdd` tool), same for estimates (using `est` tool).
2. Moreover rultor build has `pdd` checks, but doesn't have `est` checks, this also has to be fixed (by adding `est --dir=est --file=/dev/null`.

**Comment by mkordas** [comment]
@krzyk please assign me when it will be valid bug

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk yep, done. @mkordas it is your task now

**Comment by davvd** [comment]
@krzyk many thanks, **30 mins** added to your acc for reporting this bug, pmt ID `73861370`

**Comment by mkordas** [comment]
@krzyk merged in #588, can you close issue?

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
@mkordas paid, thanks, added **38 mins** to your account, payment `568f9525d456112c5500016d`, 67 hours and 26 mins was spent. m=4046, that's why a bonus here for fast delivery. added +38 to your rating, now it is equal to [+1587](http://www.netbout.com/b/36080?open=rating)
