### ISSUE TITLE
Enforce Qulice 0.15 over entire code

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#582]
Let's update to the Qulice 0.15 when it will become available. It is not 100% straightforward update, as e.g. new check for indentation was introduced.

I'd expect Qulice's code being checked by Qulice 0.15 without any additional exclusions - all violations should be fixed.

**Comment by krzyk** [comment]
@mkordas let's wait for 0.15 (which should be here any day now) and we'll do update to that version

**Comment by mkordas** [comment]
@krzyk OK, changed descripion

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag "bug" added

**Comment by davvd** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 56939510e9f0bb6f17000061

**Comment by krzyk** [comment]
@davvd assign @krzyk please

**Comment by krzyk** [comment]
@davvd please see PR #606

**Comment by davvd** [comment]
> @davvd assign @krzyk please

@krzyk OK @krzyk please start, the task is yours

**Comment by davvd** [comment]
> @davvd please see PR #606 

@krzyk thank you, I will check it

**Comment by krzyk** [comment]
@mkordas changes have been merged, please close this issue

**Comment by mkordas** [comment]
@krzyk thank you

**Comment by davvd** [comment]
@krzyk done, I added **1 hour** in payment `74566872`, 22 hours and 50 mins spent to complete this; the bonus for fast delivery (m=1370); +60 to your rating, your total score is [+3464](http://www.netbout.com/b/35035?open=rating)
