### ISSUE TITLE
Bump up year in headers

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#583]
We have year 2016 already, so all occurrences of `2015` in licenses and headers should be bumped up.

Also all occurrences of `2014` should be reviewed. E.g. for entire year we had outdated license in [`checks.xml`](https://github.com/teamed/qulice/blob/50b833d4c233ace0936009e4f0c313909f353ce7/qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml#L7).

There should be test added to check whether copyright is 2011-current year. It should check at least `.java`, `.xml`, `.vm`, `.groovy`, `.txt`, `.fml`, `.properties` extensions.

**Comment by yegor256** [comment]
@krzyk it looks like a minor/cosmetic issue, unless we create an automated check inside pom.xml, to verify the presence of `2013-2016` in all our files.

**Comment by krzyk** [comment]
@mkordas please update the description to add a test for such case. We should always check that copyright is in the range 2011-current year. This test should be applied to (at a minimum) `.java`, `.xml`, `.vm`, `.groovy`, `.txt`, `.fml`, `.properties` - we could add more text file types here.

Another problem is that the LICENSE.txt is updated, but checks.xml doesn't use that, but should, I'm not sure if checkstyle header check is smart enough to look for header deeper in the file.

**Comment by mkordas** [comment]
@krzyk description updated. I don't think Checkstyle Header check is smart enough to check XML files. I think we need to make new check just for XMLs in Qulice. Would it be in scope of this issue?

**Comment by krzyk** [comment]
@mkordas no, I think that smart License check would be another task, that could be later on used in projects using qulice

**Comment by mkordas** [comment]
@krzyk sure, I'll submit issue for that. Do you think we need just one custom smart license check for every type of file? Or maybe we should keep using Checkstyle for non-XML files and create our own `XmlLicesneCheck`?

**Comment by krzyk** [comment]
@mkordas We would need a check for files that don't allow header in the beginning (or are just not caught by checkstyle header check), so we have xml (including .fml), vm, and properties. So not only xml check. And I hope that groovy can be checked by standard checkstyle, if we update extensions.

**Comment by yegor256** [comment]
@krzyk I think, just a `grep` is enough, see how I've done it in a JS project: https://github.com/yegor256/tacit/commit/1618dbdefd417b9be5d9acd6322a442713c10c24

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag "bug" added

**Comment by davvd** [comment]
@mkordas thanks a lot for reporting, **15 mins** added to your acc, pmt ID `568a700ec04ee048f60003c4`

**Comment by krzyk** [comment]
@davvd assign @krzyk please

**Comment by krzyk** [comment]
@davvd please see PR #624

**Comment by davvd** [comment]
> @davvd assign @krzyk please

@krzyk OK @krzyk please go ahead, this task is yours

**Comment by davvd** [comment]
> @davvd please see PR #624 

@krzyk will check it soon, thanks

**Comment by krzyk** [comment]
@mkordas changes have been merged to master, please close this issue

**Comment by mkordas** [comment]
@krzyk thank you

**Comment by davvd** [comment]
@krzyk I just added **1 hour** to your account, many thanks for your contribution (75129265).. 23 hours and 39 mins spent here... the bonus for fast delivery (m=1419)... +60 to your rating, your total score is [+3838](http://www.netbout.com/b/35035?open=rating)

**Comment by vkuchyn** [comment]
@krzyk I have similar task in [rultor project](https://github.com/yegor256/rultor/issues/981). I tried your decision and have a question about `years.sh`
If to change year of LICENSE.txt to, for example, 2011-2015 and run ./years.sh - no reaction. Is it bug or feature? 
There is `--exclude ".*"`that excludes all files in root folder. IF to remove it - we'll get violations in `*.iml;*.ipr;*.iws`files and files I broke to test if it's work. 
Can you explain please, what for is exclude `".*"`?

**Comment by krzyk** [comment]
@vkuchyn this excludes only files that name starts with a dot `.` only.
When I change date in the LICENSE.txt I get violation in it.
Also I get violations for idea files without changing the years.sh (this is a feature, as we don't have those in rultor or in travis)

**Comment by vkuchyn** [comment]
@krzyk problem is that I don't. Suppose because of different environments. 
Need your consultation - what if change approach and to do this feature not with black-list as it was done (grep finds all files that doesn't contain valid years but we need to exclude not necessary files), but white-list.
Please, see my [comment ](https://github.com/yegor256/rultor/issues/981#issuecomment-189681250) and say what you think.

**Comment by krzyk** [comment]
@vkuchyn white list is problematic, because it might cause that we miss some file extension.
If you grep doesn't handle exclude the way mine does, you could also use "double grep", so the first grep is withou the excludes, and the second one will do e.g. `egrep -v "^\..*"`

**Comment by vkuchyn** [comment]
@krzyk take a look at comment - there is sample of grep code. Idea - chek only those files that has copyright pattern
