### ISSUE TITLE
incorrect indentation level for a closing bracket 

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#589]
according http://www.yegor256.com/2014/10/23/paired-brackets-notation.html
>the line with a closing bracket should start at the same indentation level as the line with its opening pair.

qulice reports 
``')' have incorrect indentation level 4, expected level should be 8 (IndentationCheck)`
on the valid code
```
    @Override
    @RetryOnFailure(
        verbose = false, attempts = Tv.TWENTY,
        delay = Tv.FIVE, unit = TimeUnit.SECONDS
    )
    public String name() throws IOException {
        return this.origin.name();
    }
```
but the invalid formatting passed Qulice checks
```
    @Override
    @RetryOnFailure(
        verbose = false, attempts = Tv.TWENTY,
        delay = Tv.FIVE, unit = TimeUnit.SECONDS
        )
    public String name() throws IOException {
        return this.origin.name();
    }
```

**Comment by mkordas** [comment]
@dmzaytsev I will fix that in #411, just waiting for Checkstyle 6.15 release

**Comment by krzyk** [comment]
@dmzaytsev looks like duplicate of #411

**Comment by dmzaytsev** [comment]
@krzyk yep, I'm closing it
@mkordas thanks
