### ISSUE TITLE
pom.xml:379-380: Fix all FindBugs problems reported...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#590]
Puzzle `370-69914ea1` in `qulice-maven-plugin/pom.xml:379-380` has to be resolved: Fix all FindBugs problems reported in qulice-maven-plugin and remove the FindBugs exclude below.... The puzzle was created by krzyk on 1-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by krzyk** [comment]
@davvd assign @krzyk pls

**Comment by krzyk** [comment]
@davvd please see PR #600

**Comment by davvd** [comment]
> @davvd assign @krzyk pls

@krzyk OK @krzyk please start, the task is yours

**Comment by davvd** [comment]
> @davvd please see PR #600 

@krzyk I will take a look, thanks

**Comment by davvd** [comment]
@krzyk The issue should be closed..

**Comment by davvd** [comment]
@krzyk Many thanks! **45 mins** were added to your account in Transaction ID `74566859` (task took 47 hours and 15 mins). there is a bonus for fast delivery (m=2835). +45 added to your rating, current score is: [+3404](http://www.netbout.com/b/35035?open=rating)

**Comment by caarlos0** [comment]
@davvd done

**Comment by davvd** [comment]
> @davvd done

@caarlos0 thank you
