### ISSUE TITLE
Line length check doesn't work for javadoc tags

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#592]
When I create a class with following javadoc:
```
/**
 * Integration test case for all checkstyle checks.
 * @author Yegor Bugayenko (yegor@tpc2.com)
 * @version $Id$
 * @todo #123:30min Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test
 */
```

LineLength check doesn't fail, but it should, we ignore line length on every line where there is a javadoc tag.

Please fix it to check also javadoc tag lines.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk done. @mkordas you are assigned to this task. please proceed...

**Comment by mkordas** [comment]
@davvd please see  #592

**Comment by davvd** [comment]
> @davvd please see  #597

@mkordas will take a look, thanks

**Comment by mkordas** [comment]
@krzyk solved in #597, can you close the issue?

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
@mkordas Much appreciated! **38 mins** was added to your account, payment ID `5694c3783715622d5a00019b`, time spent is 69 hours and 49 mins

m=4189, that's why a bonus here for fast delivery

added +38 to your rating, now it is equal to [+2299](http://www.netbout.com/b/36080?open=rating)

**Comment by krzyk** [comment]
@yegor256 I didn't get *30mins* for reporting this issue

**Comment by yegor256** [comment]
@davvd pls add extra 30 mins to @krzyk

**Comment by davvd** [comment]
> @davvd pls add extra 30 mins to @krzyk 

@yegor256 I've sent 30 mins extra to @krzyk in transaction ID "78701774"
