### ISSUE TITLE
Allow 'id' as a variable name

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#593]
Currently Qulice prohibits variable named just 'id', e.g.
```java
final int id = readAttribute("id");
```
I don't see anything bad in using `id` as variable name, it is very common and widely accepted.

To overcome it, people use a lot of creativity. I've seen variables named like:
* `ide`
* `ident`
* `identifier`
* `attrid`
* `attribute`
* `name`
* `xid`

and so on, instead of simple `id`.

I'd expect `id` to be allowed as final/non-final local variable names, method parameters, fields and constants (`ID`). It should be prohibited for catch parameters.

**Comment by krzyk** [comment]
@yegor256 please take a look at this, are you good with the change?

**Comment by yegor256** [comment]
@krzyk make sense, I second this

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@mkordas thanks for the ticket, your account was topped for 15 mins, payment 56936d48d7717a6a38000067

**Comment by krzyk** [comment]
@jrdalpra can you work on this?

**Comment by jrdalpra** [comment]
@krzyk there's any test case to prove the issue?

**Comment by jrdalpra** [comment]
@mkordas which tool is complaining about the attribute's name?

**Comment by krzyk** [comment]
@mkordas you have to create a testcase to prove that it is no longer occurring after the changes

**Comment by krzyk** [comment]
@davvd assign @jrdalpra please

**Comment by mkordas** [comment]
@jrdalpra it's Checkstyle complaining

**Comment by jrdalpra** [comment]
@krzyk @mkordas the problem resides there https://github.com/teamed/qulice/blob/master/qulice-checkstyle/src/main/resources/com/qulice/checkstyle/checks.xml#L312-L315

Can I just pull the changes without a test case and create a puzzle for that test case?

Thanks.

**Comment by krzyk** [comment]
@jrdalpra without a test case we won't know if it reallyw works

**Comment by davvd** [comment]
> @davvd assign @jrdalpra please

@krzyk done. @jrdalpra the task is yours, please go ahead

**Comment by jrdalpra** [comment]
@krzyk @davvd there's a PR #615 ready to review. thanks.

**Comment by jrdalpra** [comment]
@mkordas can you close this issue? Thanks.

**Comment by mkordas** [comment]
@jrdalpra you need to refer to pull request in at least one message

**Comment by jrdalpra** [comment]
Fixed at PR #621

**Comment by mkordas** [comment]
@jrdalpra thanks!

**Comment by davvd** [comment]
@jrdalpra Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-91W621665H2212107`, total time was 193 hours and 17 mins; +30 added to your rating, at the moment it is: [+278](http://www.netbout.com/b/36044?open=rating)
