### ISSUE TITLE
Implement check to prohibit Javadoc in methods with '@Override'

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#594]
As agreed in #555 Javadocs in methods annotated with '@Override' should be prohibited. It's because users may have a different understanding of your method based on whether they examine the method in the supertype or the subtype and it may cause confusion.

There's implicit automatic Javadoc inheritance so also putting just `{@inheritDoc}` would be obsolete.

The check could be named e.g. `NoJavadocForOverrideMethods`.

Please do not forget to add various tests for different possible locations of Javadoc.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `5693b8e5e9f0bb7909000058`

**Comment by krzyk** [comment]
@HDouss want to try this one?

**Comment by HDouss** [comment]
@krzyk Yes please.

**Comment by krzyk** [comment]
@davvd please assign @HDouss

**Comment by davvd** [comment]
> @davvd please assign @HDouss 

@krzyk OK @hdouss please proceed, this task is yours

**Comment by HDouss** [comment]
@mkordas If I understood well, the check should also prohibit `{@inheritDoc}`, right ?

**Comment by mkordas** [comment]
@HDouss rigt

**Comment by HDouss** [comment]
@mkordas Thanks. Done in PR #636.

**Comment by HDouss** [comment]
@mkordas PR #636 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss thx

**Comment by davvd** [comment]
@hdouss Thanks for your contribution, **30 mins** was added to your account, payment ID is `75677168`, 90 hours and 12 mins spent total. +30 added to your rating, at the moment it is: [+1510](http://www.netbout.com/b/36032?open=rating)
