### ISSUE TITLE
NonStaticMethodCheck complains about overriden methods

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#595]
NonStaticMethodCheck complains that an overridden method doesn't reference `this`, which is perfectly fine in most cases.
Please fix this check to ignore overridden methods.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@mkordas would you like to take this?

**Comment by mkordas** [comment]
@krzyk sure, please assign me

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk OK @mkordas please go ahead, this task is yours

**Comment by mkordas** [comment]
@davvd @krzyk please see PR #598

**Comment by davvd** [comment]
> @davvd @krzyk please see PR #598

@mkordas will check it soon, thanks

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by krzyk** [comment]
@yegor256 @davvd didn't add a bug reporting bonus here

**Comment by mkordas** [comment]
@davvd please see PR #610

**Comment by davvd** [comment]
@mkordas thank you, added **30 mins** to your acc, payment num is `56960636a4221961ad00004d`, 73 hours and 1 min spent in total to complete. +30 added to your rating, current score is: [+2389](http://www.netbout.com/b/36080?open=rating)

**Comment by krzyk** [comment]
@yegor256 here also, I didn't get *30mins* for reporting this issue

**Comment by krzyk** [comment]
@yegor256 I didn't get *30mins* bonus for reporting this issue

**Comment by yegor256** [comment]
@davvd pls add extra 30 mins to @krzyk

**Comment by krzyk** [comment]
@yegor256 it didn't work, could you try again?

**Comment by yegor256** [comment]
@krzyk this ticket is already out of management scope (too old). mention this problem in some other ticket (currently open) and we'll pay there. make sure you reference this one.
