### ISSUE TITLE
NonStaticMethodCheck complains about abstract method and native method

### ISSUE THREAD

**Issue by super132** [teamed/qulice#603]
After upgrading to `0.15`, NonStaticMethodCheck complains an abstract method from abstract class and JNI methods should be static, which they should not be in this use case. Let's ignore abstract and native methods from NonStaticMethodCheck.

**Comment by mkordas** [comment]
@krzyk please assign me to this one

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk OK @mkordas please go ahead, this task is yours

**Comment by davvd** [comment]
@super132 many thanks for the bug report, I added 15 mins to your acc, transaction `AP-2KV09524YE725893J`

**Comment by mkordas** [comment]
@davvd please see PR #610

**Comment by davvd** [comment]
> @davvd please see PR #610 

@mkordas thanks, I'll take a look

**Comment by mkordas** [comment]
@super132 this was done in #610, can you close the issue?

**Comment by mkordas** [comment]
@super132 ping

**Comment by super132** [comment]
@mkordas thanks.

**Comment by davvd** [comment]
@mkordas thanks, I just added **45 mins** to your account, payment `569ca97c32cc4f00c6000011`, 46 hours and 26 mins spent

the bonus for fast delivery (m=2786)

+45 added to your rating, current score is: [+2739](http://www.netbout.com/b/36080?open=rating)

**Comment by longtimeago** [comment]
@krzyk could you, please, release a new version with this fix?

**Comment by krzyk** [comment]
@longtimeago it is in 0.15.3 and 0.15.4

**Comment by longtimeago** [comment]
@krzyk cool, thanks!
