### ISSUE TITLE
PMDDisabledRulesTest.java:44-47: When new version of Qulice...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#609]
Puzzle `569-cd6c2a10` in `qulice-pmd/src/test/java/com/qulice/pmd/PMDDisabledRulesTest.java:44-47` has to be resolved: When new version of Qulice is released (with disabled rules: UseConcurrentHashMap, DoNotUseThreads and AvoidUsingVolatile) remove suppression of given rules and remove unneeded usages of ConcurrentMap and ConcurrentHashMap.... The puzzle was created by krzyk on 10-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd assign @mkordas please

**Comment by mkordas** [comment]
@krzyk can you trigger release 0.15.2 so that I can continue with this one?

**Comment by davvd** [comment]
> @davvd assign @mkordas please

@krzyk done. @mkordas you are assigned to this task. please proceed...

**Comment by mkordas** [comment]
@krzyk is it possible to do release today?

**Comment by krzyk** [comment]
@mkordas 0.15.2 is ready

**Comment by mkordas** [comment]
@krzyk thanks a lot!

**Comment by mkordas** [comment]
@davvd please see PR #614

**Comment by davvd** [comment]
> @davvd please see PR #614

@mkordas thank you, I will check it

**Comment by davvd** [comment]
@krzyk Done, thanks all, closing..

**Comment by davvd** [comment]
@mkordas Much obliged! I have added **30 mins** to your account in payment "569ca98909d92000ac0000b5", 23 hours and 34 mins spent; m=1414, that's why a bonus here for fast delivery; +30 added to your rating, current score is: [+2769](http://www.netbout.com/b/36080?open=rating)
