### ISSUE TITLE
logging mechanism should be improved and unified

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#61]
_migrated from Trac, where originally posted by **dpetruha** on 24-Nov-2011 10:03am_

a) to get resource validators from ValidatorsProvider (method to get such validators will be added in #44)
b) if a) returns any resource validators then get list of files to be checked (should be all files of the target project under src folder).
c) iterate over that list of files then iterate over each resource validator returned from a) and send current file to the current resource validator for validation (i.e. 

call ResourceValidator.validate method).
d) If ResourceValidator.validate returns ResourceValidationResult that is failed then log returned error with
com.ymock.util.Logger.error()
specifying validation resource (path should be relative to
this.session.getExecutionRootDirectory()), line number if present in validation result, error message if present in validation result.
e) after validation of all files is over if any validation failed throw MojoFailureException

**Comment by krzyk** [comment]
@yegor256 is this still valid?

**Comment by yegor256** [comment]
@krzyk up to you. I think, the idea is interesting. you decide.

**Comment by krzyk** [comment]
@davvd it is a valid bug

**Comment by davvd** [comment]
> @davvd it is a valid bug

@krzyk added "bug" tag to this issue

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
@yegor256 thank you for reporting this, I added 15 mins to your acc, transaction `000-1734463e`

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by davvd** [comment]
> @davvd assign @krzyk

@krzyk OK @krzyk please go ahead, this task is yours

**Comment by krzyk** [comment]
@yegor256 initial batch has been merged to master (checkstyle uses new logging, others are in todos), please close this issue if it is OK

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by davvd** [comment]
@yegor256 5 puzzles were created here: `61-61fa67ee`, `61-1d39a5c7`, `61-832eca62`/#740, `61-1e86e587`, `61-654de8aa`

**Comment by davvd** [comment]
@krzyk I just added **45 mins** to your account, many thanks for your contribution (79287961).. 45 hours and 39 mins spent here; there is a bonus for fast delivery (m=2739); +45 added to your rating, current score is: [+5930](http://www.netbout.com/b/35035?open=rating)

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#1127](https://github.com/yegor256/qulice/issues/1127) is still not solved.
