### ISSUE TITLE
QulicePlugin.java:47-48: Design validator classes for Gradle....

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#612]
Puzzle `339-f214ff2b` in `qulice-gradle-plugin/src/main/java/com/qulice/gradle/QulicePlugin.java:47-48` has to be resolved: Design validator classes for Gradle. And remove the NonStaticMethod exclude below.... The puzzle was created by krzyk on 11-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk someone else will help in this task, no problem at all

**Comment by davvd** [comment]
@krzyk Closing..
