### ISSUE TITLE
findbugs filters are broken

### ISSUE THREAD

**Issue by exper0** [teamed/qulice#618]
I tried to enable findbugs for Netbout - and found that exclude filters don't work. The only valid filter is regular expression that match empty string, for example `^$`. Here is actual example from netbout pom.xml:

                        <groupId>com.qulice</groupId>
                        <artifactId>qulice-maven-plugin</artifactId>
                        <configuration>
                            <excludes>
                                
                                <exclude>findbugs:^$</exclude>
                            </excludes>

and it works wrong - excludes everything. I expect that empty string matches to none of classes.

Few more examples, there is a module netbout-spi, all classes are in package com.netbout.spi. Without any exclude section it provides errors:
>[WARNING] FindBugs: L D NP: friend must be non-null but is marked as nullable  At Friends.java:[lines 122-124]
>[WARNING] FindBugs: L D NP: friend must be non-null but is marked as nullable  At Friends.java:[lines 143-145]
>[WARNING] FindBugs: L D NP: input must be non-null but is marked as nullable  At Attachments.java:[lines 166-168]
>[WARNING] FindBugs: L P SIC: The class com.netbout.spi.Friends$Search$1 could be   refactored into a named _static_ inner class  At Friends.java:[lines 118-124]
>[WARNING] FindBugs: L P SIC: The class com.netbout.spi.Friends$Search$2 could be refactored into a named _static_ inner class  At Friends.java:[lines 139-145]
>[WARNING] FindBugs: L P SIC: The class com.netbout.spi.Attachments$Search$1 could be refactored into a named _static_ inner class  At Attachments.java:[lines 162-168]

However, following excludes do not work:
    `<exclude>findbugs:Friends</exclude>`
    `<exclude>findbugs:com.netbout.spi.Friends</exclude>`
    `<exclude>findbugs:com.netbout.spi.*</exclude>`
    `<exclude>findbugs:/src/main/java/com/netbout/spi/Friends.java</exclude>`

**Comment by mkordas** [comment]
@exper0 are you sure that documentation at http://www.qulice.com/qulice-maven-plugin/example-exclude.html is wrong for FindBugs excludes? If yes, can you provide more specific examples what doesn't work?

**Comment by krzyk** [comment]
@exper0 have you tried 0.15.2 qulice?

**Comment by exper0** [comment]
@mkordas example in the original ticket. The issue is that regex ^$ shouldn't exclude anything but it excludes everything.

**Comment by exper0** [comment]
@krzyk no, it seems that I used old version - 0.12. Let me check if it's fixed in newer qulice

**Comment by exper0** [comment]
@krzyk check 0.15.2 - same issue there

**Comment by exper0** [comment]
@mkordas added details and examples in the ticket description

**Comment by mkordas** [comment]
@exper0 have you noticed `~` in doc for FindBugs regex excludes? It is required.

**Comment by exper0** [comment]
@mkordas yes. The problem was that actual error in inner classes - so strict exclude (without ~) didn't work. Now it's fine, thanks.

**Comment by exper0** [comment]
@mkordas @krzyk There problem actual did exists in 0.12 (which is active in Netbout by default) - filters that work in 0.15.2 didn't work in 0.12
