### ISSUE TITLE
Is it possible to disable one or more checkstyle checks?

### ISSUE THREAD

**Issue by srgg** [teamed/qulice#622]
I like the idea of this plugin very much, but being realist I can't afford to myself to spend a long time on fixing all the failed checks. Especially, considering the fact that it is pretty raw code.

The most annoying checks for me are the bunch of javadoc rules such as: JavadocTagsCheck, JavadocPackageCheck.

BTW @author check doesn't allow to use more or less spam aware postbox address formats such as: 
```
Me <me at somewhere dor com>
```

So the question is: Is there a way to prevent these javadoc related rules from being used during the checkstyle:check?

**Comment by krzyk** [comment]
@srgg please see https://github.com/teamed/qulice/issues/326#issuecomment-58991903
So you won't be able to remove the checks globally, but you might be able to do it on the package level by using package-info.java files and appropriate exclude (checkstyle, PMD or FindBugs one).
As for the author tags,  good idea, but if we will use the same format for non spam messages, it is too easy to gather such addresses also, so I don't think there is a value in that, spammers will find the addresses.

But if you still think that author tag formatting is a good idea, please report a new issue with that and we can discuss it more.

**Comment by srgg** [comment]
@krzyk Thank you for the quick turnaround. The issue you are pointed me out was completely answered on my question. Unfortunately, as I mentioned above, I can't afford to myself spent a lot of time to join the club, therefore I've configured all the stuff separately.

IMO having the package level configuration is a bit weird for the club, since you have a good chance to never know about the existing suppressions.
