### ISSUE TITLE
NonStaticMethodCheck complains about methods that just throw an exception

### ISSUE THREAD

**Issue by HDouss** [teamed/qulice#623]
NonStaticMethodCheck complains about methods that only throws an exception. This could be fine in cases where a class implementation have a "not yet" supported feature or a serializable object that does not support readObject/writeObject where the method have just to throw an appropriate exception. Example:
```
private void writeObject(final ObjectOutputStream stream)
    throws NotSerializableException {
    throw new NotSerializableException(AggregateException.class.getName());
}
```

**Comment by mkordas** [comment]
@HDouss but then method has '@Override' and is excluded from check, right? Please provide an example.

**Comment by HDouss** [comment]
@mkordas You are right, I update description to give another example.

**Comment by krzyk** [comment]
@HDouss If you gave an example please show it,  if not please close this issue

**Comment by HDouss** [comment]
@krzyk The examples are in the description: 
>This could be fine in cases where a class implementation have a "not yet" supported feature or a serializable object that does not support readObject/writeObject where the method have just to throw an appropriate exception

**Comment by krzyk** [comment]
@HDouss but such methods are not correct ones, so the appropriate way of dealing with this is adding an exclude. readObject/writeObject shouldn't be implemented if there is no state.

**Comment by HDouss** [comment]
@krzyk But NonStaticMethodCheck should alert the developer about methods that are not declared as static but are in fact static. For example: 
```
private void writeObject(final ObjectOutputStream stream)
        throws NotSerializableException {
        throw new NotSerializableException(AggregateException.class.getName());
    }
```
Why such a method should be static ?

**Comment by krzyk** [comment]
@HDouss OK, so you are saying that we should exclude the `readObject()` and `writeObject()` methods or some other general rule?

**Comment by HDouss** [comment]
@krzyk I would say that in general, if a method just throws an exception shouldn't be considered as static.

**Comment by krzyk** [comment]
@HDouss please update the description with that clarification

**Comment by krzyk** [comment]
@HDouss method that only throws exception

**Comment by HDouss** [comment]
@krzyk Done.

**Comment by krzyk** [comment]
@HDouss sorry, I still don't see it in the issue description

**Comment by krzyk** [comment]
@HDouss also add an example code, it will be easier to understand and implement

**Comment by HDouss** [comment]
@krzyk First sentence: 
>NonStaticMethodCheck complains about methods that only throws an exception

**Comment by krzyk** [comment]
@HDouss yes, I noticed that later :), but example would make it even better.
Could you add an example method that shouldn't cause `NonStaticMethodCheck` to complain?

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@hdouss thanks for reporting! I topped your account for 15 mins, transaction 75228386

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here

**Comment by krzyk** [comment]
@davvd assign @kitsook

**Comment by kitsook** [comment]
@krzyk @davvd i am not taking new tasks at the moment. please assign to someone else

**Comment by krzyk** [comment]
@kitsook OK, I'll reassign

**Comment by krzyk** [comment]
@davvd please assign @gumbelmj

**Comment by davvd** [comment]
> @davvd assign @kitsook 

@krzyk done. @kitsook the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd please assign @gumbelmj

@krzyk sure! @gumbelmj the task is yours, please go ahead

**Comment by gumbelmj** [comment]
@davvdthe pull request has been submitted.

**Comment by gumbelmj** [comment]
@HDouss can you close this issue as it has been fixed?  Thanks.

**Comment by HDouss** [comment]
@gumbelmj it seems that the implementation also excludes such cases:
```java
    private void data(final String input) {
        try {
            Class.someStaticMethod(input);
        } catch (final IOException ex) {
            throw new IllegalStateException(ex);
        }
    }
```

The example above is a true positive (i.e it should raise a complaint by `NonStaticMethodCheck`), but your implementation is discarding it.

**Comment by krzyk** [comment]
@HDouss I don't think this is a good case, if there is such method it should be definitely static (unless it is an `@Override` method).

**Comment by HDouss** [comment]
@krzyk This is what I said
>The example above is a true positive (i.e it should raise a complaint by NonStaticMethodCheck)

But the solution provided by the PR will exclude such case.

**Comment by HDouss** [comment]
@krzyk It will exclude it from the check, but it shouldn't. Such case should make qulice raise an issue.

**Comment by krzyk** [comment]
@HDouss Sorry, you are right ( I must learn not to read on the phone :) ).

**Comment by gumbelmj** [comment]
@krzyk I saw you deployed the changes.  Should I continue to address @HDouss concerns?

**Comment by krzyk** [comment]
@gumbelmj yes you should, deploy is just to finish the PR, you will need to create a new one.

**Comment by davvd** [comment]
> @davvd the pull request has been submitted.

@gumbelmj OK

**Comment by krzyk** [comment]
@gumbelmj please add reference to the pull requests here

**Comment by gumbelmj** [comment]
@krzyk I updated pull request #685 to count the number of semi-colons instead of the number of lines.  I also added another test case.

**Comment by gumbelmj** [comment]
@HDouss this has been merged again. Are you satisfied with the code now?

**Comment by HDouss** [comment]
@gumbelmj Thanks

**Comment by davvd** [comment]
@gumbelmj Thank you, I have added **30 mins** to your account in payment/transaction "`AP-61V51661VF813222P`", time consumed: 261 hours and 29 mins... +30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/36306?open=rating)
