### ISSUE TITLE
Ignore LineLength check on lines containing links

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#625]
Right now Checkstyle's `LineLength` check complains on lines with > 80 chars containing lengthy links. The only thing that implementer can do is to use suppression, as links cannot be divided across the lines, e.g.:
```
  /**
   * First sentence.
   * @author Yegor Bugayenko (yegor@tpc2.com)
   * @version $Id$
   * @since 1.0
   * @checkstyle LineLengthCheck (1 line)
   * @link https://github.com/teamed/qulice/blob/0c2bff851aad6ac5a23f4e43dd8bace68a3013db/qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java
   */
```
I'd expect all lines containing `http://` or `https://` to be skipped from this check.

**Comment by krzyk** [comment]
@mkordas good idea

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk someone else will help in this task, no problem at all

**Comment by davvd** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 569ccef5810de7335700009c

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @alexey-krylov

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @alexey-krylov

@krzyk OK @alexey-krylov please start, the task is yours

**Comment by krzyk** [comment]
@davvd assign @jimdeanspivey

**Comment by davvd** [comment]
> @davvd assign @jimdeanspivey

@krzyk done. @jimdeanspivey you are assigned to this task. please proceed...

**Comment by JimDeanSpivey** [comment]
@mkordas The PR #654 has been merged.

**Comment by mkordas** [comment]
@JimDeanSpivey thx

**Comment by JimDeanSpivey** [comment]
@davvd This issue has been accepted.

**Comment by davvd** [comment]
@jimdeanspivey thanks, paid, **38 mins** to your account, payment ID is `56b2fb04a97bd03c4000006d`, task took 70 hours and 39 mins to complete

the bonus for fast delivery (m=4239)

+38 added to your rating, at the moment it is: [+38](http://www.netbout.com/b/36321?open=rating)
