### ISSUE TITLE
Qulice allows catch parameters not following naming convention

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#627]
Currently Qulice does not complain on the following catch parameter names:
```java
try {
    ...
} catch(IllegalStateException ex_invalid_1) {
    ...
}
try {
    ...
} catch(IllegalStateException $xxx) {
    ...
}
```

I'd expect violation on both of these names. Only `ex` or 3-12 lowercase latin characters should be allowed.

Pattern should be `^(ex|[a-z]{3,12})$`. Moreover, rest of patterns should be unified to follow the convention: replace `^id$|^[a-z]{3,12}$` with `^(id|[a-z]{3,12})$` in LocalFinalVariableName, LocalVariableName, MemberName, ParameterName.

**Comment by krzyk** [comment]
@mkordas doesn't it work already?
```
        <module name="CatchParameterName">
            <property name="format" value="^ex|[a-z]{3,12}$"/>
        </module>
```
Is this configuration wrong?

**Comment by mkordas** [comment]
@krzyk both names are matching our regex: http://regexr.com/3cki7

**Comment by krzyk** [comment]
@mkordas so the `()` are missing, strange, those shouldn't be required, but they are.
Could you also add to the description that we should follow the convention of `^(ex|[a-z]{3,12})$` and replace all`^id$|^[a-z]{3,12}$` with `^(id|[a-z]{3,12})$`   (so the list includes LocalFinalVariableName, LocalVariableName, MemberName, ParameterName)?

**Comment by krzyk** [comment]
@mkordas ping

**Comment by mkordas** [comment]
@krzyk done, thanks for pinging

**Comment by krzyk** [comment]
@davvd valild bug

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valild bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `56a5fb478cc94d3272000322`

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @kitsook

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by davvd** [comment]
> @davvd assign @kitsook 

@krzyk done. @kitsook you are assigned to this task. please proceed...

**Comment by kitsook** [comment]
@krzyk the regular expressions of LocalFinalVariableName, LocalVariableName, MemberName, and ParameterName are working fine and do not require changes

`^id$|^[a-z]{3,12}$` works because it means there are two alternatives:
- between line start and end, contain "id"
- between line start and end, contain 3 to 12 lowercase alphabets

`^ex|[a-z]{3,12}$` of `CatchParameterName` doesn't work as expected as it means there are two alternatives:
- line start with "ex"
- line end with 3 to 12 lowercase alphabets

`^ex|[a-z]{3,12}$` can be fixed with `^ex$|^[a-z]{3,12}$` or the proposed `^(ex|[a-z]{3,12})$`

**Comment by krzyk** [comment]
@kitsook let's make all the regexes you mentioned to the `^(...)$` convention, it is more readable, also we need a test for the CatchParameterName so we will be sure there won't be any regression

**Comment by kitsook** [comment]
@dvvd PR #651 created

**Comment by kitsook** [comment]
@mkordas PR #651 merged. Please close the issue

**Comment by mkordas** [comment]
@kitsook thanks!

**Comment by davvd** [comment]
@kitsook **38 mins** was added to your account, many thanks for your contribution (payment AP-5BA49698PH173703C)! The task took 70 hours and 22 mins.

m=4222, that's why a bonus here for fast delivery

+38 added to your rating, current score is: [+98](http://www.netbout.com/b/36293?open=rating)
