### ISSUE TITLE
Qulice doesn't check puzzles

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#632]
Right now Qulice doesn't [check puzzles](https://github.com/yegor256/takes/pull/526#issuecomment-173131915).
It would be great to add this feature
I'm aware about [Pdd](https://github.com/teamed/pdd)  but
> Qulice is a static analysis quality control instrument for Java projects. It combines all the best static analysis instruments and pre-configure them. **You don't need to use and configure them individually any more**.

**Comment by krzyk** [comment]
@dmzaytsev at some point it was decided to use `pdd`, and puzzle checks in qulice were abandoned
@yegor256 should we try again with validating todos in qulice (doubling the work of `pdd`)?

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@krzyk I think that it's out of scope of qulice. We have a tool for that, let's keep this functionality there.

**Comment by dmzaytsev** [comment]
@krzyk okay, I'm closing the ticket
