### ISSUE TITLE
Member names are limited to 12 characters

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#633]
In #621 we've missed unintended change of format for member names: https://github.com/teamed/qulice/pull/621/files#diff-0ac1133cfe7780870854ffd4c3f1d582L323

Till Qulice `0.15.3` it was allowed to have member name with 13 characters, but from `0.15.4` it is prohibited.

As it was change made by mistake, we should revert it (change pattern to `^id$|^[a-z]{3,}$`) and write some tests to avoid regression.

**Comment by krzyk** [comment]
@yegor256 what do you think about limiting field names to just 12 characters, just like the variables in methods?

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@krzyk totally in favor of it. the shorter the name, the better. `3-12` looks like a reasonable interval.

**Comment by krzyk** [comment]
@mkordas please close this issue

**Comment by mkordas** [comment]
@krzyk closing then
