### ISSUE TITLE
Qulice doesn't check order of Javadoc tags

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#634]
Right now Qulice doesn't check order of Javadoc tags
it would be good t\o check that

I think [Oracle guidelines](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#orderoftags) can be used
```
Include tags in the following order:

@author (classes and interfaces only, required)
@version (classes and interfaces only, required. See footnote 1)
@param (methods and constructors only)
@return (methods only)
@exception (@throws is a synonym added in Javadoc 1.2)
@see
@since
@serial (or @serialField or @serialData)
@deprecated (see How and When To Deprecate APIs)
```

furthermore, place of `@checkstyle` and `@todo` should be checked as well

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk done. @mkordas the task is yours, please go ahead

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
@dmzaytsev thanks for the ticket, your account was topped for 15 mins, payment 75231649

**Comment by mkordas** [comment]
@davvd please see #637

**Comment by davvd** [comment]
> @davvd please see #637

@mkordas I will take a look, thanks

**Comment by mkordas** [comment]
@dmzaytsev merged in #637 and #645, can you please close the issue?

**Comment by dmzaytsev** [comment]
@mkordas thanks!

**Comment by mkordas** [comment]
@krzyk do you know what I did wrong here? @davvd forgot about this one

**Comment by krzyk** [comment]
@davvd you forgot to add payment to @mkordas

**Comment by mkordas** [comment]
@yegor256 extra 30 mins needed here

**Comment by yegor256** [comment]
@davvd pls add extra 30 mins to @mkordas

**Comment by davvd** [comment]
> @davvd you forgot to add payment to @mkordas 

@krzyk @yegor256 please help us here

**Comment by davvd** [comment]
> @davvd pls add extra 30 mins to @mkordas 

@yegor256 I've sent 30 mins extra to @mkordas in transaction ID "56d4205464a01504d00002c8"
