### ISSUE TITLE
Qulice allows 5 spaces for the indentation step

### ISSUE THREAD

**Issue by dmzaytsev** [teamed/qulice#635]
Qulice allows 5 spaces for the indentation step

![image](https://cloud.githubusercontent.com/assets/9972909/12477833/a2823906-c053-11e5-83c1-d5508c19b624.png)

see https://github.com/yegor256/takes/pull/526/files#diff-ea3e400b0f8b3cf80072e16a86fd31e9R248

I can't find the rule, but I thought four spaces is the standard indentation step

**Comment by krzyk** [comment]
@dmzaytsev already fixed in 0.15 release (see https://github.com/teamed/qulice/issues/527)

**Comment by dmzaytsev** [comment]
@krzyk thanks!
