### ISSUE TITLE
Allow precondition checks in constructors

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#638]
Right now `ConstructorOnlyInitializesOrCallOtherConstructors` rejects any other expression that field assignment in constructor. E.g. the following code is not valid:
```java
class Foo {
    private int size;
    Foo(int size) {
        Preconditions.checkArgument(
            size > 0, "Size should be greater than zero, but was %d", size
        );
        this.size = size;
    }
}
```
I'd like the code from above to be accepted. It should not be possible to create classes with invalid state, and Guava's `Preconditions` should be allowed.

**Comment by krzyk** [comment]
@mkordas wouoldn't http://aspects.jcabi.com/jsr-303.html cover that? (specifically `@Valid` annotation?)

**Comment by mkordas** [comment]
@krzyk Precoditions are usually just one line. I see that this complex example with `@Valid` has many lines and for me is a way too verbose.

**Comment by krzyk** [comment]
@yegor256 What do you think, should guava Preconditions be allowed in constructors?

**Comment by krzyk** [comment]
@mkordas citing @yegor256 from http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html#comment-2014240415
> I think that we should not fail during object costruction, but only during execution. Or, in other words, only when we ask our objects to expose some behavior, they have a right to fail.

**Comment by krzyk** [comment]
@mkordas and later http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html#comment-2015661139 : 
> Yes, I think that input validation should not happen in ctor. Even if you pass NULL as a single argument to new EnglishName(), it should not complain. If later, you never call its first() method, you will never know that the object you created was not "complete". It was a perfect employee for "doing nothing" job. But it's an incompetent employee for "fetching first name" job. See the point? Unless you give me a task, you will never know how good am I as an employee. Same here.

**Comment by mkordas** [comment]
@krzyk I see, thanks for extracting those. On the other hand we have JSR-303 validations that are working during object construction... So maybe they should be prohibited if we go that way :)

**Comment by krzyk** [comment]
@mkordas well, JSR-303 can be treated as documentation if there is no instrumentation of the code

**Comment by mkordas** [comment]
@krzyk OK, closing this one
