### ISSUE TITLE
How to use Qulice with Grails application?

### ISSUE THREAD

**Issue by aistomin** [teamed/qulice#640]
I have an idea to use Qulice in a Grails project that I'm currently working on. I spent about one hour trying to figure out how to do that, but unfortunately didn't get any result. I'm just wondering, should I put more energy on it or maybe somebody already had some positive/negative experience with that. 

I know that it's possible to change Grails application in a way to use native Maven configs. Probably it will be easy to integrate Qulice with such a projects. But what about standard grails applications?

Thanks in advance for your help. Let me know if my problem is not clear or you need additional information from my side.

**Comment by krzyk** [comment]
@aistomin unfortunatelly I haven't used grails at all so I don't know how to help you with this. Currently maven is the mostly used plugin in qulice, the second one being ant and gradle is in the works.
If grails build system is different from those three it would take some time to integrate it into qulice, as gradle would have probably higher priority.

**Comment by aistomin** [comment]
@krzyk thanks for quick response. Looks like Grails have his own build system, but it is possible to use Maven and Gradle instead of default. I'll try them. Anyway, thanks for detailed response and sharing future plans. I'm perfectly satisfied with the answer. I'm going to close the issue.
