### ISSUE TITLE
Enforce Qulice 0.15.4 over entire code

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#648]
Currently Qulice's code is validated using Qulice `0.15.2`. Let's update it to the latest version (currently `0.15.4`).

This task would require some smart way of assigning `@since` tag. I'd recommend making list of [release dates](http://stackoverflow.com/questions/13208734/get-the-time-and-date-of-git-tags) and then retrieving from repository [creation date](http://stackoverflow.com/questions/2390199/finding-the-date-time-a-file-was-first-added-to-a-git-repository) of each file.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
@mkordas many thanks for the bug report, I added 15 mins to your acc, transaction `56a7662533fcbd09bf000243`

**Comment by krzyk** [comment]
@davvd assign @krzyk

**Comment by krzyk** [comment]
@davvd please see PR #679

**Comment by davvd** [comment]
> @davvd assign @krzyk 

@krzyk done. @krzyk you are assigned to this task. please proceed...

**Comment by davvd** [comment]
> @davvd please see PR #679 

@krzyk I will take a look, thanks

**Comment by krzyk** [comment]
@mkordas changes have been merged to master, please close this issue

**Comment by mkordas** [comment]
@krzyk perfect!

**Comment by davvd** [comment]
@krzyk Much appreciated! **1 hour** was added to your account, payment ID `76556844`, time spent is 2 hours and 22 mins

the bonus for fast delivery (m=142)

added +60 to your rating, now it is equal to [+5167](http://www.netbout.com/b/35035?open=rating)
