### ISSUE TITLE
Empty line between methods of an Anonymous class makes qulice complain

### ISSUE THREAD

**Issue by HDouss** [teamed/qulice#653]
qulice complains when it finds an empty line between methods of an anonymous inner class.
Example :
```java
public void method() {
    new Runnable() {
        public void run() {
            do();
        }

        private void do() {
            //do something
        }
    }
}
```
qulice considers the line between `run()` method and `do()` method as an empty line inside the outer `method()` method.
I think qulice should allow such empty lines.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@HDouss could you post the error message which qulice uses to complain about those empty lines?

**Comment by HDouss** [comment]
@krzyk It's our `com.qulice.checkstyle.EmptyLinesCheck`. The message is: `Empty line inside method (EmptyLinesCheck)`.

**Comment by krzyk** [comment]
@davvd assign @jimdeanspivey

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag "bug" added

**Comment by davvd** [comment]
> @davvd assign @jimdeanspivey

@krzyk OK @jimdeanspivey please go ahead, this task is yours

**Comment by HDouss** [comment]
@davvd The bug is being resolved. I wasn't paid for reporting it.

**Comment by JimDeanSpivey** [comment]
@HDouss @davvd the PR #672 was merged.

**Comment by HDouss** [comment]
@JimDeanSpivey Thanks

**Comment by HDouss** [comment]
@davvd Ping
>@davvd The bug is being resolved. I wasn't paid for reporting it.

**Comment by davvd** [comment]
@jimdeanspivey thank you, added **30 mins** to your acc, payment num is `56b47c89accb8b18c900015b`, 137 hours and 55 mins spent in total to complete; +30 added to your rating, at the moment it is: [+68](http://www.netbout.com/b/36321?open=rating)

**Comment by HDouss** [comment]
@davvd Could you please give a reason for:
>@davvd The bug is being resolved. I wasn't paid for reporting it.

**Comment by HDouss** [comment]
@davvd Could you please explain why I haven't been paid for reporting this bug ? Thanks.

**Comment by davvd** [comment]
> @davvd Could you please explain why I haven't been paid for reporting this bug ? Thanks.

@hdouss @yegor256 please help us here

**Comment by HDouss** [comment]
@yegor256 Could I be paid for reporting this bug ?

**Comment by yegor256** [comment]
@davvd pls add extra 15 mins to @HDouss

**Comment by davvd** [comment]
> @davvd pls add extra 15 mins to @HDouss 

@yegor256 15 mins extra was just paid to @hdouss, transaction `78459039`
