### ISSUE TITLE
All usages of apache commons CharEncoding.UTF_8 should be prohibited

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#655]
`CharEncoding.UTF_8` (and the rest, like `CharEncoding.US_ASCII`) were used before JDK 1.7, but qulice requires this JDK so there is no point in allowing `CharEncoding`, users should use `StandardCharsets` from the JDK for the charsets.

`CharEncoding` exists in three libraries from apache: commons-lang, commons-lang3 and commons-codec. All of those should be prohibited and the user should get the message that he/she should use `StandardCharsets` instead.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by mkordas** [comment]
@krzyk can I take this one?

**Comment by krzyk** [comment]
@mkordas sure

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by krzyk** [comment]
@mkordas wait a second, I still need to get @davvd to notice it also (and get a bonus), if the task is closed earlier I won't get it :(

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk OK @mkordas please proceed, this task is yours

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will assign somebody else to this issue

**Comment by davvd** [comment]
@krzyk thanks for reporting! I topped your account for 30 mins, transaction 76003922

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk thanks, I removed the "postponed" tag

**Comment by mkordas** [comment]
@krzyk please assign me here

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk too many tasks (11) are active in the project already, can't assign new ones

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk there are already 11 active tasks in the project, we can't have more

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by davvd** [comment]
> @davvd assign @mkordas
> 

@krzyk yep, done. @mkordas it is your task now

**Comment by krzyk** [comment]
@mkordas please add reference to the PR

**Comment by mkordas** [comment]
@davvd please see PR #682

**Comment by mkordas** [comment]
@krzyk done in #682, please close the issue

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
> @davvd please see PR #682

@mkordas thanks, will take a look

**Comment by davvd** [comment]
@mkordas **1 hour** sent to your balance (ID `56bdab4a07e57a25440001f3`), many thanks! It took 17 hours and 55 mins.; there is a bonus for fast delivery (m=1075); +60 added to your rating, current score is: [+6094](http://www.netbout.com/b/36080?open=rating)
