### ISSUE TITLE
Prohibit empty line at the start and at the end of javadoc.

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#656]
Following cases two cases should make qulice complain:
* empty javadoc line at the beginning:
```
/**
 *
 * Some text
 */
```

* empty javadoc line at the end:
```
/**
 * Some text
 *
 */
```

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
@krzyk thanks for the report, I topped your acc for 30 mins, payment ID `75998417`

**Comment by krzyk** [comment]
@davvd assign @guiandmag

**Comment by davvd** [comment]
> @davvd assign @guiandmag

@krzyk too many tasks already active in the project (11), can't have more

**Comment by guiandmag** [comment]
@davvd I have no tasks assigned for me right now.

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd I have no tasks assigned for me right now.

@guiandmag you will have them soon

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk OK, I put "urgent" label here

**Comment by davvd** [comment]
@dskalenko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here... **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by krzyk** [comment]
@dskalenko How is the work going, do you need any help?

**Comment by dskalenko** [comment]
@krzyk Thanks for asking,  all clear and I don't need help, thanks, will push my changes today

**Comment by dskalenko** [comment]
@davvd here is the PR https://github.com/teamed/qulice/pull/702

**Comment by krzyk** [comment]
@dskalenko thanks

**Comment by davvd** [comment]
> @davvd here is the PR https://github.com/teamed/qulice/pull/702

@dskalenko I will take a look, thanks

**Comment by davvd** [comment]
@dskalenko thanks, I just added **30 mins** to your account, payment `77677193`, 143 hours and 42 mins spent... +30 added to your rating, current score is: [+30](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk OK, I un-labeled it as "urgent" tag
