### ISSUE TITLE
Prohibit 'public static' methods

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#659]
Methods that are `public static` are usually a sign of a [bad design](http://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html). Qulice should prohibit them with couple of exceptions:
* `public static void main(final String... args)`
*  methods annotated with `@Parameterized.Parameters`, `@BeforeClass`, `@AfterClass` and other JUnit annotations that must be used only with `public static` methods.

Classes or fields that are `public static` should not be prohibited by this check.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by krzyk** [comment]
@kitsook are ready to take this?

**Comment by kitsook** [comment]
@krzyk pls assign to someone else. I have set my status as away with alice in netbout

**Comment by krzyk** [comment]
@Happy-Neko can you take it?

**Comment by Happy-Neko** [comment]
@krzyk yes.

**Comment by krzyk** [comment]
@Happy-Neko We have to wait a bit for other tasks to complete, as we now have a limit of simultaneously assigned tasks.

**Comment by davvd** [comment]
@mkordas thanks for reporting! I topped your account for 15 mins, transaction 56baf4f700d77d5e2f00038e

**Comment by yegor256** [comment]
@mkordas that's rather harsh, but I like it, let's do it

**Comment by Happy-Neko** [comment]
@mkordas @yegor256 Sounds unnecessary extreme to me.
Static methods are not synonymous with utility classes. For example static factories are well known and extensively used OOP pattern.

**Comment by krzyk** [comment]
@Happy-Neko I don't recall any usages of static factory methods in the teamed code, more over I don't see even public static methods, that are not for use by JUnits `@Before`/`@After`, so prohibiting it is not so extreme.

**Comment by mkordas** [comment]
@Happy-Neko if it will become too extreme, we may consider tuning it down for method matching e.g. the following regexps:
* `valueOf`
* `getInstance`
* `newInstance`
* `create.*`
* `make.*`

What do you think?

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by Happy-Neko** [comment]
@mkordas I think this is good idea. 
Maybe even exclude all static methods that return class (or subclasses) type because these methods are most likely to be factories.

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment]
@vkuchyn please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have. Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by vkuchyn** [comment]
@mkordas shall I include 
> valueOf
getInstance
newInstance
create.*
make.*

as task definition, or it was suggestion? If so - please update issue description

**Comment by mkordas** [comment]
@krzyk can you make a final decision here? Either we can detect factories by names or by return type.

**Comment by krzyk** [comment]
@mkordas I don't like static factories (and they are not used in teamed.io) and I really hate singletons. So  no excludes (for now).
But there has to be a way to disable this check.

@vkuchyn And I think it might be possible to do it using PMD XPath rules (like `StaticAccessToStaticFields`).

**Comment by vkuchyn** [comment]
@krzyk we have conflict here with rule NonStaticMethodCheck. Now build fails or from new rule - prohibit public static methods, or from another one - make method static if no this reference. How to exclude NonStaticMethodCheck rule for IT projects to make build stable?   
For sure, we need to allow public methods without reference to this be non static. Shall I report a bug on it, or make puzzle?

**Comment by vkuchyn** [comment]
@davvd I am blocked with problem described [here](https://github.com/teamed/qulice/issues/659#issuecomment-186208756)

**Comment by krzyk** [comment]
@vkuchyn which ITs make this test fail? do they have public methods that are not junit annotated?

**Comment by vkuchyn** [comment]
@krzyk Failed next IT projects:
- pmd-violations, see [Java file](https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it/pmd-violations/src/main/java/com/qulice/foo/Violations.java)
- dependency-violations, see [Java file](https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it/dependency-violations/src/main/java/com/qulice/foo/Sample.java)
- dependency-violations-exclude, see [Java file](https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it/dependency-violations-exclude/src/main/java/com/qulice/foo/Sample.java)
- hibernate-validator-check, see [Java file](https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it/hibernate-validator-check/src/main/java/com/qulice/foo/Sample.java)
- multi-module, see [Java file](https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it/multi-module/mod-alpha/src/main/java/com/qulice/plugin/alpha/Main.java)
Yes, all provided java classes have public static not main, not junit annotated methods

If remove static method declaration, facing with another violation:
[ERROR] /src/main/java/com/qulice/foo/Violations.java[56]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)

**Comment by krzyk** [comment]
@vkuchyn but IT tests are already excluded in qulice-maven-plugin https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/pom.xml#L373-L374

**Comment by krzyk** [comment]
@vkuchyn you could exclude PMD or checkstyle check from the ITs that fail, not sure which one fails for you and you can add excludes directly in the code. It is OK if you don't test that particular check. (using `@checkstyle NonStaticMethod (2 lines)`) or just add usage of instance methods, or convert it to private statics, it all depends on particular case.

**Comment by vkuchyn** [comment]
@davvd Please, find someone for review #723

**Comment by krzyk** [comment]
@mkordas fix has been merged to master, please close this issue (@vkuchyn sorry for stepping in, I just need to have a free "urgent" slot available in the project :)

**Comment by mkordas** [comment]
@krzyk @vkuchyn thank you

**Comment by vkuchyn** [comment]
@davvd fixed and merged, see #723. Please - close issue and proceed payment. Thank you

**Comment by davvd** [comment]
> @davvd Please, find someone for review #723 

@vkuchyn OK

**Comment by davvd** [comment]
@vkuchyn **30 mins** added to your account (payment number `79073810`), many thanks for your contribution! 335 hours and 23 mins spent here.. +30 added to your rating, at the moment it is: [+120](http://www.netbout.com/b/36353?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk got it, "urgent" tag removed from here
