### ISSUE TITLE
Check to make sure that abbreviations are written in camel case

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#660]
There's always debate whether acronyms in class names should be written in uppercase or in camelcase. However, both [Google](http://checkstyle.sourceforge.net/reports/google-java-style.html#s5.3-camel-case) and [Microsoft](https://msdn.microsoft.com/en-us/library/141e06ef(v=vs.71).aspx) recommend making them camelcase meaning that we should prefer `XmlHttpRequest` over `XMLHTTPRequest`, which makes sesne also from readability perspective.

Let's enable and configure properly `AbbreviationAsWordInNameCheck` to prohibit class names like `XMLHTTPRequest`.

**Comment by krzyk** [comment]
@mkordas I like the idea.
@yegor256 What do you think about such rule? I just checked in takes, and there are classes like `RsPrettyJSON`, `TkCORS`, `RsPrettyXML` but on the other hand there is also `HttpException`, `TkSlf4j`. The first group is much bigger than the latter.

**Comment by yegor256** [comment]
@krzyk let's do it, I agree

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by davvd** [comment]
@mkordas thanks for tis bug, I topped your account for 15 mins, transaction `56b9d90fe357d530ee000206`

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk right, I added "urgent" label

**Comment by original-brownbear** [comment]
Suggest solution her  #703 :)

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
@vkuchyn please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by krzyk** [comment]
@vkuchyn please don't start work on this, we already have an outside PR for this one, let's see if we can make it better

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk got it, "urgent" tag removed from here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@mkordas changes have been merged to master, please close this issue

**Comment by mkordas** [comment]
@krzyk @original-brownbear thx

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk got it, "postponed" tag removed from here
