### ISSUE TITLE
Javadoc of a test method should start with the class name

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#664]
Javadoc of each test method should start with the name of the class that is being tested (name of the test class with `Test` word removed).

e.g. for `Foo` class, following Javadoc is correct:

```
/**
 * Foo can do it.
 */
```

this one also is correct (uses inner class `Foo.Bar` inside a `FooTest`):

```
/**
 * Foo.Bar can do it.
 */
```

but this one is incorrect:

```
/**
 * Can do it, because it is a Foo.
 */
```

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by mkordas** [comment]
@krzyk I'm not sure about that one - what about tests for entire components or modules?

**Comment by krzyk** [comment]
@mkordas That would be more of integration tests so they should and with IT (for failsafe), or maven invoker ones.

**Comment by mkordas** [comment]
@krzyk do you mean that we have convention to mark as IT tests that test 2 or more classes? For me classical distinction between IT and UT is not a number of classes being tested, but rather way of testing: UT checks code in the same process, while IT runs SUT in separate process thus usually requiring `pre-integration-test` and `post-integration-test` phases.

**Comment by krzyk** [comment]
@mkordas No we don't have that convention, but usually there is a driving class that is checked, so in most cases there is a `Class can do something`, even if this class needs several others to do the job. I greped javadocs and it is hard to find a case where the test doesn't mention the class being tested. Notable exceptions are test classes that are getting to big and are split into several classes, but are testing still the same class. In such cases there should be a way to exclude this check.

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by krzyk** [comment]
@davvd assign @vkuchyn

**Comment by davvd** [comment]
> @davvd assign @vkuchyn 

@krzyk too many tasks already active in the project (11), can't have more

**Comment by davvd** [comment]
@krzyk thanks for reporting! I topped your account for 30 mins, transaction 77006983

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
