### ISSUE TITLE
NonStaticMethodCheck should ignore IT tests and small fixes

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#666]
1. Currently `NonStaticMethodCheck` ignores only classes that end in `Test`, but it should also ignore classes that end in `IT` and `ITCase`.

2. Also remove exclude of `NonStaticMethodCheck` in `qulice-spi/src/main/java/com/qulice/spi/Environment.java` file

3. Remove `else exit 0;` clause in years.sh file

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by mkordas** [comment]
@krzyk can I take that one?

**Comment by krzyk** [comment]
@mkordas here you go

**Comment by krzyk** [comment]
@mkordas but I need to wait for @davvd to notice it first

**Comment by mkordas** [comment]
@krzyk sure, I can start preparing PR in the meantime, I'll need to wait a few days for reviewer anyway

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk there too many active tasks (11) already in the project, can't assign more

**Comment by krzyk** [comment]
@davvd assign @mkordas

**Comment by yegor256** [comment]
+1

**Comment by davvd** [comment]
> @davvd assign @mkordas 

@krzyk OK @mkordas please go ahead, this task is yours

**Comment by mkordas** [comment]
@davvd please see PR #680

**Comment by davvd** [comment]
> @davvd please see PR #680

@mkordas will take a look, thanks

**Comment by davvd** [comment]
@krzyk thanks a lot for reporting, **30 mins** added to your acc, pmt ID `76668899`

**Comment by mkordas** [comment]
@krzyk done in PR #680, please close

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
@mkordas Thanks so much! Your account was topped up for **1 hour** (transaction ID is `56baf3f4c26808321c0001fd`, the task took 21 hours and 25 mins)

the bonus for fast delivery (m=1285)

+60 added to your rating, at the moment it is: [+5620](http://www.netbout.com/b/36080?open=rating)
