### ISSUE TITLE
Fields should be marked transient only if class is Serializable

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#675]
Currently we have a PMD rule `BeanMembersShouldSerialize` with rationale:
> If a class is a bean, or is referenced by a bean directly or indirectly it needs to be serializable. Member variables need to be marked as transient, static, or have accessor methods in the class. Marking variables as transient is the safest and easiest modification. Accessor methods should follow the Java naming conventions, i.e. for a variable named foo, getFoo() and setFoo() accessor methods should be provided.

Most of the time we don't follow the rules for *Java Beans* (see getters/setters) so I think that the rule requiring fields to be `transient` should be loose up to only `Serializable` classes - and there is already such rule enabled in Findbugs (SE_BAD_FIELD):
> This Serializable class defines a non-primitive instance field which is neither transient, Serializable, or java.lang.Object, and does not appear to implement the Externalizable interface or the readObject() and writeObject() methods.  Objects of this class will not be deserialized correctly if a non-Serializable object is stored in this field.

We should remove rule `BeanMembersShouldSerialize` and create a test that ensures we can create classes without transient fields.

**Comment by krzyk** [comment]
@yegor256 What do you think about the above?

**Comment by yegor256** [comment]
@krzyk well... what's wrong with `transient`? it is an extra protection against accidental serialization, as far as I understand.

**Comment by krzyk** [comment]
@yegor256 I haven't thought of it as a protection, more like wasted keystrokes :)
If class is not `Serializable` then how could it be serialized by accident? One would have to do it on purpose (writeObject) in class that uses it.
And lomboks `@EqualsAndHashCode` requires naming each transient field for the generated methods (and this annotation is easily forgotten when refactoring the class).

**Comment by yegor256** [comment]
@krzyk OK, I'm convinced, let's remove this check

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk OK, I put "urgent" label here

**Comment by davvd** [comment]
@vkuchyn please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@krzyk many thanks, **30 mins** added to your acc for reporting this bug, pmt ID `77111221`

**Comment by krzyk** [comment]
@vkuchyn it is a good practice to add reference to the PR, even before it was merged

**Comment by davvd** [comment]
@vkuchyn I'm not sure who actually completed this task, since there were no messages from you above (correct me if I'm wrong)

**Comment by krzyk** [comment]
@vkuchyn you have to always inform David about PR in the issue you are solving, and after it was merged ask issue creator to close IT (unless creator notices it earlier, like in this case).  After you add the reference, please ask davdd for payment.

**Comment by vkuchyn** [comment]
@davvd Issue was fixed, see #698. Please, proceed payments

**Comment by davvd** [comment]
> @davvd Issue was fixed, see #698. Please, proceed payments
> 

@vkuchyn thank you!

**Comment by vkuchyn** [comment]
@davvd issue was fixed 7 days ago, but still no payments. Please, recheck status of it.

**Comment by vkuchyn** [comment]
@davvd More than 10 days passed and still no payment. Please - fix it.
@krzyk 10 days passed - no payment, no reaction on my comment above. What is the best way to resolve this situation according your working policy? Thanks.

**Comment by krzyk** [comment]
@vkuchyn you can ask @yegor256 for help here

**Comment by vkuchyn** [comment]
@krzyk Thanks
@yegor256 please, help to resolve the situation - read comments above.

**Comment by yegor256** [comment]
@davvd pls add extra 30 mins to @vkuchyn

**Comment by davvd** [comment]
> @davvd issue was fixed 7 days ago, but still no payments. Please, recheck status of it.

@vkuchyn @yegor256 please help us here

**Comment by davvd** [comment]
> @davvd pls add extra 30 mins to @vkuchyn 

@yegor256 I've sent 30 mins extra to @vkuchyn in transaction ID "78701880"

**Comment by vkuchyn** [comment]
@davvd Thank you for payment. What about raiting? This task tool 3 days according to github history. But it is not mentioned in my [netbout](http://www.netbout.com/b/36353?open=rating) rating. Please check it and fix.

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk right, I removed "urgent" tag

**Comment by vkuchyn** [comment]
@yegor256 again need your help. Please, see [comment above](https://github.com/teamed/qulice/issues/675#issuecomment-190759025)

**Comment by yegor256** [comment]
@vkuchyn see http://at.teamed.io/policy.html#15

**Comment by vkuchyn** [comment]
@yegor256 please, see http://at.teamed.io/policy.html#14 I didn't received any points, but got payment - what I am talking about

**Comment by yegor256** [comment]
@vkuchyn you still don't have rating points in your account in Netbout?

**Comment by vkuchyn** [comment]
@yegor256 still don't have this ticket in my rating. You can take a look by the reference http://www.netbout.com/b/36353?open=rating if you have access

**Comment by yegor256** [comment]
@vkuchyn that's because the payment was done not in a normal mode. won't happen in the future, I hope. we have to move on here, can't do anything with it.
