### ISSUE TITLE
LineLengthCheck must ignore @link and @see

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#683]
`LineLengthCheck` must ignore lines that start with `@link` and `@see`, for example:

```
/**
 * @link <a href="http://www.yegor256.com/2014/12/04/synchronization-between-nodes.html">Synchronization Between Nodes</a>
 */
```

This is how it worked before... why did we change that?

**Comment by mkordas** [comment]
@yegor256 we noticed in #592 that some at-clauses were unnecessarily exceeding limit of 80 chars, so we strengthened the check, but on the other hand #625 was raised to cover the links. Just update to latest Qulice and you'll be good to go.

**Comment by yegor256** [comment]
@mkordas right, it's a dupe of #625 thanks
