### ISSUE TITLE
DefaultMavenEnvironmentTest.java:136-143: Ideally integration test is required...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#699]
Puzzle `676-be080182` in `qulice-maven-plugin/src/test/java/com/qulice/maven/DefaultMavenEnvironmentTest.java:136-143` has to be resolved: Ideally integration test is required to reproduce NPE in issue #676. To reproduce problem firstly revert changes marked with #676, then add to pom.xml of IT project at least one exclude rule in configuration.excludes block and dependency (in my case worked org.hibernate:hibernate-annotations:3.5.6-Final). Suggestion is that dependency must be compile-time scope as far as JUnit didn't work as test-scope dependency.... The puzzle was created by Viktor Kuchyn on 9-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by davvd** [comment]
@dskalenko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dskalenko** [comment]
@davvd here is the PR #722

**Comment by dskalenko** [comment]
@davvd need more time for code review

**Comment by davvd** [comment]
> @davvd here is the PR #722

@dskalenko will take a look, thanks

**Comment by davvd** [comment]
> @davvd need more time for code review

@dskalenko of course, thanks for letting me know, take your time

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk thanks, I removed the "urgent" tag

**Comment by davvd** [comment]
@krzyk I am closing it, thanks all

**Comment by davvd** [comment]
@dskalenko I added **30 mins** to your account, many thanks for working with the project (79409485)! The completion time here was 552 hours and 14 mins.; +30 added to your rating, current score is: [+105](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent
