### ISSUE TITLE
CheckstyleValidatorTest.java:383-387: Sample code provided in #411...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#700]
Puzzle `411-71c8871e` in `qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java:383-387` has to be resolved: Sample code provided in #411 should be considered as invalid. Find a way how to do that by either custom check, or updating Checkstyle whenever IndentationCheck there will be more reliable. As for Checkstyle 6.15 there's no ready solution for that. Right now Qulice allows both correct and incorrect code from #411.... The puzzle was created by Michal Kordas on 9-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by davvd** [comment]
@krzyk I am closing it, thanks all
