### ISSUE TITLE
Duplicated PMD and Checkstyle checks for multiple string literals

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#701]
When Java file contains on purpose multiple string literals (e.g. while building XML or in tests), they can be suppressed as follows:
```java
    String act() {
        // @checkstyle MultipleStringLiterals (1 line)
        return String.format("%s%s", "test", "test");
    }
```
However, if methods contains at least 4 occurrences of some particular string, there is both Checkstyle and PMD violation:
```java
    @SuppressWarnings("PMD.AvoidDuplicateLiterals")
    String act() {
        // @checkstyle MultipleStringLiterals (1 line)
        return String.format("%s%s%s%s", "test", "test", "test", "test");
    }
```
I suggest removing Checkstyle rule and leaving just PMD one, as it has more convenient AST suppressions. We need to reconfigure PMD rule to warn from 2 duplicated strings.

Another option is to exclude PMD rule.

**Comment by krzyk** [comment]
@mkordas let's go with PMD rule

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment]
@dskalenko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dskalenko** [comment]
@davvd here is the PR #727

**Comment by davvd** [comment]
> @davvd here is the PR #727 

@dskalenko I will take a look, thanks

**Comment by krzyk** [comment]
@dskalenko and now after merge, you have to ask @mkordas to close the issue

**Comment by dskalenko** [comment]
@mkordas Could you please close this issue

**Comment by mkordas** [comment]
@dskalenko thanks

**Comment by davvd** [comment]
@dskalenko paid, thanks, added **30 mins** to your account, payment `79073826`, 309 hours and 36 mins was spent... +30 to your rating, your total score is [+60](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk OK, I un-labeled it as "urgent" tag
