### ISSUE TITLE
static analysis on individual java files

### ISSUE THREAD

**Issue by simonjenga** [teamed/qulice#704]
Is it possible for this project to execute static analysis on individual java files in a project?
A Software Developer may be working on a very huge java project and has added ONLY four files:

```
SimpleInterface.java
SimpleInterfaceImplementation.java
SimpleInterfaceMocker.java
SimpleInterfaceTest.java
```

Is it possible to carry out static analysis (one file at a time) on ONLY these four individual java files that have been created?

Is there such a command: ```mvn clean -Pqulice=SimpleInterfaceMocker``` in this project to enable them to do such a thing? This would be a real time saver!

The command to run a full Maven Build: ```mvn clean install -Pqulice``` performs static analysis on ALL projects files and most of the time this is NOT necessary since most of these files have not been edited or touched.

This wastes a lot of time and someone would ONLY like to run a full Maven Build at the very end just before they make a commit.

Maven has the command: ```mvn -Dtest=SimpleInterfaceTest test``` that executes ONLY a single test.

**Comment by krzyk** [comment]
@simonjenga interesting idea, but I think it is doable after #61 is done, and you will need full paths to be specified, this makes it a bit more painful.

It could look like this:
```
mvn clean install -Pqulice -Dcheck=src/main/java/com/qulice/mocks/SimpleInterfaceMocker.java,src/test/java/com/qulice/mocks/SimpleInterfaceMockerTest.java
```

It looks quite verbose, not sure if anyone would like to enter whole paths.

**Comment by krzyk** [comment]
@simonjenga Isn't `mvn qulice:check -Pqulice` enough for this? Qulice analysis in comparison with the whole build is quite fast.

**Comment by simonjenga** [comment]
@krzyk The command: ```mvn qulice:check -Pqulice``` is not applicable to all projects:
https://github.com/yegor256/takes/issues/455
https://github.com/jcabi/jcabi-email/issues/27

Providing full paths may look quite verbose but it is better off than the time wasted waiting for a full Maven qulice check to complete.

And BTW, we have something similar in ```Git``` that allows you to provide full paths to files that you would like to add and commit. Instead of using ```git add .``` You can do:

```
./>git add src/main/java/com/qulice/mocks/SimpleInterfaceMocker.java

./>git add src/test/java/com/qulice/mocks/SimpleInterfaceMockerTest.java

./>git commit -m "updated files one and two" src/main/java/com/qulice/mocks/SimpleInterfaceMocker.java src/test/java/com/qulice/mocks/SimpleInterfaceMockerTest.java

./>git push -f -u origin master
```

It also looks verbose but it is still in place in ```Git``` as it is helpful in some situations.

That is why I am suggesting ```qulice``` to have something similar so as to always avoid full Maven Builds that consume time.  This will make ```qulice``` to scale easily in large projects.

Try to imagine having to run a full ```qulice``` check on some large open source framework projects e.g ```JDK, Spring, Apache CXF, Apache Tapestry, Hibernate``` etc.

It may not be possible or even practical to use ```qulice``` in such projects. You would need a very powerful computer to do so which also may not be affordable in price.

**Comment by krzyk** [comment]
@simonjenga really? I just tried on a project and it takes 30s to perform analysis, but the whole build takes 10 minutes.

So your problem is that you:
1. have to make the full build for the qulice to work properly
2. qulice:check doesn't work correctly (pom.xml configuration is not taken into account)

Because what you propose (check only few files) will right now still require a full build (which can take minutes) and after it qulice will check everything (in under 1 min)./

**Comment by simonjenga** [comment]
@krzyk Yes, those are my two main concerns/problems.

What is the best way to go about it? Is it possible for my suggestion to be implemented in this project?
Is it worthwhile doing it?

Why does it have to check everything? Other files were not touched or edited.

**Comment by krzyk** [comment]
@simonjenga Yes, it doesn't have to check other files, but this check is relatively quick in comparison to the whole build. That's why I'm reluctant to add complication to the project just to speed things from 30s to 20s. (you have to take into account that starting the whole thing takes some time, so it won't be 1s ever).

Point 2 will be solved in #684

**Comment by simonjenga** [comment]
@krzyk OK, Thanks.

**Comment by krzyk** [comment]
@simonjenga If #684 will solve your issue, please close this one, thanks.

**Comment by simonjenga** [comment]
@krzyk I am closing it for now but this issue may be re-visited and opened again some time later.
