### ISSUE TITLE
Upgrade qulice to 0.16.2

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#709]
Let's upgrade our own qulice from 0.15.4 to 0.16.2 and:
- remove all unnecessary `transient` keywords.
- remove all LineLength excludes before lines with URLs (e.g. in qulice-checkstyle/src/main/java/com/qulice/checkstyle/JavadocTagsCheck.java)

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by davvd** [comment]
@krzyk thanks for the ticket, your account was topped for 30 mins, payment 79173443

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@davvd assign @vkuchyn

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by davvd** [comment]
> @davvd assign @vkuchyn 

@krzyk OK @vkuchyn please proceed, this task is yours

**Comment by vkuchyn** [comment]
@krzyk file [DuplicateFinderValidator](https://github.com/vkuchyn/qulice/blob/30f530b6d49aa1506291b6d37b012392dbeb57ec/qulice-maven-plugin/src/main/java/com/qulice/maven/DuplicateFinderValidator.java#L43-L45)
Has violation - not proper order, `@checkstyle` must be after `@todo` (AtclauseOrderCheck). But if to remove checkstyle annotation - we gets Line is too long (LineLengthCheck), about `@todo` description. This case blocks an issue. I see 2 possible decisions:
1. Create an issue to fix line length check like it was done for `@see` annotation
2. Split `@todo` description to fit 80 characters (this will reduce readability).
What will you suggest?

**Comment by vkuchyn** [comment]
@davvd I am blocked with https://github.com/teamed/qulice/issues/709#issuecomment-196739715

**Comment by krzyk** [comment]
@vkuchyn I would go with spliting the todo to fit 80 characters (except the URLs, those should work without wrapping)

**Comment by vkuchyn** [comment]
@krzyk ok, thanks

**Comment by vkuchyn** [comment]
@davvd fixed in #753. Need to review

**Comment by davvd** [comment]
> @davvd fixed in #753. Need to review

@vkuchyn thank you

**Comment by davvd** [comment]
@vkuchyn you're working with this issue for 15 days already. -30 added to your rating, current score is: [+150](http://www.netbout.com/b/36353?open=rating)

**Comment by krzyk** [comment]
@davvd please give more time here

**Comment by vkuchyn** [comment]
@davvd I was waiting for CR for PR #753 15 days. What behaviour should be in this case not to be penalized?

**Comment by vkuchyn** [comment]
@davvd need more time

**Comment by davvd** [comment]
> @davvd please give more time here

@krzyk OK, take your time

**Comment by davvd** [comment]
> @davvd need more time

@vkuchyn yeah, I know, take your time

**Comment by krzyk** [comment]
@davvd assign @vkuchyn

**Comment by davvd** [comment]
> @davvd assign @vkuchyn 

@krzyk there too many active tasks (3) already in the project, can't assign more

**Comment by vkuchyn** [comment]
@davvd Task is almost done, PR created, we all are waiting for reviewer )

**Comment by davvd** [comment]
> @davvd Task is almost done, PR created, we all are waiting for reviewer )

@vkuchyn OK

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by krzyk** [comment]
@vkuchyn thanks

**Comment by vkuchyn** [comment]
@davvd was merged and fixed in #753

**Comment by davvd** [comment]
> @davvd was merged and fixed in #753 

@vkuchyn thank you!

**Comment by davvd** [comment]
@vkuchyn Thanks a lot, I just topped your account for **30 mins**, transaction ID `88636738`, total time was 1894 hours and 7 mins; +30 to your rating, your total score is [+90](http://www.netbout.com/b/36353?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk got it, "urgent" tag removed from here
