### ISSUE TITLE
XML validator should be fixed

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#711]
Right now XML validator is quite buggy and enforces strange indentation rules.
Let's fix it so following rules are checked in xml files:
- indentation should be 4 spaces, always (even when attributes are moved to the next line)

correct:

```
<test first="123"
    second="456>
</test>
```

incorrect:

```
<test first="123"
      second="456>
</test>
```
- force preambule with encoding tag (`<?xml version="1.0" encoding="UTF-8"?>`)
- prohibit two tags in the same line
  correct:

```
<first>
    <second>text</second>
</first>
```

incorrect:

```
<first><second>text</second></first>
```
- allow attributes to be wrapped (as I don't have idea how to add excludes inside xmls, so strict rules for line length would be too restrictive)

correct:

```
<test name="John">
</test>
```

```
<test
    name="John">
</test>
```

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by davvd** [comment]
@krzyk thanks for this report, I added 30 mins to your account, in transaction `79073946`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
