### ISSUE TITLE
Instance fields should be prohibited in Tests

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#712]
If a class name ends with `Test` it should not be allowed to have an instance field, unless it is annotated with JUnit annotation (e.g. a `@Rule`).

Incorrect:
```java
public final class JobTest {
    private final Port port = new Port();

    @Test
    public void test() {
        ... do something with port...
    }
}
```

Correct:
```java
public final class JobTest {
    @Rule
    private final Port port = new Port();

    @Test
    public void test() {
        ... do something with port...
    }
}
```

First try to do it using PMD XPath rules (just like `StaticAccessToStaticFields` or `ConstructorOnlyInitializesOrCallOtherConstructors`).

**Comment by davvd** [comment]
@krzyk I tagged this as "bug"

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by mkordas** [comment]
@krzyk isn't it dup of #551?

**Comment by krzyk** [comment]
@mkordas oops, you are right, forgot about that one

**Comment by krzyk** [comment]
@davvd this is invalid

**Comment by davvd** [comment]
> @davvd this is invalid

@krzyk sure, thanks, I added "invalid" label to it
