### ISSUE TITLE
Allow public nonstatic methods without references to this object

### ISSUE THREAD

**Issue by vkuchyn** [teamed/qulice#724]
In task #659 a new rule was added to prohibit public static methods.
From other side in checkstyle rules we have NonStaticMethod that requires make method static if there are no references to this object. 
This is conflict of rules and may confuse developer. 
My proposition - modify NonStaticMethodCheck class to allow non static public methods if method has no references to this object. 
Example:
Valid 
`public int sum(int a, int b) {
    return a + b;
 }`

Not valid - required to be static
`protected int sum(int a, int b) {
    return a + b;
 }`

**Comment by krzyk** [comment]
@vkuchyn I don't think this is common to have a public method that doesn't depend on the state in teamed.io projects. What you have are just simple methods that should be private and static.
If it is an object it should have methods that depend on its state, if not then such method should be moved somewhere more appropriate.

**Comment by vkuchyn** [comment]
@krzyk thanks, seems it is good point
