### ISSUE TITLE
Qulice should use source level 1.7

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#725]
Qulice requires JDK 1.7 to run (FindBugs and PMD requirement), but we are still using source code level 1.6 inherited from jcabi-parent.
Let's compile the whole project using java 1.7 and:
1. use diamond operator in all places where new collection classes are created (make sure to remove potential LineLength suppressions or join lines that were wrapped because of the generic parameters)
2. Replace are cases where `AutoCloseable` is used with proper try-with-resources (in `DataSourceReader`, `FindBugsValidator`, `PMDValidatorTest`, `Prettifier`)
3. Use multi catch in `DependenciesValidator` and `Wrap`

**Comment by mkordas** [comment]
@krzyk I'm interested in doing that after @davvd will fully process it.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@mkordas OK

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment]
@dskalenko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here. The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment]
@krzyk thanks for this report, I added 30 mins to your account, in transaction `79421484`

**Comment by dskalenko** [comment]
@davvd here is PR #750

**Comment by davvd** [comment]
> @davvd here is PR #750 

@dskalenko thank you

**Comment by krzyk** [comment]
@dskalenko thank you

**Comment by davvd** [comment]
@dskalenko I just added **30 mins** to your account, many thanks for your contribution (80637285).. 212 hours and 28 mins spent here; +30 added to your rating, at the moment it is: [+135](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent
