### ISSUE TITLE
Exclude MultipleStringLiterals for tests

### ISSUE THREAD

**Issue by vkuchyn** [teamed/qulice#730]
This [article](http://www.yegor256.com/2014/04/27/typical-mistakes-in-java-code.html#redundant-constants)  says:

> Another typical mistake is to use constants in unit tests to avoid duplicate string/numeric literals in test methods. Don't do this! Every test method should work with its own set of input values.

Now we have rule MultipleStringLiterals that requires to introduce string to constant. This forces developer to extract constant that breaks concept of test independence. 
Moreover, let's make another rule to check test independence. It should violate if test method has reference to test class constant (probably aby other constant, but I'm not sure about this point)

**Comment by mkordas** [comment]
@vkuchyn we cannot disable that check because of http://www.yegor256.com/2014/04/27/typical-mistakes-in-java-code.html#test-data-coupling.
Regarding constants - agreed that test data should not be stored in constants, but they also have different purposes.

**Comment by vkuchyn** [comment]
@mkordas Well, I see. So what is compromise - leave rule MultipleStringLiterals but disable it between methods. Think this satisfies as data coupling, as test atomicity

**Comment by krzyk** [comment]
@mkordas @vkuchyn there is no contradiction here, the rule about test-data-coupling clearly states that one should introduce a variable, not a class constant

**Comment by vkuchyn** [comment]
@krzyk MultipleStringLiterals rule forces me to extract constant if String occurs in several tests. But if to exclude it - we will meet another problem - data coupling described by @mkordas. Here is contradiction

**Comment by krzyk** [comment]
@vkuchyn There is no way to disable the MultipleStringLiterals between methods (it is a simple checkstyle rule), more over it will be removed, and similar PMD rule will be used.
The way to workaround it is to use a `final` variable inside tests.
And in different tests use different values.
If that is not possible (e.g. you construct an XML that has same fields) then either disable the rule (this is appropriate in such case) or create an abstraction in another class that can be reused in tests.

**Comment by krzyk** [comment]
@vkuchyn is there more in this issue, or can we close it?

**Comment by vkuchyn** [comment]
@krzyk yes, thanks
