### ISSUE TITLE
Do not require capital letters for '@return' and '@param' tags

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#731]
Right now Qulice always demands capital letter after `@return` and `@param`. I propose to disable these checks, as they are contradicting with what Oracle suggests at http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#@param that there are different styles.

The rule is especially not applicable to return tags, e.g. Qulice now requires strange
```
@return True when empty, false otherwise
```
instead of just
```
@return true when empty, false otherwise
```

There are also other resources that do not demand capital letters:
* http://blog.joda.org/2012/11/javadoc-coding-standards.html
* https://dev.liferay.com/participate/javadoc-guidelines

**Comment by krzyk** [comment]
@yegor256 Could you give your opinion here? You added the check for this.
I personally like the large letter at the beginning, and would like also a period at the end.

**Comment by yegor256** [comment]
@krzyk I also like the capital letter...

**Comment by mkordas** [comment]
@krzyk @yegor256 then at least we need to demand dot at the end, do you agree?

**Comment by yegor256** [comment]
@mkordas well, not really :) I think that a dot is needed only when there are more than one sentence. A dot is a separator, not a decoration. We have to use it when we need to separate something from something else. So, a dot that ends a sentence that is not followed by another sentence is nothing else, but a graphic element. Make sense?

**Comment by mkordas** [comment]
@yegor256 makes sense for me, but starting with capital letter and not finishing with dot is not compliant with Oracle guide, but of course we can have our own style.

However, right now even for one sentence half people put dots and second half doesn't. So maybe a rule to prohibit dot if there is just one sentence?

**Comment by yegor256** [comment]
@mkordas yes, that would be logical

**Comment by mkordas** [comment]
@yegor256 @krzyk closing this one, let's continue in #733
