### ISSUE TITLE
Disable some rules for legacy project

### ISSUE THREAD

**Issue by vkuchyn** [teamed/qulice#739]
I have a legacy project and want to provide qulice to it. But of course there are tons of violations - there is no resource to fix it at the time. So, I decided to fix first critical rules and with continuously refactoring improve code quality to perfect. Add @checkstyle excludes requires also a lot of time. SO is there a way to set up some set of rules at maven plugin? How do you manage legacy projects?

**Comment by krzyk** [comment]
@vkuchyn Basically we don't, it is all or nothing. See #622 and #326

**Comment by vkuchyn** [comment]
@krzyk Thank you for clear answer. I'll ask another question - what practices for code style are you following when you get legacy project with lots of violations? Maybe, you have some experience.

**Comment by vkuchyn** [comment]
@mkordas 

> @vkuchyn BTW, you can link to specific line in Travis: https://travis-ci.org/yegor256/rultor/builds/112852498#L2986

thanks for information :)

**Comment by krzyk** [comment]
@vkuchyn usually I try do do it per module, if it is not possible, you could disable the whole checkstyle, pmd or findbugs, that would reduce the number of rules that you would need to enforce in the beginning.

What you might also try for PMD and FindBugs is disabling rules on the package level, e.g. create a package-info.java with `package com.company`, and put suppresions there, I haven't tested it unfortunately.

**Comment by vkuchyn** [comment]
@krzyk great thanks!
