### ISSUE TITLE
DefaultValidatorsProvider.java:81-83: Make FindBugsValidator inherit from ResourceValidator...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#740]
Puzzle `61-832eca62` in `qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java:81-83` has to be resolved: Make FindBugsValidator inherit from ResourceValidator and use it similarly to CheckstyleValidator. Remember to move it to externalResource method and make sure all the tests pass.... The puzzle was created by krzyk on 27-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk OK, I un-labeled it as "postponed" tags

**Comment by davvd** [comment]
@krzyk It is closed now
