### ISSUE TITLE
Violation.java:57-60: Let's split the message part...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#741]
Puzzle `61-654de8aa` in `qulice-spi/src/main/java/com/qulice/spi/Violation.java:57-60` has to be resolved: Let's split the message part into lines, message and check name. After it is done fix CheckstyleValidatorTest.ViolationsMatcher to handle all those parameters and fix all failing tests.... The puzzle was created by krzyk on 27-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd assign me

**Comment by krzyk** [comment]
@davvd please see PR #751

**Comment by davvd** [comment]
> @davvd assign me

@krzyk the task is yours, please proceed

**Comment by davvd** [comment]
> @davvd please see PR #751 

@krzyk will take a look at it, thanks

**Comment by davvd** [comment]
@krzyk It is closed now

**Comment by davvd** [comment]
@krzyk thanks, I just added **1 hour** to your account, payment `80573931`, 22 hours and 50 mins spent. the bonus for fast delivery (m=1370). +60 added to your rating, at the moment it is: [+6153](http://www.netbout.com/b/35035?open=rating)
