### ISSUE TITLE
CheckstyleValidatorTest.java:442-444: This test and passesWindowsEndsOfLineWithoutException should...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#742]
Puzzle `61-61fa67ee` in `qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java:442-444` has to be resolved: This test and passesWindowsEndsOfLineWithoutException should be refactored to gather log4j logs and validate that they work correctly. (see changes done in #61)... The puzzle was created by krzyk on 27-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by davvd** [comment]
@krzyk Done, the task is closed
