### ISSUE TITLE
DefaultValidatorsProvider.java:84-86: Make XmlValidator and CodeNarcValidator inherit...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#745]
Puzzle `61-1e86e587` in `qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java:84-86` has to be resolved: Make XmlValidator and CodeNarcValidator inherit from ResourceValidator and use it similarly to CheckstyleValidator. Remember to move it to externalResource method and make sure all the tests pass.... The puzzle was created by krzyk on 27-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I will try to assign someone else

**Comment by davvd** [comment]
@krzyk Done, the task is closed
