### ISSUE TITLE
DefaultValidatorsProvider.java:78-80: Make PMDValidator inherit from ResourceValidator...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#746]
Puzzle `61-1d39a5c7` in `qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java:78-80` has to be resolved: Make PMDValidator inherit from ResourceValidator and use it similarly to CheckstyleValidator. Move it to externalResource method and make sure all the tests pass.... The puzzle was created by krzyk on 27-Feb-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd assign me

**Comment by krzyk** [comment]
@davvd please see PR #756

**Comment by davvd** [comment]
> @davvd assign me

@krzyk there too many active tasks (5) already in the project, can't assign more

**Comment by davvd** [comment]
> @davvd please see PR #756 

@krzyk will take a look, thanks

**Comment by krzyk** [comment]
@yegor256 Where is the policy for the amount of active tasks in a project? How should I know which number is correct right now?

**Comment by yegor256** [comment]
@krzyk it's a dynamic parameter. in open source projects we're trying to keep this number to a minimum, mostly because these projects are donated by Teamed.io and we don't want to burn too much money here

**Comment by krzyk** [comment]
@davvd assign me

**Comment by davvd** [comment]
> @davvd assign me 

@krzyk too many tasks (3) are active in the project already, can't assign new ones

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed 

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed 

@krzyk all right, we'll find someone else for this task

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk OK, I un-labeled it as "postponed" tag

**Comment by krzyk** [comment]
@davvd assign me

**Comment by davvd** [comment]
> @davvd assign me

@krzyk too many tasks already active in the project (4), can't have more

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk thanks, I added "urgent" label

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I un-labeled it as "urgent" tags

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk thanks, I added "urgent" label

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk OK, I un-labeled it as "postponed" tags

**Comment by krzyk** [comment]
@davvd assign me

**Comment by davvd** [comment]
> @davvd assign me

@krzyk of course, the task is yours, go ahead

**Comment by krzyk** [comment]
@davvd please see PR #802

**Comment by davvd** [comment]
> @davvd please see PR #802 

@krzyk I will take a look, thanks

**Comment by davvd** [comment]
@krzyk Thanks all, closed

**Comment by davvd** [comment]
@krzyk **30 mins** sent to your balance (ID `98619905`), many thanks! It took 94 hours and 12 mins.; added +30 to your rating, now it is equal to [+993](http://www.netbout.com/b/35035?open=rating)
