### ISSUE TITLE
CheckstyleValidatorTest.java:722-723: add test for next situation...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#752]
Puzzle `715-04710633` in `qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java:722-723` has to be resolved: add test for next situation `return new ArrayList

();`... The puzzle was created by Viktor Kuchyn on 11-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will try to find someone else

**Comment by davvd** [comment]
@krzyk Thanks, closed
