### ISSUE TITLE
Run Qulice to inspect Qulice code quality

### ISSUE THREAD

**Issue by wilsonmar** [teamed/qulice#757]
I'm new to this, so I'm looking to use Qulice to run something.
Might as well be itself.
But I don't see the `<goal>check</goal>` from the README.md in Qulice's pom.xml.
There is `<goal>enforce</goal>` though.

**Comment by krzyk** [comment]
@wilsonmar qulice check is inherited from jcabi-parent (see jcabi/jcabi-parent)

**Comment by krzyk** [comment]
@wilsonmar does the above answer your question?

**Comment by krzyk** [comment]
@wilsonmar ping

**Comment by krzyk** [comment]
@wilsonmar ping

**Comment by krzyk** [comment]
@wilsonmar ping

**Comment by wilsonmar** [comment]
No it does not because I am a noob, so pardon the naive question here.
I need to research what  jcabi-parent means.

What I need is an explanation of how to install Qulice with dependents and
a library under test,
which I've started to do at http://wilsonmar.github.io/java-devops-workflow/

**Comment by krzyk** [comment]
@wilsonmar jcabi-parent is a maven parent project that we use: https://github.com/jcabi/jcabi-parent

As for qulice, you can check out our integration tests, e.g. https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it/checkstyle-violations/pom.xml or others at https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/it

**Comment by krzyk** [comment]
@wilsonmar Have you had a chance to look at jcabi-parent? As you can see there it is configured with qulice, and qulice itself uses it so is tested with previous qulice version.

**Comment by krzyk** [comment]
@davvd this is invalid

**Comment by krzyk** [comment]
@davvd this is invalid

**Comment by krzyk** [comment]
@yegor256 davvd ignores my requests to invalidate this issue

**Comment by yegor256** [comment]
@krzyk that's because it's not really an issue yet. it was never tagged as a valid bug. that's why it's still outside of scope. I'll close it now
