### ISSUE TITLE
Allow logging in constructors

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#758]
Currently Qulice prohibits logging statements in constructors:
```java
class Logging {
    Logging() {
        Logger.debug(Logging.class, "Creating logging object");
    }
}
```
This is not strictly part of object logic, so I don't see a reason why such information/debug message should be prohibited.

I'd expect logging statements to be allowed in constructors.

**Comment by davvd** [comment]
@krzyk please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by krzyk** [comment]
@mkordas I'm not sure why we should log anything in constructors? Isn't `@Loggable` a solution to this?

**Comment by mkordas** [comment]
@krzyk thanks, `@Loggable` looks nice
