### ISSUE TITLE
PMD's AvoidDuplicateLiterals is not equivalent to original MultipleStringLiteralsCheck

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#760]
In Qulice 0.16.4 `AvoidDuplicateLiterals` took over `MultipleStringLiteralsCheck`. However, these checks are not fully equivalent.

`MultipleStringLiteralsCheck` was by default ignoring duplicates in annotations, see http://checkstyle.sourceforge.net/config_coding.html#MultipleStringLiterals. `AvoidDuplicateLiterals` doesn't do that, but it should, as it doesn't make sense to extract strings used in annotations to constants, especially if they are e.g. PMD exclusions.

Let's tune `AvoidDuplicateLiterals` to allow duplicates in annotations.

**Comment by krzyk** [comment]
@dmarkov valid bug

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@mkordas thank you for the ticket reported, I topped your account for 15 mins, transaction `570ca198dd526211c100028f`

**Comment by xupyprmv** [comment]
@krzyk Can this issue being resolved soon?

**Comment by krzyk** [comment]
@xupyprmv let's see

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by xupyprmv** [comment]
@krzyk Great thanks

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk got it, "urgent" label here

**Comment by davvd** [comment]
@dskalenko this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dskalenko** [comment]
@davvd here my PR #792

**Comment by davvd** [comment]
> @davvd here my PR #792 

@dskalenko thank you!

**Comment by dskalenko** [comment]
@mkordas Could you please close the task

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk OK, I un-labeled it as "urgent" tag

**Comment by davvd** [comment]
@dskalenko I just added **30 mins** to your account, many thanks for your contribution (95742106).. 75 hours and 12 mins spent here; +30 added to your rating, current score is: [+90](http://www.netbout.com/b/36376?open=rating)
