### ISSUE TITLE
Prohibit usage of '@author' Javadoc tag

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#761]
I don't see any reason why Qulice demands `@author` for every class. It usually is just a noise, because this information is in Git blame anyway. Moreover it gets outdated quickly, as after a few changes original author may have very little in common with a class.

Very rarely user of an API needs to know an author of particular item. Even if they want to know, the first point of contact is a GitHub/ticket anyway.

Apache already prohibits these tags: http://www.theinquirer.net/inquirer/news/1037207/apache-enforces-the-removal-of-author-tags

Another article: https://www.databasesandlife.com/dont-use-the-author-javadoc-tag/

**Comment by krzyk** [comment]
@yegor256 Do you have preference regarding `@author` tag?

**Comment by yegor256** [comment]
@krzyk I think @mkordas is right, we should stop using that tag

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag "bug" added

**Comment by davvd** [comment]
@mkordas many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `5714b2d8dacf4d0dc10000b7`

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/761#issuecomment-384933655))

@krzyk Job [#761](https://github.com/teamed/qulice/issues/761) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/761#issuecomment-384933655))

@krzyk Thanks for your contribution, @mkordas[/z](https://www.0crat.com/u/mkordas)! If you would be a member of [the project](https://www.0crat.com/p/C3T49A35L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/761#issuecomment-385421378))

@krzyk The job [#761](https://github.com/teamed/qulice/issues/761) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/1201467250); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@mkordas this was fixed in https://github.com/teamed/qulice/pull/886 could you close this one?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/teamed/qulice/issues/761#issuecomment-386613291))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#761](https://github.com/teamed/qulice/issues/761), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by mkordas** [comment]
@krzyk thanks for fixing that!

**Comment by 0crat** [comment]
The job [#761](https://github.com/teamed/qulice/issues/761) is now out of scope
