### ISSUE TITLE
How to fix the violation SE_TRANSIENT_FIELD_NOT_RESTORED of FindBugs?

### ISSUE THREAD

**Issue by essobedo** [teamed/qulice#762]
Hi Qulice team,

I need some help to find the best way to fix the violation [_SE_TRANSIENT_FIELD_NOT_RESTORED: Transient field that isn't set by deserialization_](http://findbugs.sourceforge.net/bugDescriptions.html#SE_TRANSIENT_FIELD_NOT_RESTORED) of FindBugs in the project takes within the context of this ticket https://github.com/yegor256/takes/issues/660, my PR is https://github.com/yegor256/takes/pull/662. 

Indeed in the project _takes_ we have twice this kind of violation:
- In the class _HttpException_ [here](https://github.com/yegor256/takes/blob/65f4712ea2e21c02ce4655ce700778b2600d25fd/src/main/java/org/takes/HttpException.java#L46)
- In the class _RsForward_ [here](https://github.com/yegor256/takes/blob/65f4712ea2e21c02ce4655ce700778b2600d25fd/src/main/java/org/takes/facets/forward/RsForward.java#L65)

To "fix" those violations so far I proposed to proceed as next:
- For the class _HttpException_, I fixed the issue by removing the modifier _transient_ but I get a warning from PMD (_BeanMembersShouldSerialize_ ) complaining about the fact that I don't have any accessor which is not true here since I have the method _code()_ instead of the expected method _getStatus()_ so I suppressed the warning "PMD.BeanMembersShouldSerialize".
- For the class _RsForward_, I didn't find any obvious way to fix it since the variable _origin_ is not necessary _Serializable_ so it needs to remain _transient_ so I added the corresponding annotation SuppressFBWarnings.

So my question is: Do you have any better way to fix those violations to propose?

Thank you in advance,
BR,
Nicolas

**Comment by essobedo** [comment]
@davvd I need help to fix the FindBugs violations in takes so could you please assign it to someone in the Qulice team as you are also the PM? Thank you in advance

**Comment by krzyk** [comment]
@essobedo well, why not just implement the readObject and writeObject?

**Comment by essobedo** [comment]
@krzyk thx for the suggestion but how do you implement the method readObject in an immutable object?

**Comment by essobedo** [comment]
@krzyk I could indeed apply the _Serialization Proxy Pattern_ as described [here](http://allenlsy.com/NOTES-of-Effective-Java-10/#78.-consider-serialization-proxies-instead-of-serialized-instances), but it sounds to me like a very ugly hack, WDYT?

**Comment by essobedo** [comment]
@davvd could you please affect it to someone?

**Comment by essobedo** [comment]
@davvd please I need help here

**Comment by krzyk** [comment]
@essobedo I don't think that this is the place to discuss how to fix what is Findbugs complaining. It is more of a need for Findbugs explanation, qulice is just using it with all the checks enabled.

**Comment by essobedo** [comment]
@krzyk  as you know I'm very new here and I still don't get how everything works at teamed.io, I simply followed the recommendation of the reviewer of my PR. 
@dmzaytsev could you please explain more what you expect from the qulice team? maybe I misunderstood what you wanted exactly, thx in advance

**Comment by dmzaytsev** [comment]
@yegor256 I am aware about [a Getters/Setters problem] (http://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html). But what do we have to do in this case? actually [HttpException](https://github.com/yegor256/takes/blob/65f4712ea2e21c02ce4655ce700778b2600d25fd/src/main/java/org/takes/HttpException.java#L46) has  an accessor named  `code()`  instead of the expected name `getStatus()`. 
Which way is a best way ? Suppress  `PMD.BeanMembersShouldSerialize` in Qulice or right  in `HttpException` class ? what do you think?

@krzyk  I guess it looks like  a common issue with accessors which named not like a getter. This issue might be suppressed on Qulice level. That's why I have suggested to ask here. If you don't think so, we can  suppress the warning right in the class for sure.

**Comment by krzyk** [comment]
@dmzaytsev As for BeanMembersShouldSerialize, it has been removed in https://github.com/teamed/qulice/issues/675 But not yet released (I'm waiting for budget to fix a major bug - https://github.com/teamed/qulice/issues/706, releasing without it is pointless).

**Comment by essobedo** [comment]
@krzyk good to know it means that the way I fixed _HttpException_ is acceptable, right? What about the second problem with _RsForward_?
