### ISSUE TITLE
Qulice release 0.16.4 is too slow

### ISSUE THREAD

**Issue by HDouss** [teamed/qulice#767]
Using qulice for some time, I realized that 0.16.4 release is much slower than the older ones. I tried to integrate qulice checking in a [simple (rather small) project](https://github.com/hdouss/jeometry) with 3 sub modules. The table below compares the maven build time when:
* running the build without qulice check
* running the build with qulice 0.16.3
* running the build with qulice 0.16.4

Module | without qulice|with qulice 0.16.3 | with qulice 0.16.4 | Est. time taken by qulice 0.16.3 | Est. time taken by qulice 0.16.4
------------ | ------------- | ------------- | ------------- | ------------- | -------------
Module 1 | 7.5s | 21s | 1min24s | 13.5s | 1min16s
Module 2 | 4s | 11s | 1min04s | 7s | 60s
Module 3 | 3s | 10s | 34s | 7s | 31s

Every figure in this table is a mean build time of 3 builds. Even if these figures are not necessarily significant, it is obvious that 0.16.4 version has a performance issue (as I said before this was noticed in many other projects). I expect to figure out which new feature or which bug resolution has introduced this performance issue and to resolve it.

**Comment by krzyk** [comment]
@HDouss good catch, I think the problem appeared after #61

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I just added bug tag here

**Comment by davvd** [comment]
@hdouss thanks for the report, I topped your acc for 15 mins, payment ID `87713214`

**Comment by mkordas** [comment]
@krzyk @HDouss yes, the reason is here: https://github.com/teamed/qulice/pull/735/files#diff-2cf0472dd4aa25abe70bb2e0426ea000R154
Basically, Checkstyle has very slow startup time and this is known issue - it's just supposed to be started once per entire project. After the change we're initializing Checkstyle from scratch for every file...

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk OK, I put "urgent" label here

**Comment by davvd** [comment]
@dskalenko this task is yours, please help (see our key [principles of work](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html)). If you have any technical questions, don't hesitate to ask right here; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by dskalenko** [comment]
@krzyk 
@mkordas 
Could you please give me an advice -  how I can test it, I mean how I (or who will do review) can measure that after fix the performance problem is gone?

**Comment by mkordas** [comment]
@dskalenko It will be simple to verify. Now we bootstrap Checkstyle from
scratch for every file under check. After fix we should initialise
Checkstyle once per analysis.

**Comment by dskalenko** [comment]
@mkordas ok I see, thanks, I just thought about some test  ... :)

**Comment by mkordas** [comment]
@dskalenko unfortunately we don't have environment for running perf tests...

**Comment by dskalenko** [comment]
@mkordas 
Here is PR #778, Could you please take a look?

**Comment by dskalenko** [comment]
@HDouss 
Could you please take a look my fix PR #778

**Comment by HDouss** [comment]
@dskalenko Thanks !

**Comment by davvd** [comment]
@dskalenko done, I added **30 mins** in payment `89369930`, 169 hours and 51 mins spent to complete this

added +30 to your rating, now it is equal to [+60](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment]
@davvd this is not urgent

**Comment by davvd** [comment]
> @davvd this is not urgent

@krzyk thanks, I removed the "urgent" tag
