### ISSUE TITLE
Prevent having a normal parameter following directly a parameter with a parenthesis

### ISSUE THREAD

**Issue by essobedo** [teamed/qulice#773]
It could be nice to have a rule that prevents developers to write code like this:

```
StringUtils.join(
  Arrays.asList(
    "first line", "second line",
    StringUtils.join(Arrays.asList("a", "b"))
  ), "separator"
);
```
I believe that it is more readable to have a normal parameter following a parameter with parenthesis in the next line as this:

```
StringUtils.join(
  Arrays.asList(
    "first line", "second line",
    StringUtils.join(Arrays.asList("a", "b"))
  ),
  "separator"
);
```

As described [here](http://www.yegor256.com/2014/04/27/typical-mistakes-in-java-code.html#indentation)

**Comment by krzyk** [comment]
@essobedo yes, it is described there, but on the other hand the rule is (from the same page):
>...  you should put as much as possible on one line - within the limit of 80 characters.

**Comment by krzyk** [comment]
@essobedo Can we close this issue?
