### ISSUE TITLE
CheckstyleValidatorTest.java:700-701: add test for next situation...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#776]
Puzzle `715-2a207c32` in `qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java:700-701` has to be resolved: add test for next situation {@code return new ArrayList

();}... The puzzle was created by Viktor Kuchyn on 11-Mar-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I will find someone else, no problem

**Comment by davvd** [comment]
@krzyk Done, thanks all, closing..
