### ISSUE TITLE
Wrap.java:78-84: After fix issue mentioned in...

### ISSUE THREAD

**Issue by davvd** [teamed/qulice#787]
Puzzle `706-72bdab5d` in `qulice-findbugs/src/main/java/com/qulice/findbugs/Wrap.java:78-84` has to be resolved: After fix issue mentioned in comment https://github.com/teamed/qulice/issues/706#issuecomment-225943946 rollback the changes done in #706 then remove @Ignore above FindBugsValidatorTest.reportsIncorrectlyAddedThrows test and fix test findbugs-bed-bogus-exception-declaration. For the moment third item is done from comment https://github.com/teamed/qulice/issues/706#issuecomment-184611854... The puzzle was created by DSkalenko on 22-Jun-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by krzyk** [comment]
@davvd this is urgent

**Comment by davvd** [comment]
> @davvd this is urgent

@krzyk "urgent" label already in this issue

**Comment by davvd** [comment]
@dskalenko please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have; Total fixed cost of this task is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more info)

**Comment by krzyk** [comment]
@dskalenko Any updates?

**Comment by krzyk** [comment]
@dskalenko are you working on this issue?

**Comment by davvd** [comment]
@dskalenko you're working with this issue for 15 days already. as a reminder, don't forget to remove the `@todo` puzzle from the source code. added -30 to your rating, now it is equal to [+60](http://www.netbout.com/b/36376?open=rating)

**Comment by krzyk** [comment]
@dskalenko Are you working on this issue?

**Comment by davvd** [comment]
@dskalenko please stop here, the task is not yours any more. I'll give you something else; -60 added to your rating, current score is: [+0](http://www.netbout.com/b/36376?open=rating)

**Comment by davvd** [comment]
@krzyk Closing..
