### ISSUE TITLE
IndentationCheck

### ISSUE THREAD

**Issue by 54uso** [teamed/qulice#788]
When I coded like this:
```
21 @SuppressWarnings({
22    "PMD.ConstructorOnlyInitializesOrCallOtherConstructors",
23    "PMD.ConstructorShouldDoInitialization"
24 })
```
qulice hinted that:
> .java[24]: '}' have incorrect indentation level 0, expected level should be 4. (IndentationCheck)

But, I think the indentation is not wrong, and don't know the reason.

I hope you can give me a hand, thanks.

**Comment by krzyk** [comment]
There is an issue for this https://github.com/teamed/qulice/issues/411, for now you should format it like 
```
@SuppressWarnings({"PMD.ConstructorOnlyInitializesOrCallOtherConstructors",
    "PMD.ConstructorShouldDoInitialization"})
```

**Comment by krzyk** [comment]
@davvd this is duplicate

**Comment by krzyk** [comment]
@davvd this is duplicate

**Comment by krzyk** [comment]
@yegor256 @davvd doesn't notice my requests to close this issue as duplicate

**Comment by yegor256** [comment]
@krzyk I closed it
