### ISSUE TITLE
Suppressing FileLengthCheck is not working.

### ISSUE THREAD

**Issue by original-brownbear** [teamed/qulice#791]
Not sure if I may be doing it wrong, but I just worked on a 1008 lines file.
Put ` * @checkstyle FileLengthCheck (1100 lines)` in the JavaDoc of the class => still getting:

```
File length is 1,008 lines (max allowed is 1,000). (FileLengthCheck)
```

Bug right ? Or is it by design that this cannot be suppressed? :)

**Comment by davvd** [comment]
@krzyk take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by krzyk** [comment]
@original-brownbear I don't think there is a way to exclude FileLength check in checkstyle

**Comment by original-brownbear** [comment]
@krzyk ah ok :) I kinda figured this might be the case :) thanks!
