### ISSUE TITLE
Scala ? :)

### ISSUE THREAD

**Issue by original-brownbear** [teamed/qulice#796]
We have some Groovy support in Qulice as well as some Javascript support.
Not sure we want to spent the resources. 
But as of right now Scala outranks Groovy in popularity. 

Maybe we could add the Checkstyle analog for Scala [ScalaStyle](http://www.scalastyle.org/) to Qulice?
Also we could configure Findbugs to omit Scala files, a much requested feature in Findbugs, automatically.

I'd find this very useful in commercial projects of mine (using Qulice already :)) and would gladly volunteer some time for this (I see the joke ... :), but eventually I could get to it if interest existed).

**Comment by krzyk** [comment]
@original-brownbear I think this one will go together with https://github.com/teamed/qulice/issues/406 (see discussion there)

**Comment by original-brownbear** [comment]
@krzyk ah ok read it :) so when can we expect that Plugin API ? :D
