### ISSUE TITLE
Gradle Plugin

### ISSUE THREAD

**Issue by weisebrazil** [teamed/qulice#797]
I'd like to help and develop the gradle plugin project. What the goals/tasks Do I need to develop?

**Comment by davvd** [comment]
@krzyk please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by krzyk** [comment]
@weisebrazil there is an open issue here: https://github.com/teamed/qulice/issues/612

**Comment by krzyk** [comment]
@weisebrazil ping

**Comment by krzyk** [comment]
@weisebrazil please close this issue

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#797` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
