### ISSUE TITLE
`final` modifier in catch block with multiple exceptions

### ISSUE THREAD

**Issue by xupyprmv** [teamed/qulice#799]
`final` modifier is not necessary if we have catch block that handling more than one type of exception. Exception variable is final by default.

http://docs.oracle.com/javase/7/docs/technotes/guides/language/catch-multiple.html#multiple

> Note: If a catch block handles more than one exception type, then the catch parameter is implicitly final...

**Comment by krzyk** [comment]
@xupyprmv But it would break the symmetry of single exception catch and multiple exception catch block. If we can't remove final from both then I wouldn't remove it from only one of those.
