### ISSUE TITLE
Remove EqualsAvoidNull check from Qulice

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#807]
Currently Qulice prohibits code like 

``` java
input.equals("contents")
```

in favour of 

``` java
"contents".equals(input)
```

The reason behind this is to avoid null pointer exceptions when `input` is `null`. However, IMO it's just hiding a problem, while code should be fragile. Moreover, in well written code `input` should never be `null` anyway.

Second reason to remove this check is that inverted notation is unnatural and less readable.

In scope of this issue I expect that check is removed and test is added proving that first syntax is allowed.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk added "bug" tag to this issue

**Comment by davvd** [comment]
@mkordas thanks for the report, I topped your acc for 15 mins, payment ID `57c3fe5a6d5f4b008819f535`

**Comment by kanghj** [comment]
@davvd @mkordas I have made PR #807 for this.

**Comment by mkordas** [comment]
@kanghj #807 is this issue :)

**Comment by kanghj** [comment]
@mkordas, my bad! Edited the original comment

**Comment by davvd** [comment]
> @davvd @mkordas I have made PR #809 for this.

@kanghj thank you!

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/807#issuecomment-385074282))

@krzyk Job [#807](https://github.com/teamed/qulice/issues/807) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/807#issuecomment-385074282))

@krzyk Thanks for your contribution, @mkordas[/z](https://www.0crat.com/u/mkordas)! If you would be a member of [the project](https://www.0crat.com/p/C3T49A35L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by krzyk** [comment]
@mkordas Change was merged in #809, please close

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by mkordas** [comment]
@krzyk thanks for merging!

**Comment by 0crat** [comment]
The job [#807](https://github.com/teamed/qulice/issues/807) is now out of scope
