### ISSUE TITLE
Checkstyle dependency is outdated

### ISSUE THREAD

**Issue by exper0** [teamed/qulice#815]
qulice-checkstyle uses checkstyle 6.15. There is new major version available - 7. Let's upgrade to latest version (7.2 from what I see at the moment)

**Comment by davvd** [comment]
@krzyk please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by krzyk** [comment]
@exper0 Checkstyle will be upgraded in #880

**Comment by longtimeago** [comment]
@exper0 @krzyk actually, current checkstyle version 8.10 depends on `antlr4-runtime`. It will conflict with `antl3-runtime` from `qulice-findbugs` -> `xembly`.
Easiest way IMO is to get rid from xemby in `qulice-findbugs`

**Comment by longtimeago** [comment]
I can do that if there is someone in charge of merging and releasing here :)

**Comment by krzyk** [comment]
@longtimeago I'm here :)

**Comment by krzyk** [comment]
@exper0 please close this issue, it has been fixed in https://github.com/teamed/qulice/issues/880

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#815` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
