### ISSUE TITLE
Let's upgrade qulice to use PMD 6.1.0

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#820]
It promises significant performance improvements
http://mvnrepository.com/artifact/net.sourceforge.pmd/pmd/6.1.0
which is very crucial for big modules

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by filfreire** [comment]
@longtimeago latest version is `6.1.0` http://mvnrepository.com/artifact/net.sourceforge.pmd/pmd/6.1.0, we could change the title and description of this issue.

/cc @yegor256

**Comment by krzyk** [comment]
@longtimeago ping, please close this one

**Comment by longtimeago** [comment]
@krzyk yup, thanks!

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#820` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
