### ISSUE TITLE
The required Javadoc class comments seem overly complicated

### ISSUE THREAD

**Issue by nqafield** [teamed/qulice#823]
A brief description of what a class represents is no doubt often useful, but the rest seems unnecessary.

- The comments actually clutter and lengthen the file making it harder to mentally process, not easier.
- There doesn't seem to be any point knowing the (original) author of a class. This can be found out from version control but isn't it also irrelevant once enough changes have happened?
- I haven't been able to ascertain the usefulness of the @version and @since things.

**Would it be possible to only require the description mentioned above?**

(See further discussion here: https://github.com/yegor256/eo/issues/108)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by krzyk** [comment]
@pa9ey 
* `@author`, it was already reported here - https://github.com/teamed/qulice/issues/761 (but no budget to work on it)
* `@version` I don't find it useful (was used in the cvs/svn days, but in git, I haven't seen it much - one has to enable it explicitly in .gitattributes) - so I agree, we should get rid of it.
* `@since` that one I find useful, when you use an older library and read newer javadocs, or in similar cases (JDK API is a good example, they don't keep it everywhere, but it is useful).

**Comment by pa9ey** [comment]
Thanks for the info @krzyk.

**Comment by pa9ey** [comment]
So, do I close this? And/or do I open an issue about getting rid of `@version`?

**Comment by krzyk** [comment]
@0crat in

**Comment by nqafield** [comment]
@0crat apply

**Comment by 0crat** [comment]
> @0crat apply ([here](https://github.com/teamed/qulice/issues/823#issuecomment-385055168))

@nqafield Can't understand "apply", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@nqafield If you want to apply go to https://www.0crat.com/join and fill out the form

**Comment by nqafield** [comment]
Thanks @krzyk. Not too bothered about joining the project (except that @0crat suggested it - but I don't actually think I'm much use at the moment) but I've reported the issue here: #882

**Comment by krzyk** [comment]
@nqafield This issue you should report in https://github.com/zerocracy/farm/issues project (that's where @0crat comes from :) ).
As for joining, yeah this project is not on the board, you can join by saying `/apply C3T49A35L` (the code you can find in the url when you look at  [the project](https://www.0crat.com/p/C3T49A35L) link) in  in telegram chat with 0crat.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/teamed/qulice/issues/823#issuecomment-385061800); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by nqafield** [comment]
@0crat sorry! ;)

**Comment by 0crat** [comment]
> @0crat sorry! ;) ([here](https://github.com/teamed/qulice/issues/823#issuecomment-385063530))

@nqafield Can't understand "sorry!", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/823#issuecomment-385269251))

@krzyk The job [#823](https://github.com/teamed/qulice/issues/823) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/1191783014); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@nqafield please close this issue, the fix was merged to master in #886
