### ISSUE TITLE
ProhibitPublicStaticMethods false postive

### ISSUE THREAD

**Issue by praveendath92** [teamed/qulice#825]
When I use a slightly different signature for my `main` method.

```java
public static void main(final String[] args)
```

Any reason why this is not included in the exclusion list mentioned in https://github.com/teamed/qulice/issues/659#issue-129852722 ?

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by krzyk** [comment]
@praveendath92  It is intentional, there is no reason not to use varargs in the main method.

**Comment by praveendath92** [comment]
Agreed.

**Comment by 0crat** [comment]
Oops! Job `gh:teamed/qulice#825` was not in scope
