### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by filfreire** [teamed/qulice#854]
Tasks:
* Follow Github guideline https://github.com/blog/1184-contributing-guidelines of having a separate contributing file
* Replace "How to contribute" section's content with a link to CONTRIBUTING.md

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256 , @krzyk kindly follow-up on this

**Comment by krzyk** [comment]
@filfreire I'm not sure if moving our short "How to contribute" section to separate file would help, it will be harder to find and it won't make README.md much smaller.

**Comment by filfreire** [comment]
@krzyk only benefit was in adding the templates in order for people to get notified with that information when opening an Issue/PR. But I agree that there is no harm in having that section remaining in README.md file.

I'm closing this issue and my submitted PR, since @yegor256 already did much of the work, over here: https://github.com/teamed/qulice/tree/master/.github

Thank you for following-up though 👍
