### ISSUE TITLE
ChecksTest skipped during merge phase for some reason

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#859]
Take a looks at the build http://www.rultor.com/t/13190-338250233
Moreover, if I run `com.qulice.checkstyle.ChecksTest` now manually from IDE I got
```java
java.lang.AssertionError: 
Expected: Line no.10 ('Reference to instance variable 'number' needs "this.".') not reported by ChecksTest/RequireThisCheck: ''
     but: was <false>
Expected :Line no.10 ('Reference to instance variable 'number' needs "this.".') not reported by ChecksTest/RequireThisCheck: ''
```

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by longtimeago** [comment]
Actually, building the project with `mvn clean install`
- **passes** when building from root folder (all modules) because `com.qulice.checkstyle.ChecksTest` is not executed for some reason
- **fails** when building from `qulice-checkstyle` folder

**Comment by longtimeago** [comment]
wow ... after full build partial build of `qulice-checkstyle` passes as well; test runs but doesn't fail!

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/859#issuecomment-385870199))

@krzyk Job [#859](https://github.com/teamed/qulice/issues/859) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/859#issuecomment-385870199))

@krzyk Thanks for your contribution, @longtimeago[/z](https://www.0crat.com/u/longtimeago)! If you would be a member of [the project](https://www.0crat.com/p/C3T49A35L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by krzyk** [comment]
@longtimeago Is this one also working after build fixes?

**Comment by longtimeago** [comment]
@krzyk now it passes, thanks!

**Comment by 0crat** [comment]
The job [#859](https://github.com/teamed/qulice/issues/859) is now out of scope
