### ISSUE TITLE
Create Qulice Github's badge

### ISSUE THREAD

**Issue by filfreire** [teamed/qulice#860]
Create an SVG Qulice Github's badge so that projects that use Qulice can include the badge in their README files.

Example badge (MIT license)
```[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)```
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256 FYI

**Comment by yegor256** [comment]
@filfreire you can use this one: https://img.shields.io/badge/qulice-good-green.svg (it's self generated)

**Comment by filfreire** [comment]
@yegor256 thanks

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:teamed/qulice#860`.

**Comment by 0crat** [comment]
Oops! Job `gh:teamed/qulice#860` is not in scope.
