### ISSUE TITLE
Stop checking "abstract class name" rules

### ISSUE THREAD

**Issue by llorllale** [teamed/qulice#863]
(continued from yegor256/cactoos#557)

We should remove the ~PMD.TooManyMethods~ PMD.AbstractNaming and AbstractClassName (checkstyle) checks as per the latest developments following the [webinar](https://www.youtube.com/watch?v=Wcy53ZSF78o) on [Decorating Envelopes](http://www.yegor256.com/2017/01/31/decorating-envelopes.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.zerocracy.farm.sync.Terminator.submit(Terminator.java:106)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:97)
	at com.zerocracy.farm.strict.StrictProject.acq(StrictProject.java:117)
	at com.zerocracy.farm.props.PropsProject.acq(PropsProject.java:78)
	at com.zerocracy.farm.footprint.FtProject.acq(FtProject.java:67)
	at com.zerocracy.farm.uplinked.UplinkedProject.lambda$acq$4(UplinkedProject.java:99)
	at org.cactoos.scalar.Ternary.value(Ternary.java:123)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.app...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
@krzyk[/z](http://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by krzyk** [comment]
@llorllale I get why we should remove the `AbstractClassName` check, but why also `TooManyMethods`?

**Comment by llorllale** [comment]
@krzyk it was a typo. I've fixed the description

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/863#issuecomment-385033648))

@krzyk Job [#863](https://github.com/teamed/qulice/issues/863) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/863#issuecomment-385205038))

@krzyk The job [#863](https://github.com/teamed/qulice/issues/863) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/1182087263); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@llorllale Changes fixing this (#885) were merged to master, please close this issue.

**Comment by llorllale** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#863](https://github.com/teamed/qulice/issues/863) is now out of scope
