### ISSUE TITLE
@author Tag text pattern produces false positive

### ISSUE THREAD

**Issue by aliceice** [teamed/qulice#866]
Using following JavaDoc

```
/**
* @author Elena Ihde-Simon (elena.ihde-simon@posteo.de)
*/
```

produces this error:

`tag text 'Elena Ihde-Simon (elena.ihde-simon@posteo.de)' does not match the pattern '^([A-Z](\.|[a-z]+) )+\([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\)$' (JavadocTagsCheck)
`

I suppose the Regex is missing the `-` as a valid character for names.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by krzyk** [comment]
@aliceice This is covered by #761, where we want to remove `@author` tag completely, so there is no point in fixing it.

**Comment by aliceice** [comment]
@krzyk Sorry, I didn't see that issue. But as it is postponed, and I'm trying to implement https://github.com/yegor256/cactoos/issues/609, it is kinda blocking my PR. What do you suggest?

**Comment by krzyk** [comment]
@aliceice Let's ask @yegor256 How should we proceed here? Should we unpostponed #761 (if so, how, is @davvd still here?)?

**Comment by aliceice** [comment]
@yegor256 ping

**Comment by krzyk** [comment]
@aliceice Please close this issue, we will proceed with #761

**Comment by krzyk** [comment]
@aliceice ping

**Comment by krzyk** [comment]
@aliceice no longer valid

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#866` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
