### ISSUE TITLE
Different line length limit for groovy and java files

### ISSUE THREAD

**Issue by g4s8** [teamed/qulice#867]
It's not clear why line length limit for groovy and java files is different:
 - java - 80 chars
 - groovy - 120 chars

I think 120 chars would be OK for all file-type.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by yegor256** [comment]
@krzyk do we still check Groovy files in Qulice? We shouldn't. As for the Java, I would suggest to migrate to 100 chars limit. 80 is indeed too narrow.. WDYT?

**Comment by krzyk** [comment]
@yegor256 We check only java files for line length. OK so let's go with 100 chars for java. @g4s8 could you update your comment?
Groovy is checked using codenarc and not using qulice and we will increase java limit to 100 chars.

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/867#issuecomment-449873317))

@krzyk Job [#867](https://github.com/teamed/qulice/issues/867) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@g4s8 change has been merged to master and will be released in `0.18.9` in hour or two, please close this issue

**Comment by g4s8** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#867](https://github.com/teamed/qulice/issues/867) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
