### ISSUE TITLE
Following the instructions to join Qulice project doesn't work

### ISSUE THREAD

**Issue by nqafield** [teamed/qulice#882]
@0crat suggests that it's possible to join the project, but the [instructions](http://www.zerocracy.com/policy.html#2) don't work.

![image](https://user-images.githubusercontent.com/18754996/39379120-3bfa9ec2-4a52-11e8-9e90-a43bd1619f90.png)

Is it because this project is not on the board?

(I'm not complaining that I can't join the project, just that there seems to be a problem here. If it's not on the Board, perhaps @0crat shouldn't suggest you can join it in that way.)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@nqafield[/z](https://www.0crat.com/u/nqafield) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by nqafield** [comment]
This should probably be a bug on the zerocrat project, but couldn't find where to report that.

**Comment by nqafield** [comment]
See here: https://github.com/zerocracy/farm/issues/975

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
