### ISSUE TITLE
NullPointerException for this POM

### ISSUE THREAD

**Issue by llorllale** [teamed/qulice#891]
An NPE is being thrown from this line:
https://github.com/teamed/qulice/blob/04be11b58b7a070e1b0b8355a80f7b5d819c1a21/qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultMavenEnvironment.java#L140-L141

For [this](https://github.com/llorllale/s3auth/tree/371) project.

What's wrong?

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/891#issuecomment-385517677))

@krzyk Job [#891](https://github.com/teamed/qulice/issues/891) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by llorllale** [comment]
@krzyk ping

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@llorllale OK, the problem is in hibernate validator.
We don't support:
```
        <relocation>                                                            
            <groupId>org.hibernate.validator</groupId>                          
        </relocation>  
```

Hibernate decided to migrate validator groupId `org.hibernate` -> `org.hibernate.validator` and used this `relocation` which causes NPE here. I still don't know how to fix it in qulice.
But you can proceed with you tasks, just replace groupId org.hibernate with org.hibernate.validator (only for hibernate validators).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by llorllale** [comment]
@krzyk thanks

**Comment by 0crat** [comment]
The job [#891](https://github.com/teamed/qulice/issues/891) is now out of scope
