### ISSUE TITLE
Should ProtectedMethodInFinalClass really exist?

### ISSUE THREAD

**Issue by victornoel** [teamed/qulice#901]
When implementing a final class that extends an abstract class with protected methods, it feels very wrong to me to mark the implementations of those methods as being public.

But with the rule `ProtectedMethodInFinalClassCheck`, I am forced to make them public.
This exposes undesired internal behaviour to the outside and thus seem a bad idea.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@victornoel why would you use `protected` in such class? Doesn't default also work for the cases that you need?

**Comment by victornoel** [comment]
@krzyk see the following example:
```java
public abstract class AbstractClass {
    protected abstract void method();
}

// here qulice complains with ProtectedMethodInFinalClassCheck
public final class FinalClass extends AbstractClass {
    @Override
    protected void method() {
        // implem
    }
}

// here javac complains with "Cannot reduce the visibility of the inherited method from AbstractClass"
public final class FinalClass extends AbstractClass {
    @Override
    void method() {
        // implem
    }
}

// here we made a method not meant to be exposed public
public final class FinalClass extends AbstractClass {
    @Override
    public void method() {
        // implem
    }
}
```

To answer you question: default does not work in that case, so I have to make it public, which I think is worst design than having a protected method in a final class (or it should only be for non-overridden methods).

**Comment by krzyk** [comment]
@victornoel Oh, in that case it should be excluded in case of `@Override`

**Comment by krzyk** [comment]
@0crat in

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/901#issuecomment-408598468))

@krzyk Job [#901](https://github.com/teamed/qulice/issues/901) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/901#issuecomment-408598589))

@krzyk The job [#901](https://github.com/teamed/qulice/issues/901) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/2091061098); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@victornoel fixed in #915, it will be available with next qulice release. Please close this issue.

**Comment by victornoel** [comment]
@krzyk don't you think the rule should be stricter and only allow it in case there is an override AND the superclass method is protected?

**Comment by krzyk** [comment]
@victornoel but this will be quite a narrow case when someone widens the scope from default to protected, and it has to be in a class that has visibility of that default method (so in the same package). Please create a new bug for this (we will probably need to convert this to PMD check in that case).

**Comment by victornoel** [comment]
@krzyk yep, I understand, this issue is fixed anyway :)

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#901](https://github.com/teamed/qulice/issues/901) is now out of scope
