### ISSUE TITLE
let's get rid of xml validation

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#902]
We already have [xcop](https://github.com/yegor256/xcop) for that. Let's remove this functionality from Qulice entirely.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by krzyk** [comment]
@yegor256 I think you removed it already in https://github.com/teamed/qulice/commit/634cf6f7b790255405bd4d3a42ffd672a0290b9e
Are there some leftovers (e.g. in checkstyle or pmd) that are still complaining?

**Comment by yegor256** [comment]
@krzyk oops, my bad :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
