### ISSUE TITLE
let's get rid of Codenarc

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#903]
Let's get rid of it. Qulice is for Java code only. Groovy must not be of our concern.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by krzyk** [comment]
@yegor256 Done :) - https://github.com/teamed/qulice/commit/22c4253b88e4038e3886098a977e116a9b429da5

**Comment by yegor256** [comment]
@krzyk I need some memory pills :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
