### ISSUE TITLE
let's get rid of jslint

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#904]
Let's stop validating JavaScript sources with jslint. Qulice is for Java code only.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by krzyk** [comment]
@yegor256 Done :) - https://github.com/teamed/qulice/commit/8359dff3b8412c27110c9b58eb01f7afb337ae10

**Comment by yegor256** [comment]
@krzyk damn :) thanks.
