### ISSUE TITLE
Problems after upgrading to qulice 0.17.3

### ISSUE THREAD

**Issue by paulodamaso** [teamed/qulice#909]
I started having thee following problem after updating to qulice `0.17.3`:
```
---------------------------------------------------
Exception in thread "main" java.lang.Error: Invalid escape character at line 1 column 2.
	at net.sourceforge.pmd.lang.ast.JavaCharStream.readChar(JavaCharStream.java:331)
	at net.sourceforge.pmd.lang.ast.JavaCharStream.BeginToken(JavaCharStream.java:193)
	at net.sourceforge.pmd.lang.java.ast.JavaParserTokenManager.getNextToken(JavaParserTokenManager.java:2159)
	at net.sourceforge.pmd.lang.java.ast.JavaParser.<init>(JavaParser.java:10903)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.createJavaParser(AbstractJavaParser.java:42)
	at net.sourceforge.pmd.lang.java.Java18Parser.createJavaParser(Java18Parser.java:23)
	at net.sourceforge.pmd.lang.java.AbstractJavaParser.parse(AbstractJavaParser.java:56)
	at net.sourceforge.pmd.SourceCodeProcessor.parse(SourceCodeProcessor.java:91)
	at net.sourceforge.pmd.SourceCodeProcessor.processSource(SourceCodeProcessor.java:138)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:76)
	at net.sourceforge.pmd.SourceCodeProcessor.processSourceCode(SourceCodeProcessor.java:43)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:79)
	at net.sourceforge.pmd.processor.PmdRunnable.call(PmdRunnable.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This happens after `License.txt` parsing. Running maven with `-X` option to does not prints anything different to console.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@krzyk I'm trying to run it against https://github.com/zerocracy/farm master branch. I get this result after updating `qulice` version in `pom.xml` to `0.17.3`.

**Comment by krzyk** [comment]
@paulodamaso the problem is with this file https://github.com/zerocracy/farm/blob/master/src/main/resources/com/zerocracy/tools/layout.tex

PMD interprets `\usepackage{setspace}` as a Java escape sequence

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/909#issuecomment-403221015))

@krzyk Job [#909](https://github.com/teamed/qulice/issues/909) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#909](https://github.com/teamed/qulice/issues/909); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by paulodamaso** [comment]
@krzyk Thanks! It would be nice to have a verbose mode showing which file is currently being analyzed, WDYT?

**Comment by paulodamaso** [comment]
@krzyk Excluded all `tex` files from `pom.xml`:
```
                <exclude>pmd:/src/main/resources/com/zerocracy/tk/tools/.*</exclude>
                <exclude>pmd:/src/main/resources/com/zerocracy/pm/cost/.*</exclude>
```
But qulice keeps showing the same error.

**Comment by krzyk** [comment]
@paulodamaso the problem here is that qulice excludes the violation *after* PMD reads it, so it is not exludable

**Comment by krzyk** [comment]
@paulodamaso in version `0.17.4` excludes should work as expected, if it does please close this issue

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/909#issuecomment-403306895))

@krzyk The job [#909](https://github.com/teamed/qulice/issues/909) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/1891840367); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by paulodamaso** [comment]
@krzyk Logging file being processed is ok, thanks, but I'm still having the same error in `layout.tex` even with `<exclude>pmd:/src/main/resources/com/zerocracy/tools/layout.tex</exclude>` :
```
[DEBUG] Processing file: C:\git\zerocracy-farm\src\main\resources\com\zerocracy\tools\layout.tex
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min (Wall Clock)
[INFO] Finished at: 2018-07-09T00:40:18-03:00
[INFO] Final Memory: 76M/838M
[INFO] ------------------------------------------------------------------------
[ERROR] Invalid escape character at line 1 column 2. -> [Help 1]
java.lang.Error: Invalid escape character at line 1 column 2.
```

**Comment by krzyk** [comment]
@paulodamaso to exclude correctly you need to use a full regular expression on the path.
So in your case it would be:
```
<exclude>pmd:.*/src/main/resources/com/zerocracy/tools/layout.tex</exclude>
```

You could also try a general one:
``
<exclude>pmd:.*\..tex</exclude>
```

**Comment by paulodamaso** [comment]
@krzyk Thanks for the fixes and the and the explanation on `exclude`, it's all working as expected now.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#909](https://github.com/teamed/qulice/issues/909) is now out of scope
