### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.commons.lang3.mutable.MutableInt.getAndIncrement()I

### ISSUE THREAD

**Issue by llorllale** [teamed/qulice#925]
qulice version: 0.18

```
$ mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-134-generic", arch: "amd64", family: "unix"
```

Stacktrace:
[stacktrace.txt](https://github.com/teamed/qulice/files/2321083/stacktrace.txt)

**Comment by krzyk** [comment]
@llorllale please write what code triggers that, or is it on any code?

**Comment by driver733** [comment]
I also get the discussed error. ([Error log with stack trace](https://travis-ci.org/driver733/VK-Uploader/builds/415803418?utm_source=github_status&utm_medium=notification))

**Comment by carlosmiranda** [comment]
@llorllale @krzyk it appears to be an issue with lambda expressions. This code will bork Qulice and produce the aforementioned error:

```java
public final class TestClass {

    public String lowercase(final String str) {
        return this.exec(str, (input) -> input.toLowerCase());
    }

    public String exec(
        final String str,
        final Function<String, String> func
    ) {
        return func.apply(str);
    }
}
```

As a workaround I declared `commons-lang3` as a dependency in the Qulice plugin declaration in order to manually set the version to the latest:

```xml
          <plugin>
            <groupId>com.qulice</groupId>
            <artifactId>qulice-maven-plugin</artifactId>
            <version>0.18</version>
            <configuration>
              <excludes combine.children="append">
                <exclude>checkstyle:/src/site/resources/.*</exclude>
                <exclude>findbugs:.*</exclude>
              </excludes>
            </configuration>
            <dependencies>
              <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.8</version>
              </dependency>
            </dependencies>
          </plugin>
```

**Comment by krzyk** [comment]
@carlosmiranda thanks

**Comment by krzyk** [comment]
@0crat in

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/925#issuecomment-416467812))

@krzyk Job [#925](https://github.com/teamed/qulice/issues/925) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/925#issuecomment-416467847))

@krzyk The job [#925](https://github.com/teamed/qulice/issues/925) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/2400739073); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@llorllale @carlosmiranda @driver733 It should be fixed in 0.18.1
@llorllale please close this issue if it works

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@llorllale ping

**Comment by krzyk** [comment]
@llorllale ping

**Comment by krzyk** [comment]
@llorllale can you close this?

**Comment by llorllale** [comment]
@krzyk I no longer get the error when I try against `HEAD` in `master`, thanks

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#925](https://github.com/teamed/qulice/issues/925); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#925](https://github.com/teamed/qulice/issues/925) is now out of scope
