### ISSUE TITLE
Qulice requires javadocs in unit tests

### ISSUE THREAD

**Issue by golszewski86** [teamed/qulice#944]
Javadocs are intended to be API documentation. There is no reason to add javadocs to the test methods because they are not API.
However qulice reports an error when test methods, classes and fields do not have javadoc comments.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by golszewski86** [comment]
Thanks @krzyk

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#944` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
