### ISSUE TITLE
Can you consider extending lile length?

### ISSUE THREAD

**Issue by golszewski86** [teamed/qulice#946]
The maximum line length in qulice is 80 characters. I don't know why is that, but it seems it doesn't fit today's world when professional developers work mostly with FullHD or bigger resolutions.

I know that short line encourages us to write compact code. This is good. But it causes code to grow vertically instead of horizontally and it looks ridiculous in Full HD resolution.

Can we have the line length at least configurable so I can use for example 100? I don't want to throw qulice away just because of line length constraint.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by golszewski86** [comment]
One more thing @krzyk and @yegor256  I don't get it why can't you let users configure line length that works best for them...

**Comment by krzyk** [comment]
@golszewski86 Generally qulice is not something you configure, you either accept all of its requirements or not. This way if you have a project that uses qulice, you know what to expect, if you want configurability you can use checkstyle/pmd/findbugs manually.

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#946` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
