### ISSUE TITLE
pom.xml:103: Dummy todo to test if it works -->

### ISSUE THREAD

**Issue by 0pdd** [teamed/qulice#949]
The puzzle `123-42c66e69` from #123 has to be resolved: 

https://github.com/teamed/qulice/blob/566c3640b7fee182839a0580012e6130121e7928/qulice-checkstyle/pom.xml#L103-L103

The puzzle was created by krzyk on 01-May-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#949](https://github.com/teamed/qulice/issues/949) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@krzyk I wasn't able to discover what to do in this ticket, please improve its description

**Comment by krzyk** [comment]
@0crat out

**Comment by krzyk** [comment]
@paulodamaso this one was form the time the PDD wasn't working in qulice

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/teamed/qulice/issues/949#issuecomment-456831718))

@krzyk GitHub issue is still open, won't close

**Comment by krzyk** [comment]
@0crat help

**Comment by 0crat** [comment]
> @0crat help ([here](https://github.com/teamed/qulice/issues/949#issuecomment-456832473))

@krzyk Can't understand "help", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by paulodamaso** [comment]
@krzyk I think that you can resign me from it, IIRC 0crts does not penalize anyone for this.

**Comment by krzyk** [comment]
@0crat resign

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/teamed/qulice/issues/949#issuecomment-457104348))

@krzyk The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#949](https://github.com/teamed/qulice/issues/949), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/949#issuecomment-457104655))

@krzyk The job [#949](https://github.com/teamed/qulice/issues/949) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/7893b336-2d35-42b4-a18f-95ac7bb715c2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `123-42c66e69` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#949](https://github.com/teamed/qulice/issues/949) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
