### ISSUE TITLE
UseStringIsEmptyRule.java:55-60: This rule currently...

### ISSUE THREAD

**Issue by 0pdd** [teamed/qulice#950]
The puzzle `801-1b19be41` from #801 has to be resolved: 

https://github.com/teamed/qulice/blob/566c3640b7fee182839a0580012e6130121e7928/qulice-pmd/src/main/java/com/qulice/pmd/rules/UseStringIsEmptyRule.java#L55-L60

The puzzle was created by rultor on 03-May-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#950](https://github.com/teamed/qulice/issues/950) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@0crat wait for #979

**Comment by 0crat** [comment]
> @0crat wait for #979  ([here](https://github.com/teamed/qulice/issues/950#issuecomment-451432052))

@paulodamaso The impediment for [#950](https://github.com/teamed/qulice/issues/950) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `801-1b19be41` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1000](https://github.com/teamed/qulice/issues/1000), [#999](https://github.com/teamed/qulice/issues/999) are still not solved.

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details into registered [impediment](https://github.com/teamed/qulice/issues/950#issuecomment-451432052). Not clear what exactly you were waiting for.

**Comment by paulodamaso** [comment]
@ypshenychka Added.

**Comment by ypshenychka** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/teamed/qulice/issues/950#issuecomment-456816948))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1016](https://github.com/teamed/qulice/issues/1016), [#999](https://github.com/teamed/qulice/issues/999) are still not solved; solved: [#1000](https://github.com/teamed/qulice/issues/1000).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1000](https://github.com/teamed/qulice/issues/1000), [#1016](https://github.com/teamed/qulice/issues/1016), [#999](https://github.com/teamed/qulice/issues/999).
