### ISSUE TITLE
"Cannot initialize module SuppressionFilter" executionerror in version 0.18.3

### ISSUE THREAD

**Issue by filfreire** [teamed/qulice#951]
@krzyk when I try to use the latest version of qulice in one of my repos (https://github.com/filfreire/hercule), when I issue `mvn clean install` command, there's the following error:

```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.18.3:check (default) on project hercule: Execution default of goal com.qulice:qulice-maven-plugin:0.18.3:check failed: Failed to configure checker: cannot initialize module SuppressionFilter - Unable to find: /home/r/repo/qulice-checkstyle/src/main/resources/com/qulice/checkstyle/suppressions.xml -> [Help 1]
```

If I use version `0.18.2` instead, I don't get this type of execution error, and qulice seems to run normally.

Also possibly connected to latest works in issue https://github.com/teamed/qulice/issues/798

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@filfreire thanks

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/951#issuecomment-443488977))

@krzyk Job [#951](https://github.com/teamed/qulice/issues/951) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/951#issuecomment-444114157))

@krzyk The job [#951](https://github.com/teamed/qulice/issues/951) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/326f0299-c278-4949-ac30-6f0418e16df7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@filfreire please try with 0.18.4 it should work now

**Comment by filfreire** [comment]
@krzyk seems to be fixed in 0.18.4, closing this issue.

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#951](https://github.com/teamed/qulice/issues/951) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
