### ISSUE TITLE
EmptyLineSeparatorCheck conflicts with EmptyLinesCheck

### ISSUE THREAD

**Issue by victornoel** [teamed/qulice#953]
For example in Takes, in the following code at the following line: https://github.com/yegor256/takes/blob/3e53d1278d8a882343b877c5d7d2c04966491478/src/test/java/org/takes/http/BkBasicTest.java#L143

If don't separate the two methods with an empty line, you get:
`[INFO] Checkstyle: src/test/java/org/takes/http/BkBasicTest.java[143]: 'METHOD_DEF' should be separated from previous statement. (EmptyLineSeparatorCheck)`

If you add a line you get:
`[INFO] Checkstyle: src/test/java/org/takes/http/BkBasicTest.java[143]: Empty line inside method (EmptyLinesCheck)`

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@victornoel is this for 0.18.2?

**Comment by victornoel** [comment]
@krzyk actually it is for both 0.18.2 and 0.17.6

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/953#issuecomment-443743350))

@krzyk Job [#953](https://github.com/teamed/qulice/issues/953) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/953#issuecomment-443743398))

@krzyk The job [#953](https://github.com/teamed/qulice/issues/953) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/bf896bc0-c3ab-4945-8250-1eced6240495); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@victornoel The issue is because there is a anonymous class inside anonymous class (which is not the best style, I think this should be prohibited in qulice) so for a fast workaround, convert one of those anonymous classes into an inner class

**Comment by krzyk** [comment]
@victornoel this should be fixed in `0.18.5`, please close this issue

**Comment by victornoel** [comment]
@krzyk excellent, thanks!

**Comment by 0crat** [comment]
Job was finished in 46 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#953](https://github.com/teamed/qulice/issues/953) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
