### ISSUE TITLE
Checkstyle and PMD upgrade

### ISSUE THREAD

**Issue by fabriciofx** [teamed/qulice#961]
The latest version of Checkstyle is 8.15 and PMD is 6.10.0. So, let's update them.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@fabriciofx please update the description/title to do upgrade of both Checkstyle and PMD.

**Comment by fabriciofx** [comment]
@krzyk Done.

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/961#issuecomment-446635084))

@krzyk Job [#961](https://github.com/teamed/qulice/issues/961) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/961#issuecomment-449551801))

@krzyk The job [#961](https://github.com/teamed/qulice/issues/961) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/5d260ee2-ec39-4a28-bc50-234b6133f5bd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@fabriciofx checkstyle and PMD have been upgraded in #968, please close this issue

**Comment by fabriciofx** [comment]
Closed by #968.

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#961](https://github.com/teamed/qulice/issues/961) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
