### ISSUE TITLE
Update jcabi parent 0.49.3

### ISSUE THREAD

**Issue by fabriciofx** [teamed/qulice#966]
Let's update jcabi parent to `0.49.3` because Qulice still has been using `0.40` version.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@0crat assign @korthout

**Comment by 0crat** [comment]
> @0crat assign @korthout  ([here](https://github.com/teamed/qulice/issues/966#issuecomment-457102802))

@krzyk The job [#966](https://github.com/teamed/qulice/issues/966) assigned to @korthout[/z](https://www.0crat.com/u/korthout), here is [why](https://www.0crat.com/footprint/C3T49A35L/54ca0ed7-0cf3-4648-9cf9-0ad8b67bd5ad); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @korthout[/z](https://www.0crat.com/u/korthout) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1009](https://github.com/teamed/qulice/issues/1009) is still not solved.

**Comment by korthout** [comment]
I think this can be closed, because #991 has been merged.

**Comment by krzyk** [comment]
@korthout you need to ask fabriciofx for that

**Comment by fabriciofx** [comment]
Closed by #991.

**Comment by 0crat** [comment]
Job [#966](https://github.com/teamed/qulice/issues/966) is not in the agenda of @korthout[/z](https://www.0crat.com/u/korthout), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#966](https://github.com/teamed/qulice/issues/966) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/teamed/qulice/issues/966#issuecomment-458498998))

@ypshenychka This is what I know about this job in [C3T49A35L](https://www.0crat.com/p/C3T49A35L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#966](https://github.com/teamed/qulice/issues/966) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 23hr
  * @korthout[/z](https://www.0crat.com/u/korthout) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3T49A35L?q=%7Bjob%3A%27gh%3Ateamed%2Fqulice%23966%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@fabriciofx and @korthout According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job always start with a name of a user they are addressed to

Please correct your messages by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@korthout According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add reference to PR. You can reference it by indicating this issue in PR's description.

**Comment by fabriciofx** [comment]
@ypshenychka Sorry, but the only message I didn't indicate and addressee was the first (which opens the ticket). Should I indicate it too? If yes, to who?

**Comment by ypshenychka** [comment]
@fabriciofx I mean this [one](https://github.com/teamed/qulice/issues/966#issuecomment-458090549).

**Comment by fabriciofx** [comment]
@ypshenychka So, when a close an issue I should address it to who?

**Comment by fabriciofx** [comment]
@ypshenychka Ok. I'll fix it. Thanks!

**Comment by ypshenychka** [comment]
@fabriciofx thanks

**Comment by korthout** [comment]
@ypshenychka done

**Comment by ypshenychka** [comment]
@korthout thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/teamed/qulice/issues/966#issuecomment-458526999))

@ypshenychka The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @korthout[/z](https://www.0crat.com/u/korthout)

**Comment by 0pdd** [comment]
@fabriciofx the only puzzle [#1009](https://github.com/teamed/qulice/issues/1009) is solved here.
