### ISSUE TITLE
LinguisticNaming should ignore overriden methods coming from super classes/interfaces

### ISSUE THREAD

**Issue by victornoel** [teamed/qulice#972]
In takes, there is the following [code](https://github.com/yegor256/takes/blob/3e53d1278d8a882343b877c5d7d2c04966491478/src/main/java/org/takes/misc/EntryImpl.java) that raises the following error:
```
[INFO] PMD: src/main/java/org/takes/misc/EntryImpl.java[70-72]: Linguistics Antipattern - The setter 'setValue' should not return any type except void linguistically (LinguisticNaming)
``` 

But the method is coming from a super interface and thud can't be changed.

I believe qulice should ignore it.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@victornoel which version of qulice?

**Comment by victornoel** [comment]
@krzyk 0.18.8

**Comment by krzyk** [comment]
@victornoel I recently upgraded PMD, so please check qulice 0.18.8

**Comment by krzyk** [comment]
@victornoel do you have a code sample?

**Comment by victornoel** [comment]
@krzyk yes, see the description, there is a link to a code sample

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/972#issuecomment-449639027))

@krzyk Job [#972](https://github.com/teamed/qulice/issues/972) is now in scope, role is `DEV`

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/972#issuecomment-449697597))

@krzyk The job [#972](https://github.com/teamed/qulice/issues/972) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/9ff57d58-dab1-4699-ba9e-f669ac97e25b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@victornoel this has been fixed in #973, (to be released in 0.18.9), please close this issue

**Comment by krzyk** [comment]
@victornoel ping

**Comment by victornoel** [comment]
@krzyk sorry, Christmas and all ;)

**Comment by 0crat** [comment]
The job [#972](https://github.com/teamed/qulice/issues/972) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
