### ISSUE TITLE
PMD rule CallSuperInConstructor makes no sense

### ISSUE THREAD

**Issue by golszewski86** [teamed/qulice#982]
PMD rule CallSuperInConstructor requires an explicit call to superclass constructor, e.g.
```
public class Foo extends Bar(final String name) {
   super(); // required by CallSuperInConstructor rule
   this.name = name;
}
```

The rule description (https://pmd.github.io/pmd/pmd_rules_java_codestyle.html#callsuperinconstructor) only says that it is a good practice without referencing any source. So I've asked PMD developers and their answer was:
> this rule is part of the codestyle category. As such, it has no other reason than stylistic consistency.
(https://github.com/pmd/pmd/issues/1564)

I believe this rule actually enforces a bad practice:
- It requires one additional and completely unnecessary line of code
- It suggests that developer doesn't believe Java compiler works and inserts the super constructor call. See for example justification for the ckeckstyle ExplicitInitializationCheck rule: http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/ExplicitInitializationCheck.html

Given that, I think this rule should be disabled.

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T49A35L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by krzyk** [comment]
@yegor256 Any opinions on that? I agree with @golszewski86 that this rule is pointless.

**Comment by llorllale** [comment]
@krzyk it's also triggered for anonymous classes. See [this example](https://github.com/yegor256/cactoos/blob/67632d6cfffbbcbdc77c315c60215294c1dd708b/src/main/java/org/cactoos/iterable/IterableOf.java#L84)

**Comment by yegor256** [comment]
@krzyk I agree, let's get rid of it.

**Comment by krzyk** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/982#issuecomment-458922127))

@krzyk Job [#982](https://github.com/teamed/qulice/issues/982) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/teamed/qulice/issues/982#issuecomment-458922127))

@krzyk Thanks for your contribution, @golszewski86[/z](https://www.0crat.com/u/golszewski86)! If you would be a member of [the project](https://www.0crat.com/p/C3T49A35L), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#982](https://github.com/teamed/qulice/issues/982) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3T49A35L/8f7b3a05-3585-4709-88ed-8bd9f6a6c057); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@golszewski86 Merged, please close

**Comment by paulodamaso** [comment]
@0crat wait for closure

**Comment by paulodamaso** [comment]
@golszewski86 ping

**Comment by paulodamaso** [comment]
@krzyk ping

**Comment by 0crat** [comment]
> @0crat wait for closure ([here](https://github.com/teamed/qulice/issues/982#issuecomment-463782064))

@paulodamaso The impediment for [#982](https://github.com/teamed/qulice/issues/982) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@krzyk please take a look

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#982](https://github.com/teamed/qulice/issues/982); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by krzyk** [comment]
@paulodamaso I can't do much here, I can't close issues

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#982](https://github.com/teamed/qulice/issues/982); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) everybody who has role `DEV` is banned at [#982](https://github.com/teamed/qulice/issues/982); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by grzechol** [comment]
@paulodamaso, @krzyk Sorry guys I can't close the issue too...

**Comment by golszewski86** [comment]
Ooops wrong github account :) With this one I can

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#982` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#982](https://github.com/teamed/qulice/issues/982) is now out of scope
